Repository dotnet/efcore, pull requests merged in 2019-09, with the labels that each got.

#17601 [3.0] Remove suffix from Cosmos Metadata extensions
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeBuilderExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosModelBuilderExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosModelExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
  src/EFCore.Cosmos/Internal/CosmosModelValidator.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/KeyAccessExpression.cs
  src/EFCore.Cosmos/Query/Internal/ObjectAccessExpression.cs
  src/EFCore.Cosmos/Query/Internal/ObjectArrayProjectionExpression.cs
  src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
  src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
  src/EFCore.Cosmos/ValueGeneration/Internal/CosmosValueGeneratorSelector.cs
  src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
  test/EFCore.Cosmos.Tests/Metadata/CosmosBuilderExtensionsTest.cs
  test/EFCore.Cosmos.Tests/Metadata/CosmosMetadataExtensionsTest.cs
Labels: ask-mode, servicing-approved

#17600 [3.0] Set a default query cache size limit.
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Query/Internal/CompiledQueryCache.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: ask-mode, servicing-approved

#17603 [3.0] Use IMemoryCache for model caching.
  src/EFCore/Infrastructure/ModelSource.cs
  src/EFCore/Infrastructure/ModelSourceDependencies.cs
  test/EFCore.Tests/ModelSourceTest.cs
Labels: ask-mode, servicing-approved

#17651 [3.0] Perf: Skip visiting table inside ColumnExpression
  src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: ask-mode, servicing-approved

#17714 [release/3.0] Update Microsoft.Data.SqlClient to 1.0.19249.1
  eng/Versions.props
Labels: ask-mode

#17945 Update to 5.0 SDK
  Directory.Build.props
  Directory.Build.targets
  global.json
  src/dotnet-ef/dotnet-ef.nuspec
Labels: area-infrastructure

#18032 Update branding to 3.0.1
  eng/Versions.props
Labels: area-platform

#18027 [release/3.0] Switch to embedded package icon
  Directory.Build.props
  global.json
  packageIcon.png
  src/EFCore.Analyzers/EFCore.Analyzers.csproj
  src/EFCore.Analyzers/EFCore.Analyzers.nuspec
  src/EFCore.Analyzers/lib/netstandard1.3/_._
  src/EFCore.Tools/EFCore.Tools.csproj
  src/EFCore.Tools/EFCore.Tools.nuspec
  src/dotnet-ef/dotnet-ef.csproj
  src/dotnet-ef/dotnet-ef.nuspec
  src/dotnet-ef/lib/netcoreapp2.1/_._
Labels: area-infrastructure

#18133 Update branding to 3.1.0-preview2
  eng/Versions.props
Labels: area-platform
