Repository dotnet/efcore, pull requests merged in 2019-03, with the labels that each got.

#14975 Remove unused property passed to EntityMaterializerSource.CreateReadValueExpression
  src/EFCore.Cosmos/Query/Internal/EntityShaper.cs
  src/EFCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
  src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
  src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
  src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs
  src/EFCore/Metadata/Internal/PropertyParameterBinding.cs
  src/EFCore/Query/EntityQueryModelVisitor.cs
Labels: providers-beware

#14887 [2.2.x] Query: Add explicitCast for projection more robustly
  src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
  src/EFCore.Specification.Tests/Query/QueryTestBase.cs
  src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
  src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Labels: customer-reported, regression, servicing-approved

#15044 SQLite: Store char as TEXT by default
  src/EFCore.Relational/Storage/CharTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteCharTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
  src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
Labels: providers-beware

#15123 Migrations: Use parameter objects in MigrationsSqlGenerator
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
Labels: providers-beware

#15130 Migrations: Throw not implemented in MigrationSqlGenerator for computed columns
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  test/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
  test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
Labels: providers-beware

#15129 Propagate store generated values to all entries sharing a row.
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
  src/EFCore.InMemory/Storage/Internal/IInMemoryStore.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs
  src/EFCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
  src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/RelationalDatabase.cs
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/ICommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore/ChangeTracking/Internal/IStateManager.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/DbUpdateException.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  src/EFCore/Storage/Database.cs
  src/EFCore/Storage/IDatabase.cs
  test/EFCore.Relational.Specification.Tests/F1RelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
  test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs
  test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Labels: breaking-change, providers-beware

#15152 Close connection even if ambient transaction hasn't completed
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/RelationalConnection.cs
  test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
Labels: breaking-change, providers-fyi

#15168 Convention set builder refactoring
  src/EFCore.Abstractions/Properties/AbstractionsStrings.resx
  src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
  src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
  src/EFCore.Design/Metadata/Internal/ScaffoldingAnnotationNames.cs
  src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
  src/EFCore.InMemory/Metadata/Conventions/Internal/InMemoryConventionSetBuilder.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetCustomizer.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
  src/EFCore.Proxies/ProxiesServiceCollectionExtensions.cs
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Infrastructure/Internal/RelationalModelSource.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilderDependencies.cs
  src/EFCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilderDependencies.cs
  src/EFCore.Relational/Metadata/Conventions/Internal/TableNameFromDbSetConvention.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
  src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteConventionSetBuilder.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Infrastructure/IModelSource.cs
  src/EFCore/Infrastructure/ModelSource.cs
  src/EFCore/Infrastructure/ModelSourceDependencies.cs
  src/EFCore/Internal/DbContextServices.cs
  src/EFCore/Internal/IndentedStringBuilder.cs
  src/EFCore/Internal/NonCapturingLazyInitializer.cs
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/Infrastructure/IConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/IConventionSetCustomizer.cs
  src/EFCore/Metadata/Conventions/Infrastructure/IProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilderDependencies.cs
  src/EFCore/Metadata/Conventions/Internal/IConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/ICoreConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/NullConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/RuntimeConventionSetBuilder.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalConventionSetBuilderDependenciesTest.cs
  test/EFCore.Relational.Tests/Migrations/HistoryRepositoryDependenciesTest.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalOptionsExtension.cs
  test/EFCore.Relational.Tests/TestUtilities/TestRelationalConventionSetBuilder.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
  test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
  test/EFCore.Tests/DbContextServicesTest.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionSetBuilderTests.cs
  test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelSourceTest.cs
Labels: providers-beware

#15167 Map inherited CLR properties to the same column
  src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
  test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Labels: breaking-change

#15155 Chain coherence links up to aspnet/Extensions
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#15177 Do not specify `name` of the default (hosted) pools
  build/templates/default-build.yml
Labels: area-infrastructure
