Repository dotnet/efcore, pull requests merged in 2019-10, with the labels that each got.

#18170 [2.1] Fix to #13285 - UseRelationalNulls does not work with SELECT conditions
  src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
  src/EFCore.Relational/Query/Expressions/SelectExpression.cs
  src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
Labels: Servicing-approved

#18215 Fixup nuspecs master
  src/EFCore.Analyzers/EFCore.Analyzers.csproj
  src/EFCore.Analyzers/EFCore.Analyzers.nuspec
  src/EFCore.Analyzers/lib/netstandard1.3/_._
  src/dotnet-ef/dotnet-ef.csproj
  src/dotnet-ef/dotnet-ef.nuspec
  src/dotnet-ef/lib/netcoreapp2.1/_._
Labels: area-infrastructure

#18214 Remove unnecessary placeholders in .nuspec's
  src/EFCore.Analyzers/EFCore.Analyzers.csproj
  src/EFCore.Analyzers/EFCore.Analyzers.nuspec
  src/EFCore.Analyzers/lib/netstandard1.3/_._
  src/dotnet-ef/dotnet-ef.csproj
  src/dotnet-ef/dotnet-ef.nuspec
  src/dotnet-ef/lib/netcoreapp2.1/_._
Labels: area-infrastructure, ask-mode

#18562 Rebrand for 3.1.0-preview3
  eng/Versions.props
Labels: area-infrastructure

#18674 Ignore line endings in test assertions
  test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Labels: area-test, type-cleanup

#18679 Apply element sorter in AssertIncludeQuery
  test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
Labels: area-test, type-bug

#18675 Fix some non-determinism in tests
  test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Labels: area-test, type-bug
