Repository dotnet/efcore, pull requests merged in 2019-01, with the labels that each got.

#14216 Update SQLitePCL.raw to version 1.1.12
  build/dependencies.props
Labels: servicing-consider

#14306 Merge interfaces for 3.0
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
  src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryDatabaseCreator.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
  src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
  src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
  src/EFCore.SqlServer.NTS/Infrastructure/Internal/SqlServerNetTopologySuiteOptionsExtension.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerOptionsExtension.cs
  src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteOptionsExtension.cs
  src/EFCore.Sqlite.NTS/Infrastructure/Internal/SqliteNetTopologySuiteOptionsExtension.cs
  src/EFCore/Infrastructure/CoreOptionsExtension.cs
  src/EFCore/Infrastructure/DatabaseFacade.cs
  src/EFCore/Infrastructure/IDbContextOptionsExtension.cs
  src/EFCore/Infrastructure/IDbContextOptionsExtensionWithDebugInfo.cs
  src/EFCore/Internal/ServiceProviderCache.cs
  src/EFCore/Storage/IDatabaseCreator.cs
  src/EFCore/Storage/IDatabaseCreatorWithCanConnect.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalDatabaseCreator.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalOptionsExtension.cs
  test/EFCore.Tests/DatabaseFacadeTest.cs
  test/EFCore.Tests/DbContextOptionsTest.cs
  test/EFCore.Tests/ServiceProviderCacheTest.cs
Labels: providers-beware

#14330 Fix SequenceHiLo to use the sequence from the correct database
  src/EFCore.SqlServer/ValueGeneration/Internal/ISqlServerValueGeneratorCache.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
  test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
  test/EFCore.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs
Labels: providers-fyi

#14343 Remove workaround for dotnet/arcade#1634
  eng/Signing.props
  eng/Versions.props
Labels: blocked

#14146 [2.2.x] Reset the property isNullable configuration source when removing a key.
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
Labels: servicing-approved

#14199 [2.2.x] Don't change FK requiredness when only some of the contained properties change nullability.
  src/EFCore/Metadata/Internal/Property.cs
Labels: servicing-approved

#14309 [2.2.x] Don't propagate implicit requiredness when recreating an FK
  src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
Labels: servicing-approved

#14206 [2.2.x] Don't throw on missing store generated values in data seeds.
  src/EFCore/Infrastructure/ModelValidator.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Labels: servicing-approved
