Repository dotnet/efcore, pull requests merged in 2019-04, with the labels that each got.

#15217 Rename FromRawSql to FromSqlRaw and related
  benchmark/Shared.EFCore/Query/RawSqlQueryTests.cs
  src/EFCore.Relational/RawSqlString.cs
  src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/RelationalQueryableExtensions.cs
  test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlSprocQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarFromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
  test/EFCore.Relational.Tests/Storage/RelationalDatabaseFacadeExtensionsTest.cs
  test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerQueryTriggersTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
Labels: providers-beware

#15248 Always use a MemberInfo for navigations if there is one matching the name
  src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
  src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
  src/EFCore.SqlServer/Metadata/SqlServerKeyAnnotations.cs
  src/EFCore/Extensions/ConventionPropertyExtensions.cs
  src/EFCore/Extensions/MutablePropertyExtensions.cs
  src/EFCore/Extensions/PropertyExtensions.cs
  src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
  src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
  src/EFCore/Metadata/Conventions/Internal/ServicePropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
  src/EFCore/Metadata/Internal/IndexedPropertySetterFactory.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Metadata/Internal/PropertyIdentity.cs
  src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryFixtureBase.cs
  test/EFCore.Tests/Metadata/Conventions/Internal/BackingFieldConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Labels: breaking-change

#15288 Create a public abstraction for managing seed data
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryContext.cs
  src/EFCore.InMemory/Storage/Internal/IInMemoryDatabase.cs
  src/EFCore.InMemory/Storage/Internal/IInMemoryStore.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryDatabaseCreator.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Storage/RelationalDatabase.cs
  src/EFCore.Relational/Update/ICommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparerDependencies.cs
  src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
  src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
  src/EFCore/ChangeTracking/Internal/IStateManager.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/EFCore.csproj
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  src/EFCore/Storage/DatabaseDependencies.cs
  src/EFCore/Update/IUpdateAdapter.cs
  src/EFCore/Update/IUpdateAdapterFactory.cs
  src/EFCore/Update/IUpdateEntry.cs
  src/EFCore/Update/Internal/UpdateAdapter.cs
  src/EFCore/Update/Internal/UpdateAdapterFactory.cs
  test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.InMemory.Tests/InMemoryDatabaseCreatorTest.cs
  test/EFCore.InMemory.Tests/InMemoryDatabaseTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
  test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Labels: providers-beware

#15394 Add security section to issue template.
  .github/ISSUE_TEMPLATE.md
Labels: area-infrastructure

#15434 Remove LazyRef
  src/EFCore.Design/Design/OperationExecutor.cs
  src/EFCore.Relational/Infrastructure/ModelSnapshot.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs
  src/EFCore.Relational/Migrations/Migration.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/DbUpdateException.cs
  src/EFCore/Infrastructure/Annotatable.cs
  src/EFCore/Internal/LazyRef.cs
  test/EFCore.Tests/Utilities/LazyRefTest.cs
Labels: providers-beware
