Repository dotnet/efcore, pull requests merged in 2019-11, with the labels that each got.

#18770 Exclude Object when checking for DbContext in query filters
  src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved

#18891 Update dependencies from extensions
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#18886 Fixes #12729 Flatten Case expression
  src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Labels: accepted

#18937 Fix to #18916 - Query: regression in EFCore 3.1 Preview 2 and Preview3 for query with conditional expression whose element is a comparison containing null-value parameter
  src/EFCore.Relational/Query/Internal/ParameterValueBasedSelectExpressionOptimizer.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved

#18971 Query: Read Avg/Min/Max as nullable from database to throw exception …
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Storage/FloatTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
Labels: Servicing-approved

#19004 Update SqlServerDbContextOptionsBuilder.cs
  src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
Labels: Servicing-approved

#18993 [release/3.0] Revert dotnet-ef package changes
  src/dotnet-ef/dotnet-ef.csproj
  src/dotnet-ef/dotnet-ef.nuspec
  src/dotnet-ef/lib/netcoreapp2.1/_._
Labels: Servicing-approved
