Repository dotnet/efcore, pull requests merged in 2019-08, with the labels that each got.

#16921 SqlServer Migrations: Consolidate IDENTITY annotations
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
  src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsAnnotationProviderTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Labels: breaking-change

#17211 Update SDK to preview 8
  global.json
Labels: area-infrastructure, tell-mode

#17198 Generate Sqlite create table comments
  EFCore.Sqlite.slnf
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
  src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
Labels: providers-beware

#17430 [release/3.0] Update NetTopologySuite packages
  eng/Versions.props
Labels: tell-mode

#17462 [release/3.0] Update Microsoft.Data.SqlClient
  eng/Versions.props
Labels: tell-mode

#17451 [release/3.0] RevEng: Fix bad logic around connection strings
  src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs
Labels: ask-mode, servicing-approved
