Repository dotnet/efcore, pull requests merged in 2019-12, with the labels that each got.

#19154 [3.1.1] Warn on redundant AddEntityFramework* calls
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
  src/EFCore/Internal/ServiceProviderCache.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
  test/EFCore.Tests/DbContextServicesTest.cs
Labels: Servicing-approved

#19259 [3.1.1] Query: Don't use VisitAndConvert in projectionBindingExpressionVisitor
  src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
Labels: Servicing-approved

#19269 #5783 - Casting with as causing exceptions
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Labels: accepted

#19324 DebugView for query and simple way to get SQL from an EF LINQ query
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.resx
  src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs
  src/EFCore.Relational/Storage/IRelationalCommand.cs
  src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
  src/EFCore.Relational/Storage/RelationalCommand.cs
  src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/IQueryingEnumerable.cs
  src/EFCore/Query/Internal/EntityQueryable`.cs
  src/EFCore/Query/Internal/QueryDebugView.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindWhereQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
Labels: providers-beware

#18630 Implement Translation for DATETIMEFROMPARTS (SqlServer)
  src/EFCore.Relational/Query/RelationalMethodCallTranslatorProviderDependencies.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeFromPartsFunctionTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
Labels: accepted

#19368 Can we run it? Yes we can!
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Query/IRelationalQueryStringFactory.cs
  src/EFCore.Relational/Query/IRelationalQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/IRelationalQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/RelationalQueryStringFactory.cs
  src/EFCore.Relational/Query/RelationalQueryContext.cs
  src/EFCore.Relational/Query/RelationalQueryContextDependencies.cs
  src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryStringFactory.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/Query/RelationalOwnedQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/SpatialQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalQueryAsserter.cs
  test/EFCore.Specification.Tests/FixtureBase.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerFixture.cs
  test/EFCore.Sqlite.FunctionalTests/Query/FunkyDataQuerySqliteTest.cs
Labels: providers-beware

#19376 Allow DbConnection or connection string to be changed on existing DbContext
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/IRelationalConnection.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
  test/EFCore.Relational.Specification.Tests/TwoDatabasesTestBase.cs
  test/EFCore.Relational.Tests/RelationalConnectionTest.cs
  test/EFCore.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
  test/EFCore.SqlServer.FunctionalTests/TwoDatabasesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/TwoDatabasesSqliteTest.cs
  test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
Labels: providers-beware
