Repository dotnet/efcore, pull requests merged in 2019-02, with the labels that each got.

#14470 Allow cascade delete timing to be configured
  src/EFCore/ChangeTracking/CascadeTiming.cs
  src/EFCore/ChangeTracking/ChangeTracker.cs
  src/EFCore/ChangeTracking/Internal/IStateManager.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/DbContext.cs
  src/EFCore/DeleteBehavior.cs
  src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
  test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/ProxyGraphUpdatesInMemoryTest.cs
  test/EFCore.Specification.Tests/DatabindingTestBase.cs
  test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/LoadTestBase.cs
  test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
  test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
  test/EFCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs
  test/EFCore.Tests/DbContextTrackingTest.cs
  test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Labels: providers-fyi

#14610 Remove ISingletonUpdateSqlGenerator and make IUpdateSqlGenerator singleton
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGeneratorDependencies.cs
  src/EFCore.Relational/Update/IUpdateSqlGenerator.cs
  src/EFCore.Relational/Update/Internal/ISingletonUpdateSqlGenerator.cs
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
Labels: providers-beware

#14693 Add component detection step to builds
  azure-pipelines.yml
Labels: area-infrastructure

#14513 Fix to #13285 - UseRelationalNulls does not work with SELECT conditions
  src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
  src/EFCore.Relational/Query/Expressions/SelectExpression.cs
  src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
Labels: servicing-approved

#14591 [2.2] Stop assuming dependent entity types have a key
  src/EFCore.Specification.Tests/LoadTestBase.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
Labels: regression, servicing-approved

#14715 Microsoft.Data.Sqlite: Persist CreateCollation, CreateAggregate, CreateFunction & EnableExtensions between close and re-open
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Labels: breaking-change
