Repository dotnet/efcore, pull requests merged in 2020-07, with the labels that each got.

#21487 Query: Self-bootstrapping functions returning IQueryable
  src/EFCore/DbContext.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.Tests/DbContextTest.cs
Labels: auto-merge

#21502 Query: Allow ToList on non queryables
  src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: auto-merge

#21474 Query: Implement TPT for relational layer
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryFixture.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTRelationshipsQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/TPTTableSplittingSqliteTest.cs
Labels: auto-merge

#21507 Query: Use function mapping when querying for DbSet
  src/EFCore.Relational/Metadata/Internal/StoreFunction.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Labels: auto-merge

#21537 Query: Add split query tests in TPT relationship tests
  test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationshipsQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTRelationshipsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/InheritanceRelationshipsQuerySqliteTest.cs
Labels: auto-merge

#21533 Query: Add TPT variant for FilterInheritanceQueryTests
  test/EFCore.Relational.Specification.Tests/Query/TPTFiltersInheritanceQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTFiltersInheritanceQuerySqliteFixture.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTFiltersInheritanceQuerySqliteTest.cs
Labels: auto-merge

#21550 Metadata: Add HasField(FieldInfo) on NavigationBuilder
  src/EFCore.Relational/Metadata/Internal/TableMapping.cs
  src/EFCore/Metadata/Builders/IConventionForeignKeyBuilder.cs
  src/EFCore/Metadata/Builders/IConventionNavigationBuilder.cs
  src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
  src/EFCore/Metadata/Internal/InternalPropertyBaseBuilder`.cs
  src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
  src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
  test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs
Labels: auto-merge

#21517 Query: Put client method to fetch join entity after filtered include …
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  test/EFCore.Relational.Specification.Tests/Query/ManyToManyNoTrackingQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/ManyToManyQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
Labels: auto-merge

#21553 My lovely SQL
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
Labels: auto-merge

#21542 Fix updates on the dependent in table sharing using TPT
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
Labels: auto-merge

#21559 Auto-merge Dependabot PRs
  .github/dependabot.yml
Labels: auto-merge

#21551 Clean up Migrations
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Migrations/Operations/AddCheckConstraintOperation.cs
  src/EFCore.Relational/Migrations/Operations/AddColumnOperation.cs
  src/EFCore.Relational/Migrations/Operations/AlterColumnOperation.cs
  src/EFCore.Relational/Migrations/Operations/AlterDatabaseOperation.cs
  src/EFCore.Relational/Migrations/Operations/AlterSequenceOperation.cs
  src/EFCore.Relational/Migrations/Operations/AlterTableOperation.cs
  src/EFCore.Relational/Migrations/Operations/Builders/CreateTableBuilder.cs
  src/EFCore.Relational/Migrations/Operations/ColumnOperation.cs
  src/EFCore.Relational/Migrations/Operations/CreateIndexOperation.cs
  src/EFCore.Relational/Migrations/Operations/CreateTableOperation.cs
  src/EFCore.Relational/Migrations/Operations/DatabaseOperation.cs
  src/EFCore.Relational/Migrations/Operations/SequenceOperation.cs
  src/EFCore.Relational/Migrations/Operations/TableOperation.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
Labels: providers-beware

#21556 Include key values in the update topological sort
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/IKeyValueIndexFactory.cs
  src/EFCore.Relational/Update/Internal/KeyValueIndex.cs
  src/EFCore/ChangeTracking/Internal/IdentityMap.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToManyAk.cs
Labels: auto-merge

#21589 Add regression tests for issue#10012
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Labels: auto-merge

#21272 [release/3.1] Tools: Fix up App.config path on .NET Framework
  src/ef/Commands/ProjectCommandBase.cs
  src/ef/ef.csproj
Labels: Servicing-approved

#21638 Fix non-deterministic test issue in ManyToManyQueryTestBase
  test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
Labels: auto-merge

#20377 [3.1] Updating Microsoft.Data.SqlClient to 1.1.3
  eng/Versions.props
Labels: Servicing-approved, blocked

#21622 Deprecate defining query at Core level
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
  src/EFCore.InMemory/Internal/InMemoryModelValidator.cs
  src/EFCore.InMemory/Metadata/Conventions/DefiningQueryRewritingConvention.cs
  src/EFCore.InMemory/Metadata/Conventions/InMemoryConventionSetBuilder.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/WithConstructorsInMemoryTest.cs
  test/EFCore.InMemory.Tests/Infrastructure/InMemoryModelValidatorTest.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Labels: auto-merge

#21639 Use FindEntityType(Type) as appropriate
  src/EFCore/DbContext.cs
  src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
  src/EFCore/Extensions/ModelExtensions.cs
  src/EFCore/Extensions/MutableModelExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Internal/EntityFinder.cs
  src/EFCore/Internal/InternalDbSet.cs
  src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
  src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
  src/EFCore/Metadata/IConventionModel.cs
  src/EFCore/Metadata/IModel.cs
  src/EFCore/Metadata/IMutableModel.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Tests/DbContextTest.cs
  test/EFCore.Tests/Metadata/Internal/ModelTest.cs
Labels: auto-merge

#21645 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: auto-merge

#21675 [preview8] Deprecate defining query at Core level
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
  src/EFCore.InMemory/Internal/InMemoryModelValidator.cs
  src/EFCore.InMemory/Metadata/Conventions/DefiningQueryRewritingConvention.cs
  src/EFCore.InMemory/Metadata/Conventions/InMemoryConventionSetBuilder.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/WithConstructorsInMemoryTest.cs
  test/EFCore.InMemory.Tests/Infrastructure/InMemoryModelValidatorTest.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Labels: auto-merge

#21697 Add a regression test for #21527
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
Labels: auto-merge

#21702 Clean up for #21680
  test/EFCore.InMemory.FunctionalTests/BuiltInDataTypesInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/ConvertToProviderTypesInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
Labels: auto-merge

#21701 Log an error for Required on principal to dependent
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Infrastructure/CoreOptionsExtension.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
  src/EFCore/Metadata/Conventions/RequiredNavigationAttributeConvention.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
Labels: auto-merge

#21704 Set max batch size for SQL Server
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
Labels: auto-merge

#21707 Don't ask how! :cry:
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Labels: auto-merge

#21708 Reduce allocations in EntityType by short-circuiting
  src/EFCore/Metadata/Internal/EntityType.cs
Labels: auto-merge

#21715 Metadata: Throw error for shared type in inheritance
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Labels: auto-merge

#21690 Query: Apply pending selector on single result query before trying to…
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: auto-merge

#21713 Add a warning for decimal keys for SqlServer
  src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
  src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
  src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
  src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  test/EFCore.Specification.Tests/ServiceProviderFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Labels: auto-merge

#21722 Query: Use correct column mappings for TVF/FromSql
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Labels: auto-merge

#21725 Query: Disallow FromSql/TVF with TPT
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: auto-merge

#21723 [SMALL] Fix to #21607 - Incorrect results returned when joining a key-less view to an entity
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
Labels: auto-merge

#21736 Correctly generate null literals in arrays
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
Labels: auto-merge

#21735 [SMALL] Adding regression test for #21434 - Making a sub-query inside a projection from a filtered Queryable results in all the results being added to a single object.
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
Labels: auto-merge

#21738 Remove IIndexNameChangedConvention
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/IIndexNameChangedConvention.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
Labels: auto-merge

#21742 Query: Key comparison should use object.Equals internally in query
  src/EFCore.Cosmos/Query/Internal/EqualsTranslator.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/EqualsTranslator.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/Internal/EntityFinder.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
Labels: auto-merge

#21743 Rename IsEagerLoaded to AutoInclude
  src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
  src/EFCore/Metadata/Builders/IConventionNavigationBuilder.cs
  src/EFCore/Metadata/Builders/IConventionSkipNavigationBuilder.cs
  src/EFCore/Metadata/Builders/NavigationBuilder.cs
  src/EFCore/Metadata/Conventions/NavigationEagerLoadingConvention.cs
  src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
  src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  src/EFCore/Query/QueryCompilationContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
Labels: auto-merge

#21741 Return void from AddShared and AddOwned
  src/EFCore/Extensions/ConventionModelExtensions.cs
  src/EFCore/Extensions/MutableModelExtensions.cs
  src/EFCore/Metadata/Internal/Model.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
Labels: auto-merge

#21746 Henceforth Associations are Joins
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
  src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
  src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/IConventionSkipNavigation.cs
  src/EFCore/Metadata/IMutableSkipNavigation.cs
  src/EFCore/Metadata/ISkipNavigation.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
  src/EFCore/Metadata/Internal/SkipNavigation.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
  test/EFCore.Tests/Metadata/Conventions/ManyToManyAssociationEntityTypeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/SkipNavigationTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
Labels: auto-merge

#21744 Metadata: Rename SharedEntity to SharedTypeEntity
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
  src/EFCore/Metadata/Builders/IConventionModelBuilder.cs
  src/EFCore/Metadata/Builders/IConventionSharedEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/ModelBuilder.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTestBase.cs
  test/EFCore.Sqlite.FunctionalTests/ManyToManyTrackingSqliteTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Labels: auto-merge

#21695 Remove incomplete nullable reference annotations for 5.0
  src/EFCore.Design/Scaffolding/IModelCodeGenerator.cs
  src/EFCore.Design/Scaffolding/IModelCodeGeneratorSelector.cs
  src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpNamer.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpUniqueNamer.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpUtilities.cs
  src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
  src/EFCore.Design/Scaffolding/Internal/ICSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/ICSharpEntityTypeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/ICSharpUtilities.cs
  src/EFCore.Design/Scaffolding/Internal/ICandidateNamingService.cs
  src/EFCore.Design/Scaffolding/Internal/IScaffoldingModelFactory.cs
  src/EFCore.Design/Scaffolding/Internal/IScaffoldingTypeMapper.cs
  src/EFCore.Design/Scaffolding/Internal/ModelCodeGeneratorSelector.cs
  src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
  src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
  src/EFCore.Design/Scaffolding/Internal/TypeScaffoldingInfo.cs
  src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseColumnExtensions.cs
  src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseForeignKeyExtensions.cs
  src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseTableExtensions.cs
  src/EFCore.Design/Scaffolding/ModelCodeGenerationOptions.cs
  src/EFCore.Design/Scaffolding/ModelCodeGenerator.cs
  src/EFCore.Design/Scaffolding/ModelCodeGeneratorDependencies.cs
  src/EFCore.Design/Scaffolding/ModelReverseEngineerOptions.cs
  src/EFCore.Design/Scaffolding/SavedModelFiles.cs
  src/EFCore.Design/Scaffolding/ScaffoldedFile.cs
  src/EFCore.Design/Scaffolding/ScaffoldedModel.cs
  src/EFCore.Relational/Scaffolding/DatabaseModelFactory.cs
  src/EFCore.Relational/Scaffolding/DatabaseModelFactoryOptions.cs
  src/EFCore.Relational/Scaffolding/IDatabaseModelFactory.cs
  src/EFCore.Relational/Scaffolding/IProviderCodeGeneratorPlugin.cs
  src/EFCore.Relational/Scaffolding/IProviderConfigurationCodeGenerator.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseColumn.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseForeignKey.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseIndex.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseModel.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabasePrimaryKey.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseSequence.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseTable.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseUniqueConstraint.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseView.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGenerator.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorDependencies.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorPlugin.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteCodeGenerator.cs
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
Labels: auto-merge

#21761 Remove Spatialite testing from Mac OS agents
  azure-pipelines.yml
Labels: auto-merge

#21706 Validate shared views
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/TypeMaterializationInfo.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
  src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerKeyExtensions.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: auto-merge

#21764 Only create additional concurrency token properties when needed
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
Labels: auto-merge

#21747 Query: Rewrite entity equality for dependents sharing table
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#21775 Query: Make ParameterBasedSqlProcessor thread safe
  src/EFCore.Relational/Query/RelationalParameterBasedSqlProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#21776 Don't write to computed column when table splitting
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/PropertyExtensions.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Specification.Tests/TestModels/TransportationModel/Engine.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/TableSplittingSqliteTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
Labels: auto-merge

#21778 Query: Disallow FromSql on owner when owned navigation is mapped to s…
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
Labels: auto-merge

#21784 Query: Change TPT to use string discriminator column
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
Labels: auto-merge

#21780 Query: Allow entity equality to work on client converted entity
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#21783 [release/5.0-preview8] SQLite Migrations: Test table rebuilds
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: auto-merge

#21795 Fix Sqlite CommandType in XML docs
  src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Labels: auto-merge

#21787 Query: Change alias of the column for TPT Discriminator
  src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
Labels: auto-merge

#21811 Use default property names for join entity type
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
  src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Tests/Metadata/Conventions/ManyToManyAssociationEntityTypeConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: auto-merge

#21813 Make property bag entity types use an indexer prop rather than a shadow prop
  src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
  src/EFCore.Relational/Storage/Internal/TypeMappedRelationalParameter.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
  src/EFCore/Metadata/ITypeBase.cs
  src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/Shared/SharedTypeExtensions.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: auto-merge

#21821 Cosmos: Avoid reading default values from database
  src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSetOperationsQueryCosmosTest.cs
Labels: auto-merge

#21824 Discover self-referencing many-to-many relationships
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs
Labels: auto-merge

#21829 Fully support base type mapping names with precision/scale/size specified separately
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Storage/RelationalTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
  src/EFCore/Metadata/Builders/PropertyBuilder.cs
  src/EFCore/Metadata/Builders/PropertyBuilder`.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
  test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
Labels: auto-merge, providers-beware

#21831 Query: Support ToQuerySql
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindChangeTrackingQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindInMemoryContext.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindKeylessEntitiesQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindQueryInMemoryFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
Labels: auto-merge

#21834 Use the correct shared foreign key for navigation fixup
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Category.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Product.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductBase.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductCategory.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductWithBytes.cs
  test/EFCore.Specification.Tests/UpdatesFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
Labels: auto-merge

#21842 Migrations: Don't warn for existing calls to CreateCheckConstraint
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
Labels: auto-merge

#21833 Query: Fix bug in FromSqlExpression.Equals
  src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#21847 Add a nested lambda to ToTable
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder`.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
Labels: auto-merge

#21849 Adding regression test for #18510 - InvalidOperationException : When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type.
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#21848 Rename defining query APIs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
  src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
  src/EFCore.InMemory/Internal/InMemoryModelValidator.cs
  src/EFCore.InMemory/Metadata/Conventions/DefiningQueryRewritingConvention.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
  src/EFCore.Relational/Metadata/SqlQueryExtensions.cs
  src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
  test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryFixture.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindInMemoryContext.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/WithConstructorsInMemoryTest.cs
  test/EFCore.InMemory.Tests/Infrastructure/InMemoryModelValidatorTest.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
  test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
Labels: auto-merge

#21850 Add IConventionEntityTypeBuilder.HasSkipNavigation that takes an inverse
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/SkipNavigation.cs
Labels: auto-merge

#21860 Metadata: Fix few Shared Type entity type bugs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ImplicitManyToManyA.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ImplicitManyToManyB.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/SharedTypes.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#21866 Make CommandLogger available on MigrationCommand
  src/EFCore.Relational/Migrations/MigrationCommand.cs
  src/EFCore.Relational/Storage/RelationalCommandParameterObject.cs
  test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs
Labels: auto-merge

#21872 Skip flaky tests
  test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
Labels: auto-merge

#21868 ModelValidator: Throw for unmapped initialized collection navigation
  src/EFCore/Infrastructure/ModelValidator.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#21878 Use async dispose for DataReader
  src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
Labels: auto-merge

#21880 Run two SaveChanges interception suites against different databases
  test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
Labels: auto-merge

#21883 Fix typo
  src/EFCore.Relational/Metadata/Builders/SequenceBuilder.cs
Labels: auto-merge
