Repository dotnet/efcore, pull requests merged in 2020-11, with the labels that each got.

#23159 Add more tests for exceptions
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/DbFunction.cs
  src/EFCore.Relational/Metadata/Internal/DbFunctionParameter.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/RelationalOptionsExtensionTest.cs
  test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalForeignKeyBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/ModelTest.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Labels: auto-merge

#23194 Re-enable xUnit analyzers
  test/Directory.Build.targets
  test/EFCore.Proxies.Tests/ChangeDetectionProxyTests.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#23192 SqlServer: Generate False predicate when skip/take both are 0
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: auto-merge

#23204 Cosmos: Instance can be null for member translation
  src/EFCore.Cosmos/Query/Internal/CosmosMemberTranslatorProvider.cs
  src/EFCore.Cosmos/Query/Internal/IMemberTranslator.cs
  src/EFCore.Cosmos/Query/Internal/IMemberTranslatorProvider.cs
Labels: auto-merge

#23213 Cosmos: Add support for char literals
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
  test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
Labels: auto-merge

#23214 Re-enable previously failing test
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#23215 SqlServer: date constant in DateAdd method is always datetime
  src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#23216 Re-enable in-memory test for optional navigation access
  test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: auto-merge

#23225 Remove test for unsupported scenario
  test/EFCore.Tests/QueryProviderTest.cs
Labels: auto-merge

#23218 Query: Add support for set operations between 2 collection navs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: auto-merge

#23217 is operator working for InMemory
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
Labels: auto-merge

#23246 [release/5.0] Move to 5.0.1 versions
  NuGet.config
  eng/Versions.props
  global.json
Labels: area-infrastructure, area-platform, blocked, tell-mode

#23052 3.1.11: Add missing Ordinal to parameter StartsWith comparison
  src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
Labels: Servicing-approved, blocked

#23160 Sqlite: Translate char.ToLower and ToUpper
  src/EFCore.Sqlite.Core/Query/Internal/SqliteCharMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
  test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
Labels: auto-merge

#23182 Sqlite: Add glob, hex & substr functions
  src/EFCore.Sqlite.Core/Extensions/SqliteDbFunctionsExtensions.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteGlobMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteHexMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSubstrMethodTranslator.cs
  test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
Labels: auto-merge

#23060 3.1.11: Disable NRTs in scaffolding
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#23288 [5.0.1] Clear events when DbContext is disposed or returned to the pool
  All.sln.DotSettings
  src/EFCore/DbContext.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: Servicing-approved

#23143 [5.0.1] Query: Generate predicate correctly when expanding owned collections
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Labels: Servicing-approved, auto-merge

#23273 [5.0.1] Query: Correctly compute ordering to be copied from outer in collection join
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved, auto-merge

#23277 [5.0.1] RevEng: Call correct overload of HasIndex when scaffolding constraints without name
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: Servicing-approved

#23292 [5.0.1] InMemory: Copy correct value buffer data when doing LeftJoin
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Labels: Servicing-approved

#23295 [5.0.1] Query: Properly generate expression to read from BufferedDataReader
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved

#23297 [5.0.1] Query: Pushdown into subquery when applying group by over a group by
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Labels: Servicing-approved

#23299 [5.0.1] Query: Don't clear projection mapping when adding single projection
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Labels: Servicing-approved

#23323 [5.0.1] Query: Match types in conditional during client evaluation
  src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Labels: Servicing-approved

#23361 Change some metadata extension methods into DIM properties and annotate for nullability
  src/EFCore/ChangeTracking/Internal/InternalEntityEntryFactory.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
  src/EFCore/Metadata/Conventions/NotMappedMemberAttributeConvention.cs
  src/EFCore/Metadata/Conventions/OwnedEntityTypeAttributeConvention.cs
  src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
  src/EFCore/Metadata/IEntityType.cs
  src/EFCore/Metadata/ITypeBase.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Metadata/Internal/Property.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
  src/EFCore/Query/Internal/EntityMaterializerSource.cs
Labels: auto-merge

#23384 Enabled tests marked with sqlite bug
  test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyQuerySqliteTest.cs
Labels: auto-merge

#23382 Remove QueryFailed
  src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
Labels: auto-merge

#23383 Merge sync/async query tests into one
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindAsyncSimpleQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindAsyncSimpleQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindAsyncSimpleQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AsyncFromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAsyncSimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/AsyncFromSqlQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindAsyncSimpleQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#23290 [5.0.1] Microsoft.Data.Sqlite: Don't force decryption when password unset
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Labels: Servicing-approved, auto-merge

#23298 [5.0.1] Sqlite Migrations: Handle Z and M in spatial columns
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#23227 Query: Assign nullability to entity shaper correctly for set operations
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Query/EntityShaperExpression.cs
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#23392 Fix build break
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
Labels: auto-merge

#23412 Cosmos: Apply projection in post processor
  src/EFCore.Cosmos/Query/Internal/CosmosQueryTranslationPostprocessor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
  test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs
Labels: auto-merge

#23409 Annotate IsNiladic for nullability on Arguments
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
Labels: auto-merge

#23350 [5.0.1] Query: Add null check in hash computation in SqlFunctionExpression
  src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
Labels: Servicing-approved

#23421 [5.0.1] RevEng: Ignore column store index
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: Servicing-approved

#23420 [5.0.1] Query: Don't terminate translation if indexer method does not bind to indexer property
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved

#23463 Remove delta flaky test/Fix build break
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
Labels: auto-merge

#23466 [SMALL] Fix to #23349 - Test: Implement entity sorters/asserts for Spatial test base
  test/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Labels: auto-merge

#23452 [5.0.1] Migrations: Skip DbFunctionAttributeConvention when creating model for history repository
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
Labels: Servicing-approved

#23484 RevEng: Warn for FK with same required facets exists and skip it
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: auto-merge
