Repository dotnet/efcore, pull requests merged in 2020-02, with the labels that each got.

#19773 Fix to #18211 - Throw better exception for Last without order by
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindAggregateOperatorsQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
Labels: accepted

#19745 Fixes #19720 single parenthesis defaults
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
Labels: accepted

#19872 Rename IModelFinalizedConvention to IModelFinalizingConvention
  src/EFCore.Cosmos/Metadata/Conventions/ETagPropertyConvention.cs
  src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
  src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
  src/EFCore.Relational/Metadata/Conventions/DbFunctionTypeMappingConvention.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerEnumConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
  src/EFCore/Metadata/Conventions/ChangeTrackingStrategyConvention.cs
  src/EFCore/Metadata/Conventions/ConstructorBindingConvention.cs
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/ForeignKeyIndexConvention.cs
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/IModelFinalizedConvention.cs
  src/EFCore/Metadata/Conventions/IModelFinalizingConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
  src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
  src/EFCore/Metadata/Conventions/QueryFilterDefiningQueryRewritingConvention.cs
  src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/TypeMappingConvention.cs
  src/EFCore/Metadata/Conventions/ValidatingConvention.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  src/EFCore/Metadata/Internal/Model.cs
  test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
  test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/BackingFieldConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/ConstructorBindingConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
  test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/ModelCleanupConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
Labels: providers-beware

#19867 [Release/3.1] ReplacingEV uses two arrays instead of dictionary (#19858)
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/ChangeTracking/ValueComparer.cs
  src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
  src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Query/ReplacingExpressionVisitor.cs
Labels: Servicing-approved

#19901 [release/3.1] Cosmos: Visit sibling includes when encountering an owned collections
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
Labels: Servicing-approved

#19911 [release/3.1] Cherry-picking commits for for closely related detach/delete issues
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
  test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Labels: Servicing-approved

#19701 [release/3.1] SQLite Spatial: Find SpatiaLite in framework-dependent deployments
  src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
Labels: Servicing-approved

#19919 [release/3.1] RevEng: Don't create navigations to keyless entity types
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Design.Tests/TestUtilities/DatabaseColumnRef.cs
  test/EFCore.Design.Tests/TestUtilities/DatabaseTableRef.cs
  test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs
Labels: Servicing-approved

#19774 SqlServer: Translate TimeSpan members
  src/EFCore.SqlServer/Query/Internal/SqlServerMemberTranslatorProvider.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerTimeSpanMemberTranslator.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
  test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Mission.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: accepted

#20007 [release/3.1] Fix dotnet-ef RuntimeFrameworkVersion
  Directory.Build.targets
  eng/Versions.props
Labels: Servicing-approved

#20066 Store all sequences in a single annotation
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
  src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalModelExtensions.cs
  src/EFCore.Relational/Metadata/Internal/Sequence.cs
  src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
  src/EFCore/Metadata/Internal/Property.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/SequenceTest.cs
  test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerValueGenerationStrategyConventionTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
Labels: providers-beware

#18438 Improve SqliteDataRecord class Efficiency
  src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
  src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Labels: accepted
