Repository dotnet/efcore, pull requests merged in 2020-08, with the labels that each got.

#21889 Make StoreObjectIdentifier a readonly struct
  src/EFCore.Relational/Diagnostics/IndexWithPropertiesEventData.cs
  src/EFCore.Relational/Diagnostics/IndexWithPropertyEventData.cs
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
  src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalPropertyOverrides.cs
  src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerKeyExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqlitePropertyExtensions.cs
  src/EFCore.Sqlite.Core/Internal/SqliteModelValidator.cs
Labels: auto-merge

#21884 Rename MigrationOperation.For methods to CreateFrom
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Migrations/Operations/AddCheckConstraintOperation.cs
  src/EFCore.Relational/Migrations/Operations/AddForeignKeyOperation.cs
  src/EFCore.Relational/Migrations/Operations/AddPrimaryKeyOperation.cs
  src/EFCore.Relational/Migrations/Operations/AddUniqueConstraintOperation.cs
  src/EFCore.Relational/Migrations/Operations/CreateIndexOperation.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
Labels: auto-merge

#21897 RevEng: Scaffold MaxLength attribute when using data annotations
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: auto-merge

#21895 Fix some non-deterministic tests
  test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
Labels: auto-merge

#21898 Query: Allow FromSql on owner by generating join
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Labels: auto-merge

#21922 Fix FreeText tests
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
Labels: auto-merge

#21907 Query: Translate GroupBy-Aggregate with condition
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
Labels: auto-merge, providers-beware

#21923 Query: Identify Count(*) in different SelectExpression differently
  src/EFCore.Relational/Query/SqlExpressions/SqlFragmentExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Labels: auto-merge

#21924 Query: Add logging
  src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggerExtensions.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/QueryCompilationContext.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
  test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindQueryRelationalFixture.cs
  test/EFCore.Specification.Tests/ConferencePlannerTestBase.cs
  test/EFCore.Specification.Tests/FieldMappingTestBase.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/MusicStoreTestBase.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
  test/EFCore.Specification.Tests/SpatialTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.Tests/Infrastructure/EventIdTestBase.cs
Labels: auto-merge

#21929 Remove unneeded savepoint API sugar
  src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore/Infrastructure/DatabaseFacade.cs
  src/EFCore/Storage/IDbContextTransactionManager.cs
  test/EFCore.Tests/DatabaseFacadeTest.cs
Labels: auto-merge

#21938 Query: Fix bug in CaseExpression.VisitChildren
  src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: auto-merge

#21939 Remove all ambiguous InverseAttribute skip navigations
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#21936 Remove TypeMapping annotation
  src/EFCore.Relational/Metadata/Internal/ColumnMappingBaseComparer.cs
  src/EFCore.Relational/Metadata/Internal/ColumnNameComparer.cs
  src/EFCore.Relational/Metadata/Internal/Table.cs
  src/EFCore.Relational/Metadata/Internal/TableBase.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore/Extensions/ConventionPropertyExtensions.cs
  src/EFCore/Extensions/MutablePropertyExtensions.cs
  src/EFCore/Extensions/PropertyExtensions.cs
  src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
  src/EFCore/Metadata/Conventions/TypeMappingConvention.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
  src/EFCore/Metadata/Internal/Property.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
  test/EFCore.Specification.Tests/TestUtilities/AnnotationComparer.cs
  test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
Labels: auto-merge

#21933 SqlServer Migrations: Add EXEC calls to idempotent script
  src/EFCore.Design/Design/Internal/MigrationsOperations.cs
  src/EFCore.Design/Design/OperationExecutor.cs
  src/EFCore.Relational/Migrations/IMigrationsSqlGenerator.cs
  src/EFCore.Relational/Migrations/IMigrator.cs
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerationOptions.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/MigrationsInfrastructureTestBase.cs
  test/EFCore.Relational.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.Relational.Tests/RelationalEventIdTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: breaking-change, providers-beware

#21944 Add regression tests
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/QueryTestExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
Labels: auto-merge

#21946 RevEng: Generate lambda with good identifiers
  src/EFCore.Design/Design/ICSharpHelper.cs
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
Labels: auto-merge

#21941 Metadata: Add overloads for configuring shared type as owned type
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Metadata/Internal/TypeIdentity.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#21948 Add end to end test for shared type entity type
  src/EFCore/Internal/InternalDbSet.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Tests/DbSetTest.cs
Labels: auto-merge

#21958 API Review fallout
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder`.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: auto-merge

#21959 Configure OnDelete for join entity types on SQL Server
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/IForeignKeyAddedConvention.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ManyToManyJoinEntityTypeConvention.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/ManyToManyJoinEntityTypeConventionTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: auto-merge

#21966 Add ITableBase.IsOptional
  src/EFCore.Relational/Metadata/ITableBase.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Metadata/Internal/TableBase.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Labels: auto-merge

#21212 Microsoft.Data.Sqlite: Add deferred transactions
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
  src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Labels: auto-merge

#22011 Metadata: Add CLR type for shared type entity type in debug view
  src/EFCore/Extensions/EntityTypeExtensions.cs
Labels: auto-merge

#21992 Query: Prune SelectExpression to remove not needed TPT LeftJoin tables
  src/EFCore.Relational/Query/Internal/SelectExpressionPruningExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationshipsQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
Labels: auto-merge

#21989 MemberEntry support for skip navigations
  src/EFCore/ChangeTracking/CollectionEntry.cs
  src/EFCore/ChangeTracking/EntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/NavigationEntry.cs
  src/EFCore/ChangeTracking/ReferenceEntry.cs
  src/EFCore/Internal/EntityFinder.cs
  src/EFCore/Internal/IEntityFinder.cs
  src/EFCore/Internal/IEntityFinder`.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Update/UpdateEntryExtensions.cs
  src/Shared/SharedTypeExtensions.cs
  test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs
  test/EFCore.Tests/ChangeTracking/SkipMemberEntryTest.cs
  test/EFCore.Tests/ChangeTracking/SkipNavigationEntryTest.cs
Labels: breaking-change

#22026 Determine column names for TPT in the model instead of a convention.
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/EntityTypeHierarchyMappingConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
  src/EFCore/Diagnostics/CoreEventId.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Labels: auto-merge

#22032 Type mapping fixes from API reviews
  src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
  src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
  src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqliteTest.cs
  test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
Labels: providers-beware

#22037 API review changes
  src/EFCore.Abstractions/DbFunctionAttribute.cs
  src/EFCore.Abstractions/IndexAttribute.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalDbFunctionAttributeConvention.cs
  src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
  src/Shared/Check.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
Labels: auto-merge

#22039 Target FKs to the derived table in TPT if possible
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: auto-merge

#22024 Query: Disallow return types of queryables in projection
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Infrastructure/TypeExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAsyncSimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
Labels: auto-merge

#22033 Query: Simplify member access on conditional null check constructing …
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
  src/EFCore/Query/QueryTranslationPreprocessor.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Labels: auto-merge

#22050 Fix an OwnsOne overload not passing through the type.
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/TypeIdentity.cs
  src/EFCore/Metadata/MemberIdentity.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: auto-merge

#22038 API Review Changes
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
  src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteSqlGenerationHelper.cs
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/ConventionPropertyExtensions.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Query/QueryCompilationContextDependencies.cs
  test/EFCore.Tests/ApiConsistencyTestBase.cs
Labels: auto-merge, providers-beware

#22048 Undo binary breaking change to INavigation
  src/EFCore/Metadata/IConventionNavigation.cs
  src/EFCore/Metadata/IConventionNavigationBase.cs
  src/EFCore/Metadata/IConventionSkipNavigation.cs
  src/EFCore/Metadata/IMutableNavigation.cs
  src/EFCore/Metadata/IMutableNavigationBase.cs
  src/EFCore/Metadata/IMutableSkipNavigation.cs
  src/EFCore/Metadata/INavigation.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
Labels: auto-merge

#22052 Throw if same name is specified for a different shared type owned entity type
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: auto-merge

#22059 Propagate original values for shared columns to added dependents in table splitting
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore/ChangeTracking/Internal/OriginalValues.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryFixtureBase.cs
Labels: auto-merge

#22066 Don't uniquify non-existing FKs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
Labels: auto-merge

#22069 Stop qualifying Type parameters with CLR
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  src/EFCore.Cosmos/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Proxies/Proxies/Internal/IProxyFactory.cs
  src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
  src/EFCore.Relational/Extensions/RelationalModelBuilderExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
  src/EFCore.Relational/Metadata/IConventionSequence.cs
  src/EFCore.Relational/Metadata/IMutableSequence.cs
  src/EFCore.Relational/Metadata/ISequence.cs
  src/EFCore.Relational/Metadata/Internal/InternalSequenceBuilder.cs
  src/EFCore.Relational/Metadata/Internal/Sequence.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
  src/EFCore.Sqlite.NTS/Storage/Internal/SqliteNetTopologySuiteTypeMappingSourcePlugin.cs
  src/EFCore/Extensions/ConventionModelExtensions.cs
  src/EFCore/Extensions/ModelExtensions.cs
  src/EFCore/Extensions/MutableModelExtensions.cs
  src/EFCore/Infrastructure/DbSetProperty.cs
  src/EFCore/Internal/DbSetInitializer.cs
  src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
  src/EFCore/Metadata/Conventions/DbSetFindingConvention.cs
  src/EFCore/Metadata/IConventionModel.cs
  src/EFCore/Metadata/IMutableModel.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/EFCore/ModelBuilder.cs
  test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/SequenceTest.cs
  test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
  test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
  test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
  test/EFCore.Tests/EntitySetFinderTest.cs
Labels: auto-merge

#22070 Make ITableBase methods throw for entity types not mapped to the table
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Metadata/Internal/TableBase.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Labels: auto-merge

#22075 Properly remove incompatible entity types with the same name.
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
Labels: auto-merge

#22072 Use CreateFactory instead of CreateInstance in DbContextFactory
  src/EFCore/Internal/DbContextFactorySource.cs
Labels: auto-merge

#22082 [release/3.1] Correct SHAs for a few dependencies
  eng/Version.Details.xml
Labels: area-infrastructure, tell-mode

#22079 Use local DetectChanges when cascade-deleting
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  test/EFCore.Tests/DbContextTrackingTest.cs
Labels: auto-merge

#22097 React to code review comments after the bot got too eager
  test/EFCore.Tests/DbContextTrackingTest.cs
Labels: auto-merge

#22098 InMemory: No-op for AsSplitQuery operator
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
Labels: auto-merge

#22104 Update branding to 6.0.0 Alpha1
  Directory.Build.props
  eng/Versions.props
  eng/helix.proj
  src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/SerializationTestBase.cs
Labels: area-infrastructure

#22099 Don't create an FK constraint if a derived type in TPT uses table sharing
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: auto-merge

#22107 InMemory: No-op for AsSplitQuery operator (#22098)
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
Labels: auto-merge

#22108 Move exception messages
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.Cosmos/Query/Internal/SqlBinaryExpression.cs
  src/EFCore.Cosmos/Query/Internal/SqlExpression.cs
  src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
  src/EFCore.Cosmos/Query/Internal/SqlUnaryExpression.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.resx
  src/EFCore.InMemory/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlBinaryExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlUnaryExpression.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindAggregateOperatorsQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindIncludeNoTrackingQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindIncludeQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindStringIncludeQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindAggregateOperatorsQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindIncludeQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindStringIncludeQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindStringIncludeQuerySqliteTest.cs
Labels: auto-merge

#22100 ChangeTracking: Make Query work on collection entry when defining nav…
  src/EFCore/Internal/EntityFinder.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
Labels: auto-merge

#22110 Avoid initializing the model during DatabaseFacade.IsRelational()
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
  test/EFCore.SqlServer.Tests/SqlServerDatabaseFacadeTest.cs
Labels: auto-merge

#22111 Test for issue #22092
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
Labels: auto-merge

#22091 ToQueryString for ReadItemQueryingEnumerable
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalQueryAsserter.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
Labels: auto-merge

#22120 [release/3.1] Add dependencies for CPD strict in aspnetcore
  eng/Version.Details.xml
Labels: area-infrastructure, auto-merge, tell-mode

#22127 Fix Cosmos build break.
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
Labels: auto-merge

#22129 Fix flakey SQLite test
  test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Labels: auto-merge

#22124 PMC Tools: Work around dotnet/project-system#5895
  src/EFCore.Tools/tools/EntityFrameworkCore.psm1
Labels: auto-merge

#22134 PMC Tools: Work around PowerShell/PowerShell#3424
  src/EFCore.Tools/tools/EntityFrameworkCore.psm1
Labels: auto-merge

#22136 Add FK constraints between TPT tables
  src/EFCore.Relational/Metadata/Conventions/EntityTypeHierarchyMappingConvention.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Extensions/ForeignKeyExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ValueGenerationConvention.cs
  src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Conventions/ValueGeneratorConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs
Labels: auto-merge

#22145 RevEng: Use pluralizer with database names too
  src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Design.Tests/TestUtilities/DatabaseColumnRef.cs
  test/EFCore.Design.Tests/TestUtilities/DatabaseTableRef.cs
  test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs
Labels: auto-merge

#22148 SqlServer RevEng: Handle included index columns
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: auto-merge

#22155 Add tests for split query and weak entities
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsWeakQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
Labels: auto-merge

#22178 Be consistent about which NotNull attribute to use
  src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
  src/EFCore.Relational/Metadata/ITableBase.cs
  src/EFCore.Relational/Metadata/Internal/ColumnNameComparer.cs
  src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs
  src/EFCore.Sqlite.Core/Diagnostics/Internal/UnexpectedConnectionTypeEventData.cs
  src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
  src/EFCore/Metadata/Internal/PropertyNameComparer.cs
  src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
  src/EFCore/Query/Internal/SubqueryMemberPushdownExpressionVisitor.cs
  src/Shared/Check.cs
  test/EFCore.Tests/ApiConsistencyTestBase.cs
Labels: auto-merge

#22153 Re-run fk discovery convention when skip navigation changes
  src/EFCore/Extensions/PropertyExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/IConventionProperty.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
  test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: auto-merge

#22175 Add a warning for unmapped foreign keys
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/RelationalEventIdTest.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/ModelBuilderSqlServerTest.Other.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilder.Other.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#22197 Downgrade to Microsoft.Azure.Cosmos 3.12.0
  .github/dependabot.yml
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
  src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
  src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategy.cs
  src/EFCore.Cosmos/Storage/Internal/HttpException.cs
  src/EFCore.Cosmos/Storage/Internal/JsonCosmosSerializer.cs
  src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
  test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
  test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
Labels: auto-merge

#22202 Don't move my cheese!
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Labels: auto-merge

#22168 Handle NaN in value comparers for double/float
  src/EFCore.Relational/Storage/DoubleTypeMapping.cs
  src/EFCore.Relational/Storage/FloatTypeMapping.cs
  src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
  src/EFCore/ChangeTracking/DoubleValueComparer.cs
  src/EFCore/ChangeTracking/FloatValueComparer.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
Labels: providers-beware

#22207 SqlServer Migrations: Don't generate unnecessary ALTER TABLE
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
Labels: auto-merge

#22216 Query: Enable test for complex case of null removal
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Labels: auto-merge

#22220 Don't use nulls for shadow properties in non-anonymous seed data
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: Servicing-approved, auto-merge

#22218 Stop using DbSet property name for table name of shared type entity types
  src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
  test/EFCore.Relational.Tests/DbSetAsTableNameTest.cs
  test/EFCore.SqlServer.Tests/DbSetAsTableNameSqlServerTest.cs
  test/EFCore.Sqlite.Tests/DbSetAsTableNameSqliteTest.cs
Labels: Servicing-approved

#22221 Allow FK properties to remain temporary when state changes from Added
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
Labels: Servicing-approved

#22244 [release/5.0] Update to Microsoft.Data.SqlClient 2.0.1
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: auto-merge, type-dependency update :arrow_up_small:

#22227 Upgrade build SDK to 5.0 preview8
  docs/getting-and-building-the-code.md
  eng/helix.proj
  global.json
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  test/Directory.Build.targets
  test/EFCore.Design.Tests/DesignExceptionTest.cs
  test/EFCore.Tests/ExceptionTest.cs
Labels: Servicing-approved

#22229 Make sure IMutableAnnotatable methods correctly update the ConfigurationSource
  src/EFCore/Infrastructure/ConventionAnnotatable.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductTableView.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductTableWithView.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductViewTable.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
Labels: Servicing-approved

#22225 Add ValueGenerated.OnUpdateSometimes for shared columns
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Storage/RelationalDatabase.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Metadata/Builders/PropertyBuilder.cs
  src/EFCore/Metadata/Builders/PropertyBuilder`.cs
  src/EFCore/Metadata/Internal/PropertyExtensions.cs
  src/EFCore/Metadata/ValueGenerated.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
Labels: Servicing-approved

#22233 Throw detailed exception message in buffered data reader
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
  src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Relational/Storage/ReaderColumn.cs
  src/EFCore.Relational/Storage/ReaderColumn`.cs
  src/EFCore.Relational/Storage/RelationalCommand.cs
  src/EFCore.Relational/Storage/RelationalCommandParameterObject.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Relational.Tests/Query/Internal/BufferedDataReaderTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved, auto-merge

#22245 Sqlite: Make AUTOINCREMENT accurate
  src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
  test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationAnnotationProviderTest.cs
Labels: Servicing-approved, auto-merge

#22246 Query: Enable regression test for InMemory and byte array equality
  test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
Labels: Servicing-approved, auto-merge

#22249 Query: Pushdown into subquery when applying over Skip after Distinct …
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Labels: Servicing-approved

#22254 Assumptions are correct till they are not
  src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
Labels: Servicing-approved, auto-merge

#22257 Fix issue#12518
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved, auto-merge

#22242 Cleanup NaN handling in value comparers
  src/EFCore.Relational/Storage/DoubleTypeMapping.cs
  src/EFCore.Relational/Storage/FloatTypeMapping.cs
  src/EFCore/ChangeTracking/DoubleValueComparer.cs
  src/EFCore/ChangeTracking/FloatValueComparer.cs
  src/EFCore/ChangeTracking/ValueComparer.cs
  src/EFCore/ChangeTracking/ValueComparer`.cs
Labels: Servicing-approved

#22264 Improve exception message for missing shared table linking FK
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
Labels: Servicing-approved

#22261 Caching is important :snail:
  src/EFCore/ChangeTracking/Internal/StateManager.cs
Labels: Servicing-approved

#22259 Query: Handle multiple lets with weak entities
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Query/ReplacingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
Labels: Servicing-approved, auto-merge

#22251 Query: Add optimization to conditional being equated to equality
  src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved, auto-merge

#22226 SqlServer Migrations: Persist ValueGenerationStrategy.None in snapshot
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved, auto-merge

#22275 Perf: Cache candidate properties for propagation and generation
  src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
  src/EFCore/ChangeTracking/Internal/IValueGenerationManager.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
Labels: Servicing-approved

#22282 Add regression tests
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
Labels: Servicing-approved, auto-merge

#22281 Perf: Cache SkipDetectChanges on model as a field
  src/EFCore/ChangeTracking/ChangeTracker.cs
  src/EFCore/ChangeTracking/CollectionEntry.cs
  src/EFCore/ChangeTracking/EntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/ChangeTracking/ReferenceEntry.cs
  src/EFCore/Metadata/Conventions/ChangeTrackingStrategyConvention.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Update/Internal/UpdateAdapter.cs
Labels: Servicing-approved

#22258 Support overriding virtual indexer property in proxies
  src/EFCore.Proxies/Proxies/Internal/PropertyChangeInterceptorBase.cs
  src/EFCore.Proxies/Proxies/Internal/PropertyChangedInterceptor.cs
  src/EFCore.Proxies/Proxies/Internal/PropertyChangingInterceptor.cs
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  src/EFCore/Extensions/Internal/ExpressionExtensions.cs
  src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
  src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ProxyableSharedType.cs
Labels: Servicing-approved

#22278 Limit change tracking proxies to only changing _and_ changed strategies
  src/EFCore.Proxies/Proxies/Internal/ProxyChangeTrackingConvention.cs
  src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Proxies.Tests/ChangeDetectionProxyTests.cs
Labels: Servicing-approved

#22305 Re-enable exception serialization tests
  test/EFCore.Design.Tests/DesignExceptionTest.cs
  test/EFCore.Tests/ExceptionTest.cs
Labels: Servicing-approved, auto-merge

#22285 Minor model building perf improvements
  src/EFCore/Extensions/ConventionModelExtensions.cs
  src/EFCore/Extensions/ModelExtensions.cs
  src/EFCore/Extensions/MutableModelExtensions.cs
  src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/InheritanceDiscoveryConventionBase.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/Model.cs
Labels: Servicing-approved

#22298 Update exception message for LogMultipleCollectionIncludeWarning
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
Labels: Servicing-approved

#22299 Add regression test for issue#13860
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Labels: Servicing-approved, auto-merge

#22284 Re-enable tests for issue#16057
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved, auto-merge

#22300 Add regression test for issue#14471
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: Servicing-approved, auto-merge

#22319 Fix return values from ResetAsync
  src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
  src/EFCore/ChangeTracking/ChangeTracker.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Internal/InternalDbSet.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: Servicing-approved

#22314 Cache derived types used in DerivedTypeDiscoveryConvention.
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/InheritanceDiscoveryConventionBase.cs
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  test/EFCore.Tests/Metadata/Conventions/DerivedTypeDiscoveryConventionTest.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: Servicing-approved, auto-merge

#22321 Exception message update
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  tools/Resources.tt
Labels: Servicing-approved

#22322 Stop repeatedly detecting changed properties on Deleted entities
  src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Labels: Servicing-approved

#22318 Make DbFunctions non-evaluatable
  src/EFCore.Relational/Query/RelationalEvaluatableExpressionFilter.cs
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerEvaluatableExpressionFilter.cs
  src/EFCore/Query/EvaluatableExpressionFilter.cs
  test/EFCore.Relational.Specification.Tests/Query/RelationalNorthwindDbFunctionsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindDbFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
Labels: Servicing-approved

#22333 Update exception messages
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Proxies.Tests/ProxyTests.cs
Labels: Servicing-approved

#22334 PMC Tools: Throw a better exception when ActiveConfiguration returns null
  src/EFCore.Tools/tools/EntityFrameworkCore.psm1
Labels: Servicing-approved, auto-merge
