Repository dotnet/efcore, pull requests merged in 2020-04, with the labels that each got.

#20064 [3.1] Fix to #19825 - Query: incorrectly generating JOIN rather than APPLY for subqueries with outside references to a joined table
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
Labels: Servicing-approved

#20362 [3.1] Fix to #12729 - Flatten Case expression
  src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Labels: Servicing-approved

#20530 Cleanup and add documentation for IndentedStringBuilder
  src/EFCore.Cosmos/Query/Internal/SqlUnaryExpression.cs
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Relational/Migrations/MigrationCommandListBuilder.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlUnaryExpression.cs
  src/EFCore.Relational/Storage/IRelationalCommandBuilder.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilder.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
  src/EFCore/Infrastructure/IndentedStringBuilder.cs
  src/EFCore/Query/EntityShaperExpression.cs
  src/EFCore/Query/ExpressionPrinter.cs
  src/EFCore/Query/ProjectionBindingExpression.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
  test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
Labels: providers-beware

#20579 Pin 2 CoreFx dependencies
  eng/Version.Details.xml
  eng/Versions.props
Labels: tell-mode

#20521 [release/3.1] Check if parameter.Name is not null before comparing it with query pa…
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Labels: Servicing-approved

#20574 [release/3.1] Cosmos: Avoid using "value" as an alias
  src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
Labels: Servicing-consider

#20619 Query: Make Visitor.Visit* method names consistent
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
  src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
Labels: providers-beware

#20697 Update branding to preview5
  eng/Versions.props
Labels: area-infrastructure

#20700 Use newer post-build.yml than Arcade provides
  eng/common/templates/post-build/post-build.yml
Labels: area-infrastructure

#20767 Query: API Cleanup
  src/EFCore.Relational/Query/CollectionInitializingExpression.cs
  src/EFCore.Relational/Query/CollectionPopulatingExpression.cs
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/ISqlExpressionFactory.cs
  src/EFCore.Relational/Query/Internal/CollateTranslator.cs
  src/EFCore.Relational/Query/Internal/CollectionInitializingExpression.cs
  src/EFCore.Relational/Query/Internal/CollectionPopulatingExpression.cs
  src/EFCore.Relational/Query/Internal/FromSqlParameterApplyingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalParameterBasedQueryTranslationPostprocessorFactory.cs
  src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
  src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
  src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessorDependencies.cs
  src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessorFactory.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitorDependencies.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/CollateExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/ProjectionExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerMemberTranslatorProvider.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerFixture.cs
  test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteFixture.cs
Labels: providers-beware
