Repository dotnet/efcore, pull requests merged in 2020-09, with the labels that each got.

#22345 Fix to #22293 - AssertIncludeCollection ordering of elements issue
  test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryFixtureBase.cs
Labels: auto-merge

#22346 Add the column type to the migration when deleting a data using a removed column
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
  src/EFCore.Relational/Update/ColumnModification.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#21990 Fix to #15873 - Query: Identifying columns in the case of distinct
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
Labels: Servicing-approved, Servicing-consider

#22343 Be consistent about OnModelCreating as the terminology for fluent API
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.Relational/Extensions/Internal/TupleExtensions.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Infrastructure/AnnotatableExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/Shared/Multigraph.cs
  test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
  test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/ListLoggerFactory.cs
  test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Utilities/MultigraphTest.cs
Labels: Servicing-approved

#22357 Add regression test for issue#15215
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved, auto-merge

#22361 Populate DbUpdateException.Entries for non-concurrency exceptions
  src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
Labels: Servicing-approved

#22360 Print expression when throwing null type mapping in SQL tree
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
Labels: Servicing-approved

#22372 Relax restriction on derived FKs using value-generation properties from composite keys.
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
Labels: Servicing-approved

#22373 Exception message review (Cont.)
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
Labels: Servicing-approved

#22392 Continuation of exception message review
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Storage/ValueConversion/ValueConverter.cs
  src/dotnet-ef/Properties/Resources.Designer.cs
  src/dotnet-ef/Properties/Resources.resx
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
  test/EFCore.Tests/Storage/EnumToNumberConverterTest.cs
  test/EFCore.Tests/Storage/NumberToBytesConverterTest.cs
  test/EFCore.Tests/Storage/NumberToStringConverterTest.cs
  test/EFCore.Tests/Storage/StringToNumberConverterTest.cs
Labels: Servicing-approved

#22376 Propagate identity seed and increment to sharing columns
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Labels: Servicing-approved

#22398 Correctly break double cycles in FK constraints
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/Shared/Multigraph.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: Servicing-approved

#22405 Query: Find correct table to use when owned entity is mapped to diffe…
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved

#22412 Merge ExistingConnectionTest with ConnectionSpecificationTest
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore/ChangeTrackingStrategy.cs
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  test/EFCore.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs
  test/EFCore.SqlServer.FunctionalTests/ExistingConnectionTest.cs
Labels: auto-merge

#22408 Updates to shared-type entity type handling in proxies
  src/EFCore.Proxies/Properties/ProxiesStrings.Designer.cs
  src/EFCore.Proxies/Properties/ProxiesStrings.resx
  src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
  src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/Shared/MemberInfoExtensions.cs
  test/EFCore.Proxies.Tests/ChangeDetectionProxyTests.cs
  test/EFCore.Proxies.Tests/ProxyTests.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: Servicing-approved

#22419 Don't check for temporary values on non-key properties when deleting an entity
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs
Labels: Servicing-approved

#22427 Snapshot using comparer even when property is store-generated
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
Labels: Servicing-approved

#22425 Allow discriminator properties to have value converter and comparer
  src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore/ChangeTracking/ValueComparer.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Query/EntityShaperExpression.cs
  src/EFCore/Query/Internal/StaticDiscriminatorComparer.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
Labels: Servicing-approved

#22439 Stop attempting to do local DetectChanges when not snapshot change-tracking
  src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
  test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
Labels: Servicing-approved

#22443 Flow missing cancellation token in HiLo generator
  src/EFCore/ValueGeneration/HiLoValueGenerator.cs
Labels: Servicing-approved

#22426 Stop generating CommandError if CommandExecuted has already happened
  src/EFCore.Relational/Storage/RelationalCommand.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
Labels: Servicing-approved

#22438 Automatically create notification collections when change-tracking proxies are being used
  src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
  src/EFCore/Metadata/Internal/CollectionTypeFactory.cs
  test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityBranch.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityCompositeKey.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityLeaf.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityRoot.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityTwo.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
  test/EFCore.Tests/Metadata/Internal/CollectionTypeFactoryTest.cs
Labels: Servicing-approved

#22449 Remove Microsoft.Azure.Cosmos.Direct from nupkg
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
Labels: auto-merge

#22450 Improve exception messages (cont...)
  src/EFCore/Infrastructure/Annotatable.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.BaseType.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
Labels: auto-merge

#22469 Tools: Review resource strings
  src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
  src/EFCore.Tools/tools/EntityFrameworkCore.psm1
  src/EFCore.Tools/tools/about_EntityFrameworkCore.help.txt
  src/dotnet-ef/Properties/Resources.Designer.cs
  src/dotnet-ef/Properties/Resources.resx
  src/ef/Commands/DbContextScriptCommand.Configure.cs
  src/ef/Properties/Resources.Designer.cs
  src/ef/Properties/Resources.resx
Labels: Servicing-approved, auto-merge

#22471 Remove extra ToList calls in MigrationsModelDiffer
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
Labels: Servicing-approved

#22470 Generate conditionals instead of switch in materializer delegate for discriminator values that need custom comparison
  src/EFCore/Query/EntityShaperExpression.cs
  src/EFCore/Query/Internal/StaticDiscriminatorComparer.cs
Labels: Servicing-approved

#22480 Microsoft.Data.Sqlite: Review resources
  src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs
  src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
  src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Labels: auto-merge

#22472 [release/3.1] Query: Unwind nested invocation expressions
  src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Labels: Servicing-approved

#22479 Add RelationalModel debug property to Model
  src/EFCore.Relational/Extensions/RelationalModelExtensions.cs
  src/EFCore.Relational/Metadata/SqlQueryExtensions.cs
  src/EFCore.Relational/Metadata/StoreFunctionExtensions.cs
  src/EFCore.Relational/Metadata/TableExtensions.cs
  src/EFCore.Relational/Metadata/ViewExtensions.cs
  src/EFCore/Metadata/Internal/Model.cs
Labels: Servicing-approved

#22488 Design: Review resources
  src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
  src/EFCore.Design/Design/Internal/DbContextOperations.cs
  src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
Labels: Servicing-approved, auto-merge

#22485 Clone DbParameter when adding to command if ICloneable
  src/EFCore.Relational/Storage/Internal/RawRelationalParameter.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Labels: Servicing-approved

#22507 Handle stale skip FKs in ForeignKeyPropertyDiscoveryConvention
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: Servicing-approved

#22511 Improve exception messages
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  src/EFCore.Cosmos/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.resx
  src/EFCore.InMemory/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Metadata/Internal/DbFunction.cs
  src/EFCore.Relational/Metadata/Internal/DbFunctionParameter.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  src/EFCore.Sqlite.Core/Internal/SqliteLoggerExtensions.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/EntityShaperExpression.cs
  src/EFCore/Query/ExpressionPrinter.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
  test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindStringIncludeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
Labels: Servicing-approved, auto-merge

#22531 [5.0.0-rc2] Change ChangeTrackingStrategy from annotation to field
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/ConventionModelExtensions.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Extensions/ModelExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Extensions/MutableModelExtensions.cs
  src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/Model.cs
Labels: Servicing-consider, area-perf

#22534 [5.0.0-rc2] Throw for ForeignKeyAttribute on skip navigation
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: Servicing-approved

#22546 Update to .NET SDK 5.0 RC1
  eng/helix.proj
  global.json
  src/EFCore.Tools/EFCore.Tools.csproj
  src/ef/ef.csproj
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
  test/EFCore.Design.Tests/DesignExceptionTest.cs
  test/EFCore.Tests/ExceptionTest.cs
Labels: auto-merge, tell-mode

#22550 [5.0-rc2] RevEng: Remove ColumnType annotation from scaffolded code
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
Labels: Servicing-approved

#22574 Move some provider-facing tests to specifications
  test/Directory.Build.props
  test/EFCore.Cosmos.FunctionalTests/CosmosApiConsistencyTest.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestHelpers.cs
  test/EFCore.InMemory.FunctionalTests/InMemoryApiConsistencyTest.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsInfrastructureTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.Relational.Specification.Tests/Update/UpdateSqlGeneratorTestBase.cs
  test/EFCore.Relational.Tests/Storage/RelationalSqlGenerationHelperTest.cs
  test/EFCore.Relational.Tests/Storage/SqlGenerationHelperTestBase.cs
  test/EFCore.Specification.Tests/ApiConsistencyTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerApiConsistencyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/SqlServerUpdateSqlGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerSqlGenerationHelperTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsInfrastructureSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/SqliteApiConsistencyTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/SqliteUpdateSqlGeneratorTest.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationBuilderTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteSqlGenerationHelperTest.cs
Labels: auto-merge, providers-beware

#22585 Generate values for PK properties that are also self-referencing FK properties
  src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
  src/EFCore/Metadata/Internal/PropertyExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
Labels: Servicing-approved

#22587 [5.0.0-rc2] Add null checks to account for owned types in TPT
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  test/EFCore.Relational.Specification.Tests/DataAnnotationRelationalTestBase.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
Labels: Servicing-approved

#22596 Move types out of top-level Internal namespaces
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
  src/EFCore.InMemory/Infrastructure/Internal/InMemoryModelValidator.cs
  src/EFCore.Relational/Storage/Internal/RelationalDatabaseFacadeDependencies.cs
  src/EFCore.SqlServer/Extensions/Internal/SqlServerLoggerExtensions.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  src/EFCore.Sqlite.Core/Extensions/Internal/SqliteLoggerExtensions.cs
  src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteModelValidator.cs
  src/EFCore/Diagnostics/Internal/DiagnosticsLogger.cs
  src/EFCore/Diagnostics/Internal/LoggingOptions.cs
  src/EFCore/Diagnostics/Internal/ScopedLoggerFactory.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Infrastructure/Internal/ConcurrencyDetector.cs
  src/EFCore/Infrastructure/Internal/CoreOptions.cs
  src/EFCore/Infrastructure/Internal/CurrentDbContext.cs
  src/EFCore/Infrastructure/Internal/DbSetFinder.cs
  src/EFCore/Infrastructure/Internal/InternalServiceCollectionMap.cs
  src/EFCore/Infrastructure/Internal/LazyLoader.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Infrastructure/ServiceCollectionMap.cs
  src/EFCore/Internal/DbContextServices.cs
  src/EFCore/Storage/Internal/DatabaseFacadeDependencies.cs
  test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/SequenceUniquificationConventionTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
  test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsAssemblyTest.cs
  test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
  test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
  test/EFCore.Specification.Tests/TestUtilities/TestLogger.cs
  test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
  test/EFCore.SqlServer.Tests/SqlServerEventIdTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
  test/EFCore.Tests/DbContextServicesTest.cs
  test/EFCore.Tests/EntitySetFinderTest.cs
  test/EFCore.Tests/Infrastructure/InternalServiceCollectionMapTest.cs
  test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
  test/EFCore.Tests/ModelSourceTest.cs
Labels: auto-merge

#22602 [release/5.0-rc2] Make newline escaping logic more robust
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs
  test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerStringTypeMappingTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteStringTypeMappingTest.cs
Labels: Servicing-approved

#22620 Add some docs on CommandTimeout
  src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs
Labels: auto-merge

#22612 [5.0-rc2] Throw exception for cycles in auto included navigations
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved, Servicing-consider

#22607 [5.0-rc2] Also clear the store generated values when setting a normal value
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
  src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  test/EFCore.Relational.Specification.Tests/DataAnnotationRelationalTestBase.cs
Labels: Servicing-approved

#22638 Fix analyzer test after internal type was moved
  src/EFCore/Infrastructure/Internal/CoreSingletonOptions.cs
  test/EFCore.Analyzers.Tests/InternalUsageDiagnosticAnalyzerTest.cs
Labels: auto-merge

#22640 5.0 Migrations: Correctly generate UseIdentityColumn(s) API in snapshot
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#22625 Enable NetAnalyzers reliability and globalization rules
  rulesets/FxCop.ruleset
  src/.editorconfig
  src/Directory.Build.props
  src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
  src/EFCore.Cosmos/Query/Internal/KeyAccessExpression.cs
  src/EFCore.Cosmos/Query/Internal/ProjectionExpression.cs
  src/EFCore.Cosmos/Query/Internal/RootReferenceExpression.cs
  src/EFCore.Cosmos/Query/Internal/SqlFunctionExpression.cs
  src/EFCore.Cosmos/Query/Internal/SqlParameterExpression.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
  src/EFCore.Relational/Extensions/RelationalTaskExtensions.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/ProjectionExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlFragmentExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlParameterExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpressionBase.cs
  src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.SqlServer.NTS/Query/Internal/SqlServerLineStringMemberTranslator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeMemberTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMathTranslator.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteGuidTypeMapping.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Extensions/Internal/TypeExtensions.cs
  src/EFCore/Query/Internal/EntityQueryable`.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  src/EFCore/Storage/ExecutionStrategyExtensions.cs
  src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
  src/dotnet-ef/RootCommand.cs
  src/ef/CommandLineUtils/CommandLineApplication.cs
  src/ef/CommandLineUtils/CommandLineApplicationExtensions.cs
  src/ef/CommandLineUtils/CommandOption.cs
  src/ef/Commands/DatabaseDropCommand.cs
  src/ef/Commands/DatabaseUpdateCommand.cs
  src/ef/Commands/DbContextInfoCommand.cs
  src/ef/Commands/DbContextListCommand.cs
  src/ef/Commands/DbContextScaffoldCommand.cs
  src/ef/Commands/DbContextScriptCommand.cs
  src/ef/Commands/MigrationsAddCommand.cs
  src/ef/Commands/MigrationsListCommand.cs
  src/ef/Commands/MigrationsRemoveCommand.cs
  src/ef/Commands/MigrationsScriptCommand.cs
Labels: auto-merge

#22610 [5.0 RC2] Handle square brackets around explicitly specified SQL Server type names
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
Labels: Servicing-approved

#22652 [5.0-rc2] Don't remove skip foreign key when join entity type is configured explicitly.
  src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: Servicing-approved

#22669 [5.0-rc2] Mark join entities as Added when either side is Added
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/GeneratedKeysLeft.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/GeneratedKeysRight.cs
  test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
Labels: Servicing-approved

#22648 Adding tests for previously fixed issues
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindAggregateOperatorsQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindAsyncSimpleQueryInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindAsyncSimpleQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#22672 [5.0-rc2] Undo GetColumnName behavior change
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs
  test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
  test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
Labels: Servicing-approved, auto-merge

#22676 Fix the model in GraphUpdatesSqlServerTest.TptIdentity
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
Labels: auto-merge

#22649 Include commit SHA in `[AssemblyInformationalVersion]` value
  Directory.Build.targets
Labels: area-infrastructure, tell-mode

#22750 Rename Analyzer test project name
  All.sln
  EFCore.Cosmos.slnf
  EFCore.Relational.slnf
  EFCore.Runtime.slnf
  EFCore.Sqlite.slnf
  EFCore.slnf
  test/EFCore.Analyzers.Tests/EFCore.Analyzers.Tests.csproj
  test/EFCore.Analyzers.Tests/InternalUsageDiagnosticAnalyzerTest.cs
  test/EFCore.Analyzers.Tests/TestUtilities/DiagnosticAnalyzerTestBase.cs
Labels: auto-merge

#22791 Replace AsyncLock with SemaphoreSlim
  src/.editorconfig
  src/EFCore/Internal/AsyncLock.cs
  src/EFCore/ValueGeneration/HiLoValueGeneratorState.cs
Labels: auto-merge, type-cleanup

#22793 Improve exception messages
  src/EFCore.Proxies/Properties/ProxiesStrings.Designer.cs
  src/EFCore.Proxies/Properties/ProxiesStrings.resx
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.Sqlite.NTS/Properties/SqliteNTSStrings.Designer.cs
  src/EFCore.Sqlite.NTS/Properties/SqliteNTSStrings.resx
  src/EFCore/ChangeTracking/EntityEntry.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Internal/InternalDbSet.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
  src/EFCore/Metadata/Internal/SkipNavigation.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/SkipNavigationTest.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Labels: auto-merge

#22846 [5.0] Remove the correct conflicting skip navigation.
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
Labels: Servicing-approved

#22845 [5.0] Use the schema of related ends for the join entity type by default
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: Servicing-approved
