Repository dotnet/efcore, pull requests merged in 2020-12, with the labels that each got.

#23480 Query: Add regression test for #21003
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
Labels: auto-merge

#23483 Query: Throw error for translating Lambda right away
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
Labels: auto-merge

#23620 [5.0.2] SQLite Migrations: Quote table names in FROM clause during rebuilds
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#23649 [5.0.2] Fix Overrides_ForeignKeyAttribute
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
Labels: auto-merge

#23634 [5.0.2] Migrations: Generate valid SQL when escaping new lines in seed data
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs
  test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
  test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteStringTypeMappingTest.cs
Labels: Servicing-approved

#23210 SqlServer: Translate ArrayAccess/First over byte[]
  src/EFCore.SqlServer/Query/Internal/SqlServerByteArrayMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteByteArrayMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/MonsterFixupTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#23177 Test SqlServer test on Ubuntu in helix
  azure-pipelines.yml
  eng/helix.proj
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Labels: auto-merge

#23666 Scaffold IsFixedLength() instead of IsFixedLength(true)
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
Labels: waiting-for-response

#23706 Re-enable flaky CI tests on SqlServer on Ubuntu
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
  test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
Labels: auto-merge

#23733 Try to fix build failures in SqlServer ubuntu run
  eng/helix.proj
Labels: auto-merge

#23748 Replace shadow entities with property bag entity types.
  EFCore.Runtime.slnf
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntryFactory.cs
  src/EFCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
  src/EFCore/Metadata/Conventions/NotMappedMemberAttributeConvention.cs
  src/EFCore/Metadata/Conventions/OwnedEntityTypeAttributeConvention.cs
  src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
  src/EFCore/Metadata/ITypeBase.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/Navigation.cs
  src/EFCore/Metadata/Internal/Property.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/EntityMaterializerSource.cs
  src/Shared/DictionaryExtensions.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
  test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryFactoryTest.cs
  test/EFCore.Tests/Extensions/PropertyExtensionsTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.BaseType.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
  test/EFCore.Tests/Metadata/Internal/ModelTest.cs
  test/EFCore.Tests/ModelBuilding/ShadowEntityTypeTest.cs
Labels: auto-merge

#23145 Add EF.Functions.Random
  EFCore.Runtime.slnf
  EFCore.Sqlite.slnf
  EFCore.slnf
  src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
  src/EFCore.Cosmos/Query/Internal/RandomTranslator.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RandomTranslator.cs
  src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteRandomTranslator.cs
  src/EFCore/DbFunctionsExtensions.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindDbFunctionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindDbFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
Labels: auto-merge
