Repository dotnet/efcore, pull requests merged in 2020-03, with the labels that each got.

#20035 SQLite: Enable ef_compare for decimals
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
Labels: accepted

#20197 Update branding to preview3
  eng/Versions.props
Labels: area-infrastructure

#20214 [master] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: area-infrastructure

#20215 [release/5.0-preview2] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: accepted, add-regression-test, area-infrastructure, tell-mode

#20207 [release/3.1] Query: Map projection properly when joining 2 tables
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Labels: Servicing-approved

#20077 [release/3.1] Microsoft.Data.Sqlite: Set temp and data directory on UWP
  src/Microsoft.Data.Sqlite.Core/Properties/Microsoft.Data.Sqlite.rd.xml
  src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs
  src/Microsoft.Data.Sqlite.Core/Utilities/BundleInitializer.cs
Labels: Servicing-approved

#20217 [release/2.1] Update hosted and BYOC agents used in our builds
  build/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#20216 [release/3.1] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#20422 Query: Factories used during compilation time should take QueryCompil…
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore.Relational/Query/IRelationalSqlTranslatingExpressionVisitorFactory.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore.Relational/Query/Internal/RelationalSqlTranslatingExpressionVisitorFactory.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitorFactory.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitorFactory.cs
  src/EFCore/Query/IQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore/Query/QueryCompilationContext.cs
Labels: breaking-change, providers-beware

#20472 Update branding to preview4
  eng/Versions.props
Labels: area-infrastructure, tell-mode
