Repository dotnet/efcore, pull requests merged in 2020-10, with the labels that each got.

#22875 [release/5.0] Ensure grandchildren and below are mapped to the root table when using table sharing.
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Specification.Tests/TestModels/TransportationModel/CompositeVehicle.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
Labels: Servicing-approved

#22884 [5.0] Fix places where skip navigations are missed
  src/EFCore/ChangeTracking/EntityEntry.cs
  src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  test/EFCore.InMemory.FunctionalTests/ManyToManyTrackingInMemoryTest.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs
  test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs
Labels: Servicing-consider

#22908 [5.0] Add validation for seed data with skip navigations
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Labels: Servicing-approved

#22533 Query: Mark entity shaper nullable only when correct
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Labels: auto-merge

#22925 Don't print trailing comma for enumerable constants
  src/EFCore/Query/ExpressionPrinter.cs
  test/EFCore.Tests/Query/ExpressionPrinterTest.cs
Labels: auto-merge

#22933 SqlServer: Stop yelling VARCHAR
  src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerDateDiffFunctionsTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDatabaseCleaner.cs
Labels: auto-merge

#22869 Implement savepoint API for Microsoft.Data.Sqlite
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Labels: auto-merge

#22918 Upgrade to a 6.0 SDK
  eng/helix.proj
  global.json
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
Labels: area-platform

#22760 [release/3.1] Fix issue where property with value generated on add is reseeded in every migration
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Labels: Servicing-approved

#22650 [release/3.1] Include commit SHA in `[AssemblyInformationalVersion]` value
  Directory.Build.targets
Labels: area-infrastructure, tell-mode

#22984 [release/5.0] Update to .NET SDK 5.0 RC2
  eng/helix.proj
  global.json
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
Labels: Servicing-consider

#22982 Work around mono bug affecting Xamarin Android
  src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
Labels: Servicing-approved

#22995 Work around mono bug affecting Xamarin Android (#22982)
  src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
Labels: Servicing-approved

#23005 [release/5.0] SqlServer Migrations: Don't generate EXEC(CONCAT())
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#22519 Exception message review
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
Labels: auto-merge

#23080 Improve exception messages
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Relational.Tests/RelationalOptionsExtensionTest.cs
  test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Labels: auto-merge

#23083 [release/5.0] SqlServer RevEng: Stop scaffolding included index columns
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: Servicing-approved

#23084 [release/5.0] SqlServer Migrations: Don't omit ALTER COLUMN when old type is unknown
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#23119 Update to Microsoft.Data.SqlClient 2.1.0-preview2
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: auto-merge, type-dependency update :arrow_up_small:

#23120 Update to Microsoft.Azure.Cosmos 3.15.0-preview
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
Labels: auto-merge, type-dependency update :arrow_up_small:

#22367 Fix to #21402 - Test using OData
  .github/dependabot.yml
  All.sln
  EFCore.Relational.slnf
  EFCore.Runtime.slnf
  EFCore.slnf
  test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
  test/EFCore.OData.FunctionalTests/Extensions/HttpContentExtensions.cs
  test/EFCore.OData.FunctionalTests/Properties/TestAssemblyConditions.cs
  test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsControllers.cs
  test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataContext.cs
  test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
  test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTests.cs
  test/EFCore.OData.FunctionalTests/Query/GearsOfWarControllers.cs
  test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataContext.cs
  test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTestFixture.cs
  test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTests.cs
  test/EFCore.OData.FunctionalTests/Query/IODataQueryTestFixture.cs
  test/EFCore.OData.FunctionalTests/Query/NorthwindControllers.cs
  test/EFCore.OData.FunctionalTests/Query/NorthwindODataContext.cs
  test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTestFixture.cs
  test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
  test/EFCore.OData.FunctionalTests/Query/ODataQueryTestBase.cs
  test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
  test/EFCore.OData.FunctionalTests/TestAssembly.cs
  test/EFCore.OData.FunctionalTests/TestControllers.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerNorthwindTestStoreFactory.cs
Labels: not-in-5.0

#23133 First nullability work on metadata
  src/EFCore/Infrastructure/Annotatable.cs
  src/EFCore/Infrastructure/IAnnotatable.cs
  src/EFCore/Metadata/IConventionAnnotatable.cs
  src/EFCore/Metadata/IConventionEntityType.cs
  src/EFCore/Metadata/IEntityType.cs
  src/EFCore/Metadata/IMutableAnnotatable.cs
  src/EFCore/Metadata/IMutableEntityType.cs
  src/EFCore/Metadata/ITypeBase.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/Shared/NonCapturingLazyInitializer.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Labels: auto-merge

#22497 Translate Regex.IsMatch on SQLite
  src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
Labels: accepted

#23036 Delimit savepoint names as identifiers
  All.sln.DotSettings
  src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
  src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
  src/EFCore.Relational/Storage/RelationalTransaction.cs
  src/EFCore.Relational/Storage/RelationalTransactionFactory.cs
  src/EFCore.Relational/Storage/RelationalTransactionFactoryDependencies.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTransaction.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTransactionFactory.cs
  src/EFCore/Storage/IDbContextTransaction.cs
  test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
  test/EFCore.Relational.Tests/Storage/RelationalTransactionExtensionsTest.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
  test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
  test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
Labels: auto-merge
