Repository dotnet/efcore, pull requests merged in 2021-12, with the labels that each got.

#26758 test and fix for Issue #26742
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
Labels: community-contribution

#26737 [release/3.1] Update to Mac OS 11 image
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#26738 [release/5.0] Update to Mac OS 11 image
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#26739 [release/6.0] Update to Mac OS 11 image
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#26582 Query: Add multiple parameters if inferred type mapping differs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Storage/IRelationalCommandBuilder.cs
  src/EFCore.Relational/Storage/Internal/DynamicRelationalParameter.cs
  src/EFCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilder.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilderDependencies.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGeneratorFactory.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Relational.Tests/Storage/RawSqlCommandBuilderTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
Labels: auto-merge

#27002 Merging internal commits for release/3.1
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure, tell-mode

#27000 Merging internal commits for release/5.0
  global.json
Labels: area-infrastructure, tell-mode

#26892 [6.0.2] Detach join entity when removing added relationship
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
Labels: Servicing-approved

#26943 [6.0.2] Call sync connection close instead of async
  src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
  src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
  src/EFCore/DbContext.cs
  src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
  src/EFCore/Infrastructure/Internal/LazyLoader.cs
  src/EFCore/Infrastructure/PooledDbContextFactory.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
  src/EFCore/Storage/ExecutionStrategyExtensions.cs
  test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.Tests/SqlServerOptionsExtensionTest.cs
  test/EFCore.Tests/DbSetTest.cs
Labels: Servicing-approved

#26958 [6.0.2] Handle duplicate property infos when sorting columns.
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: Servicing-approved

#26959 [6.0.2] Restore the ability to break multiple FK cycles
  src/Shared/Multigraph.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: Servicing-approved

#26963 [6.0.2] Add the ability to break self-ref cycles between added and removed entities
  src/Shared/Multigraph.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
  test/EFCore.Specification.Tests/UpdatesFixtureBase.cs
  test/EFCore.Specification.Tests/UpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
Labels: Servicing-approved

#26617 [6.0.2] Query: Defer inline-ing owned navigation expansion till all joins are generated
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
Labels: Servicing-approved

#27019 Tweak SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841
  test/EFCore.Specification.Tests/TestUtilities/SingleThreadSynchronizationContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#27003 WithMany doc: fix the sample expression
  src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
Labels: community-contribution
