Repository dotnet/efcore, pull requests merged in 2021-08, with the labels that each got.

#25178 Enable value conversion support for identity/sequence properties
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
Labels: providers-beware

#25375 Incorporate API Review feedback
  src/EFCore.Design/Design/OperationExecutor.cs
  src/EFCore.InMemory/Infrastructure/InMemoryDbContextOptionsBuilder.cs
  src/EFCore.Relational/Query/RelationalCollectionShaperExpression.cs
  src/EFCore.Relational/Query/RelationalSplitCollectionShaperExpression.cs
  src/ef/Commands/DbContextOptimizeCommand.cs
  src/ef/IOperationExecutor.cs
  src/ef/OperationExecutorBase.cs
  test/EFCore.InMemory.FunctionalTests/NullabilityCheckInMemoryTest.cs
  test/EFCore.InMemory.Tests/ModelBuilding/InMemoryModelBuilderGenericTest.cs
Labels: auto-merge

#25471 Tune mappings between ReferentialAction and DeleteBehavior
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
Labels: providers-beware, breaking-change

#24360 Remove last ORDER BY for collection joins
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyFieldsLoadSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/CompositeKeysQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Labels: auto-merge

#25510 Microsoft.Data.Sqlite: Revert to using string overload of sqlite3_prepare
  src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Labels: auto-merge

#25495 Query: Add support for GroupBy patterns beyond aggregate
  src/EFCore.InMemory/Query/Internal/EntityProjectionExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryGroupByShaperExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.Helper.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Query/GroupByShaperExpression.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/ProjectionMember.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
Labels: providers-beware, breaking-change, auto-merge

#25552 Query: Add a test for group by constant composed
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Labels: auto-merge

#25540 Add scalar type configuration support to compiled models.
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore/Design/Internal/ICSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
  src/EFCore/Metadata/RuntimeModel.cs
  src/EFCore/Metadata/RuntimeScalarTypeConfiguration.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Labels: auto-merge

#25557 Query: Run shaper only when needed in SplitQueryingEnumerable
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#25558 RevEng: SqlServer: Escape table name passed from user correctly
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: auto-merge

#25568 Correct FromSqlRaw docs
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
Labels: auto-merge

#25577 Query: Remove unnecessary convert to IEnumerable for OData
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
Labels: auto-merge

#25578 Query: Add regression test for Contains on skip collection navigation
  test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
Labels: auto-merge

#25626 Disable nullability in migrations
  src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: auto-merge

#25623 Tweaks to ValueComparer nullability (RC1)
  src/EFCore.Cosmos/ChangeTracking/Internal/ListComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableSingleDimensionalArrayComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableStringDictionaryComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
  src/EFCore/ChangeTracking/GeometryValueComparer.cs
  src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
  src/EFCore/ChangeTracking/Internal/ValueComparerExtensions.cs
  src/EFCore/ChangeTracking/ValueComparer.cs
  src/EFCore/ChangeTracking/ValueComparer`.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.Tests/Storage/ValueComparerTest.cs
Labels: auto-merge

#25633 Disable nullability in migrations
  src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: auto-merge

#25587 Support value conversion for ReadOnlyIPAddress
  src/EFCore/Storage/ValueConversion/ValueConverterSelector.cs
  test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Faction.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Tests/Storage/ValueConverterSelectorTest.cs
Labels: auto-merge

#25668 [release/6.0-rc1] Fix #25225 by forcing usage of renting and populating commands when using relational command cache
  src/EFCore.Relational/Extensions/Internal/RelationCommandCacheExtensions.cs
  src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
  src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Storage/IRelationalCommand.cs
  src/EFCore.Relational/Storage/IRelationalCommandTemplate.cs
  src/EFCore.Relational/Storage/RelationalCommand.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
  test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
  test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
Labels: Servicing-approved

#25664 [release/6.0-rc1] Remove unused nullability in typeof
  src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
Labels: Servicing-approved
