Repository dotnet/efcore, pull requests merged in 2021-09, with the labels that each got.

#25840 Set the DbType on parameters wherever possible
  src/EFCore.Relational/Storage/BoolTypeMapping.cs
  src/EFCore.Relational/Storage/ByteArrayTypeMapping.cs
  src/EFCore.Relational/Storage/ByteTypeMapping.cs
  src/EFCore.Relational/Storage/CharTypeMapping.cs
  src/EFCore.Relational/Storage/DateOnlyTypeMapping.cs
  src/EFCore.Relational/Storage/DateTimeOffsetTypeMapping.cs
  src/EFCore.Relational/Storage/DateTimeTypeMapping.cs
  src/EFCore.Relational/Storage/DecimalTypeMapping.cs
  src/EFCore.Relational/Storage/DoubleTypeMapping.cs
  src/EFCore.Relational/Storage/FloatTypeMapping.cs
  src/EFCore.Relational/Storage/GuidTypeMapping.cs
  src/EFCore.Relational/Storage/IntTypeMapping.cs
  src/EFCore.Relational/Storage/LongTypeMapping.cs
  src/EFCore.Relational/Storage/SByteTypeMapping.cs
  src/EFCore.Relational/Storage/ShortTypeMapping.cs
  src/EFCore.Relational/Storage/StringTypeMapping.cs
  src/EFCore.Relational/Storage/TimeOnlyTypeMapping.cs
  src/EFCore.Relational/Storage/TimeSpanTypeMapping.cs
  src/EFCore.Relational/Storage/UIntTypeMapping.cs
  src/EFCore.Relational/Storage/ULongTypeMapping.cs
  src/EFCore.Relational/Storage/UShortTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerBoolTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerByteTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerLongTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerShortTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateOnlyTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeOffsetTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteDecimalTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteGuidTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteTimeOnlyTypeMapping.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteULongTypeMapping.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandBuilderTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
  test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
  test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NullSemanticsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
Labels: providers-beware

#25550 [release/3.1] Update SQLite dependencies to 2.0.4
  eng/Versions.props
Labels: Servicing-approved

#25942 Migrations: Honor [Column(Order)] in CreateTable operation
  src/EFCore.Design/Metadata/Internal/ScaffoldingAnnotationNames.cs
  src/EFCore.Design/Metadata/Internal/ScaffoldingPropertyExtensions.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.Relational/Diagnostics/ColumnsEventData.cs
  src/EFCore.Relational/Diagnostics/MigrationColumnOperationEventData.cs
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalColumnAttributeConvention.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
  src/EFCore.Relational/Metadata/IColumn.cs
  src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Relational.Tests/RelationalEventIdTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: auto-merge

#26051 Stabilize versions for 6.0.0 RTM
  eng/Versions.props
Labels: area-infrastructure

#26058 [6.0-rc2] Fix Fluent APIs on keys in model snapshot
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
Labels: Servicing-consider

#26036 Fixup deleted join entities
  src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Metadata/IEntityType.cs
  src/EFCore/Metadata/IReadOnlyEntityType.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Labels: Servicing-approved

#26087 [6.0-rc2] RevEng: Generate correct FK configuration for scaffolding
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#26066 [6.0-rc2] Fully support int identity seed
  src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#26099 Update dailybuild.md
  docs/DailyBuilds.md
Labels: community-contribution
