Repository dotnet/efcore, pull requests merged in 2021-11, with the labels that each got.

#26487 Query: Identify Contains on IReadOnlySet/IImmutableSet
  src/Shared/MethodInfoExtensions.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
Labels: auto-merge

#26470 Do not scaffold a default constructor when OnConfiguring is suppressed
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
Labels: community-contribution

#26511 Update branding to 6.0.1
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#26513 Update branding for 5.0.13
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#26512 Update branding for 3.1.22
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#26533 Query: Cleanup regarding TODO notes
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/EnumHasFlagTranslator.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  src/EFCore/Query/ReplacingExpressionVisitor.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
Labels: auto-merge

#26575 fix typo
  src/EFCore.Design/Design/OperationExecutor.cs
Labels: community-contribution

#26531 [6.0.1] RevEng: Consider skip navigation names when generating identifier for members of class
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: Servicing-approved

#26520 Avoid NRE in ForeignKeyAttributeConvention
  src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Labels: Servicing-approved

#26430 Allow non-nullable value comparer to be applied on nullable properties
  src/EFCore/Metadata/Internal/Property.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Labels: Servicing-approved

#26431 [6.0.1] Query: Copy client projections when updating SelectExpression
  src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Labels: Servicing-approved

#26577 [release/3.1] Update SDK
  global.json
Labels: tell-mode

#26529 [6.0.1] Microsoft.Data.Sqlite: Clean up on application exit
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Labels: Servicing-approved

#26614 [5.0.1] Move to OSX 11.0 for helix queues
  azure-pipelines.yml
Labels: area-infrastructure

#26615 [[6.0.1] Move to OSX 11.0 for helix queues
  azure-pipelines.yml
Labels: area-infrastructure

#26616 Move to OSX 11.0 for helix queues
  azure-pipelines.yml
Labels: area-infrastructure

#26622 RevEng: Don't use nameof syntax
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: auto-merge

#26623 Query: SqlServer: Add translation for string.IndexOf(string, int)
  src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
  src/EFCore.Cosmos/Query/Internal/CosmosStringMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
Labels: auto-merge, community-contribution

#26149 Switch to 1ES servicing pools on release/2.1
  build/templates/default-build.yml
Labels: area-infrastructure

#26599 [6.0.1] Query: Optimize Contains to Any recursively
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: Servicing-approved

#26640 Use latest SDK & runtime
  global.json
Labels: auto-merge

#26642 Query: More VB CompareString normalization
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
Labels: auto-merge

#26645 Match indexer properties correctly
  src/EFCore/Metadata/Internal/Property.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Labels: Servicing-approved

#26658 [6.0.1] Use read-write lock to protect concurrent pool accesses
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Labels: Servicing-consider

#26679 Use a unique identifier for variables during insert
  All.sln
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Labels: Servicing-approved

#26637 [6.0.1] Microsoft.Data.Sqlite: Handle more nulls in ApplicationDataHelper
  src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs
Labels: Servicing-approved

#26697 [6.0.1] Use read-write lock to protect concurrent pool accesses (#26658)
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Labels: Servicing-approved

#26699 [6.0.1] Avoid infinite loop when finding principal in circular relationships
  src/EFCore/Metadata/Internal/Property.cs
  test/EFCore.Tests/ChangeTracking/Internal/FixupCompositeTest.cs
Labels: Servicing-approved

#26700 [6.0.x] Query: Update table references in pushdown after moving table referen…
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: Servicing-approved

#26702 [6.0.x] Cosmos: Use configured serializer when reading
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/BuiltInDataTypesInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/ConvertToProviderTypesInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
  test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
  test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/ConvertToProviderTypesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
Labels: Servicing-approved

#26291 Cache Eventargs in SQLiteConnection
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Labels: community-contribution

#26719 Update the foreign key builder after IsRequired()
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
Labels: Servicing-approved

#26720 Use the correct builder when attaching indexes on nested owned entity types
  src/EFCore/Metadata/Internal/PropertiesSnapshot.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: Servicing-approved

#26660 Query: Introduce method for providing brackets around SqlExpression b…
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
Labels: auto-merge

#26725 Remove Windows/Ubuntu from helix testing as other pipeline covers it
  azure-pipelines.yml
Labels: auto-merge

#26730 Return null schema for unmapped entity types.
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
Labels: Servicing-consider

#26732 Update to Mac 11 image
  azure-pipelines.yml
Labels: auto-merge

#26641 Query: Defer inline-ing owned navigation expansion till all joins are…
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
Labels: auto-merge

#26680 Fix some markdown language syntax highlights
  docs/security.md
Labels: community-contribution

#26768 Skip flaky SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#26766 Remove Obsolete code
  src/EFCore.Proxies/Properties/ProxiesStrings.Designer.cs
  src/EFCore.Proxies/Properties/ProxiesStrings.resx
  src/EFCore.Relational/Diagnostics/CommandCorrelatedEventData.cs
  src/EFCore.Relational/Diagnostics/CommandEndEventData.cs
  src/EFCore.Relational/Diagnostics/CommandErrorEventData.cs
  src/EFCore.Relational/Diagnostics/CommandEventData.cs
  src/EFCore.Relational/Diagnostics/CommandExecutedEventData.cs
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
  src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/IRelationalConnection.cs
  src/EFCore.Relational/Storage/Internal/TypeMappedPropertyRelationalParameter.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.Relational/Storage/RelationalDatabaseCreatorDependencies.cs
  src/EFCore.Relational/Storage/TypeMaterializationInfo.cs
  src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/IColumnModification.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
  src/EFCore/Design/MethodCallCodeFragment.cs
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Storage/CoreTypeMapping.cs
  src/EFCore/Storage/ExecutionStrategy.cs
  src/EFCore/ValueGeneration/ValueGeneratorFactory.cs
  test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
  test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
Labels: auto-merge

#26734 Query: Fix double negation in SQL generation
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: auto-merge
