Repository dotnet/efcore, pull requests merged in 2021-04, with the labels that each got.

#24573 Warn for optional dependents sharing table without identifying column
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore/Diagnostics/EntityTypeEventData.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/ChangedChangingMonsterContext.cs
  test/EFCore.Specification.Tests/TestModels/ChangedOnlyMonsterContext.cs
  test/EFCore.Specification.Tests/TestModels/MonsterModel.cs
  test/EFCore.Specification.Tests/TestModels/SnapshotMonsterContext.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#24602 Update exception messages for optional dependents
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/TestModels/ChangedChangingMonsterContext.cs
  test/EFCore.Specification.Tests/TestModels/ChangedOnlyMonsterContext.cs
  test/EFCore.Specification.Tests/TestModels/MonsterModel.cs
  test/EFCore.Specification.Tests/TestModels/SnapshotMonsterContext.cs
  test/EFCore.Specification.Tests/TestModels/TransportationModel/FuelTank.cs
  test/EFCore.Specification.Tests/TestModels/TransportationModel/OperatorDetails.cs
  test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
  test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
Labels: auto-merge

#24604 Update branding to 3.1.15
  azure-pipelines.yml
  eng/Versions.props
Labels: area-infrastructure

#24592 Use Ubuntu 18.04 build agents
  build/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#24606 Check offset when comparing DateTimeOffset
  src/EFCore/ChangeTracking/ValueComparer.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
  test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
Labels: auto-merge

#24617 Make TestSqlLoggerFactory recognize quoting/curlies
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
Labels: auto-merge

#24624 Update DbContextOptionsBuilder.cs
  src/EFCore/DbContextOptionsBuilder.cs
Labels: community-contribution

#24626 Updating CI to set locale for ubuntu18.04.
  azure-pipelines.yml
Labels: area-infrastructure, auto-merge

#24651 Unskip `Double_dispose_does_not_enter_pool_twice` Test
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: auto-merge

#24653 Code merge and SDK update
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#24655 [release/2.1] Bump some versions
  build/dependencies.props
  korebuild-lock.txt
  src/EFCore.Specification.Tests/TestUtilities/Xunit/SkippedTestCase.cs
Labels: area-infrastructure, tell-mode

#24662 Allow type mapping source plugins to override built-in mappings
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
Labels: auto-merge

#24670 Update to 6.0.0-preview5
  eng/Versions.props
Labels: area-infrastructure

#24304 Suppress logging checks in query when not required, caching for 1 second
  src/EFCore.Relational/Diagnostics/IRelationalCommandDiagnosticsLogger.cs
  src/EFCore.Relational/Diagnostics/IRelationalConnectionDiagnosticsLogger.cs
  src/EFCore.Relational/Diagnostics/Internal/RelationalCommandDiagnosticsLogger.cs
  src/EFCore.Relational/Diagnostics/Internal/RelationalConnectionDiagnosticsLogger.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  src/EFCore.Relational/Migrations/MigrationCommand.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGeneratorDependencies.cs
  src/EFCore.Relational/Query/RelationalQueryContext.cs
  src/EFCore.Relational/Storage/IRelationalDatabaseFacadeDependencies.cs
  src/EFCore.Relational/Storage/Internal/RelationalDatabaseFacadeDependencies.cs
  src/EFCore.Relational/Storage/RelationalCommand.cs
  src/EFCore.Relational/Storage/RelationalCommandParameterObject.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.Relational/Storage/RelationalConnectionDependencies.cs
  src/EFCore.Relational/Storage/RelationalDataReader.cs
  src/EFCore.Relational/Storage/RelationalDatabaseCreatorDependencies.cs
  src/EFCore.Relational/Update/ModificationCommandBatchFactoryDependencies.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/ISqlServerSequenceValueGeneratorFactory.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerSequenceHiLoValueGenerator.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerSequenceValueGeneratorFactory.cs
  src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs
  src/EFCore/DbContextOptionsBuilder.cs
  src/EFCore/DbContextOptionsBuilder`.cs
  src/EFCore/Diagnostics/Internal/DiagnosticsLogger.cs
  src/EFCore/Infrastructure/CoreOptionsExtension.cs
  test/EFCore.Cosmos.Tests/CosmosEventIdTest.cs
  test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
  test/EFCore.InMemory.Tests/InMemoryEventIdTest.cs
  test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
  test/EFCore.Relational.Tests/Migrations/MigrationCommandExecutorTest.cs
  test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs
  test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
  test/EFCore.Relational.Tests/RelationalEventIdTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
  test/EFCore.Relational.Tests/TestUtilities/FakeRelationalCommandDiagnosticsLogger.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.Specification.Tests/TestUtilities/TestLoggerFactory.cs
  test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
  test/EFCore.SqlServer.Tests/SqlServerEventIdTest.cs
  test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
  test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
  test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs
  test/EFCore.Tests/Infrastructure/EventIdTestBase.cs
Labels: auto-merge

#24675 Query: Introduce client projections in SelectExpression
  src/EFCore.Relational/Query/CollectionResultExpression.cs
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalCollectionShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSplitCollectionShaperExpression.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyFieldsLoadSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindStringIncludeQuerySqliteTest.cs
Labels: auto-merge, providers-beware

#24676 Query: Push down into subquery when group by has unallowed terms
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Labels: auto-merge

#24701 Relational: Make table reference graph mapping consistent
  src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: auto-merge

#24702 Improve test coverage fo DateTimeOffset comparer
  test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
Labels: auto-merge

#24715 Query: Lift projections from single result query rather than applying…
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindStringIncludeQuerySqliteTest.cs
Labels: auto-merge

#24732 Add a test for #23059
  test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
  test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
Labels: auto-merge

#24734 Add regression test for #22223
  test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
Labels: auto-merge

#24735 Add regression test for #19584
  test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationshipsQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
Labels: auto-merge

#24706 Relational: Implement split query for non-include collections
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/SplitIncludeRewritingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPreprocessor.cs
  src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
  src/EFCore/Query/MaterializeCollectionNavigationExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSplitQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSplitSharedQueryTypeRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
Labels: auto-merge

#24737 Create a provider agnostic test base to put custom models
  test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/OwnedEntityQuerySqliteTest.cs
Labels: auto-merge, providers-beware

#24753 Merge conditional ?: expression into conditional access
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqlitePropertyExtensions.cs
Labels: auto-merge

#24772 [SMALL] Adding tests for #24726 - Bug with Take()
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
Labels: auto-merge

#24781 Preview 4: Copy instead of reusing the same reference in AnnotatableBase.AddAnnotations
  src/EFCore/Infrastructure/AnnotatableBase.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
  test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
Labels: Servicing-approved

#24755 Optimize using StringBuilder
  src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggerExtensions.cs
  src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
  src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Metadata/ICheckConstraint.cs
  src/EFCore.Relational/Metadata/IColumn.cs
  src/EFCore.Relational/Metadata/IColumnMapping.cs
  src/EFCore.Relational/Metadata/IForeignKeyConstraint.cs
  src/EFCore.Relational/Metadata/IFunctionColumn.cs
  src/EFCore.Relational/Metadata/IReadOnlyDbFunction.cs
  src/EFCore.Relational/Metadata/IReadOnlyDbFunctionParameter.cs
  src/EFCore.Relational/Metadata/IReadOnlySequence.cs
  src/EFCore.Relational/Metadata/IRelationalModel.cs
  src/EFCore.Relational/Metadata/ISqlQuery.cs
  src/EFCore.Relational/Metadata/ISqlQueryColumn.cs
  src/EFCore.Relational/Metadata/IStoreFunction.cs
  src/EFCore.Relational/Metadata/IStoreFunctionParameter.cs
  src/EFCore.Relational/Metadata/ITable.cs
  src/EFCore.Relational/Metadata/ITableIndex.cs
  src/EFCore.Relational/Metadata/IUniqueConstraint.cs
  src/EFCore.Relational/Metadata/IView.cs
  src/EFCore.Relational/Metadata/IViewColumn.cs
  src/EFCore.Relational/Metadata/Internal/DbFunction.cs
  src/EFCore.Relational/Metadata/Internal/Sequence.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Storage/ByteArrayTypeMapping.cs
  src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
  src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/UpdateSqlGenerator.cs
  src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
  src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs
  src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
  src/EFCore/Infrastructure/Uniquifier.cs
  src/EFCore/Metadata/IReadOnlyForeignKey.cs
  src/EFCore/Metadata/IReadOnlyNavigation.cs
  src/EFCore/Metadata/IReadOnlyProperty.cs
  src/EFCore/Metadata/IReadOnlyServiceProperty.cs
  src/EFCore/Metadata/IReadOnlySkipNavigation.cs
  src/dotnet-ef/Exe.cs
Labels: auto-merge

#24790 Query: Avoid pushdown on top level during split query
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#24746 Add translations for string.Substring with one arg
  src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteStringMethodTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
Labels: accepted
