Repository dotnet/efcore, pull requests merged in 2021-01, with the labels that each got.

#23801 Disable SqlServer functional tests on helix ubuntu docker
  eng/helix.proj
Labels: auto-merge

#23800 Fixes to database collation migrations
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
Labels: auto-merge

#23694 Fix unexpected null in principal columns of foreign key
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  src/EFCore.Relational/Migrations/Operations/AddForeignKeyOperation.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
Labels: waiting-for-response

#23823 Fix non-deterministic test
  test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
Labels: auto-merge

#23829 Allow schema-less UDFs to not be built-in
  src/EFCore.Relational/Query/ISqlExpressionFactory.cs
  src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
Labels: auto-merge

#23836 [5.0.3] Fix to #23779 - TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved

#23448 [3.1.x] Query: Cosmos: Generate enum literal/parameter correctly
  src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
  test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
  test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
Labels: Servicing-approved, blocked

#23852 [5.0.3] Don't generate Fluent API in model snapshot for certain annotations
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#23826 [5.0.3] Fix event counter issues and add test patterns for event source testing
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/DbContext.cs
  src/EFCore/Infrastructure/EntityFrameworkEventSource.cs
  src/EFCore/Storage/ExecutionStrategy.cs
  test/EFCore.Tests/EventSourceTest.cs
  test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
Labels: Servicing-approved

#23818 [5.0.3] InMemory: Skip over AsSingleQuery method
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
Labels: Servicing-approved

#23809 [5.0.3] Fixes to database collation migrations
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
Labels: Servicing-approved, blocked

#23808 [5.0.3] Set skip navigations in delayed fixup
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
Labels: Servicing-approved, blocked

#23614 [5.0.3] Flow through the column types in MigrationBuilder.InsertData
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#23692 [5.0.3] Use IUpdateEntry.EntityState instead of ModificationCommand.EntityState for entities using table splitting.
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
Labels: Servicing-approved

#23697 [5.0.3] Add column name null checks in default FK and PK name calculation
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: Servicing-approved

#23624 [5.0.3] InMemory: Decompose join condition which uses equals for comparison
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Labels: Servicing-approved

#23815 [5.0.3] Set relationship snapshot correctly for skip navigations
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Labels: Servicing-approved

#23874 [release/5.0] Update to 1.0.2 SDK
  global.json
Labels: area-infrastructure, tell-mode

#23881 Fix capturing uses of NonCapturingLazyInitializer
  src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore/ChangeTracking/ValueComparer`.cs
  src/EFCore/Internal/InternalDbSet.cs
  src/EFCore/Metadata/INavigation.cs
  src/EFCore/Metadata/INavigationBase.cs
  src/EFCore/Metadata/ISkipNavigation.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/Index.cs
  src/EFCore/Metadata/Internal/Key.cs
  src/EFCore/Metadata/Internal/Navigation.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Metadata/Internal/SkipNavigation.cs
  src/EFCore/Metadata/ServiceParameterBinding.cs
  src/EFCore/Query/Internal/CompiledQueryBase.cs
  src/EFCore/Storage/CoreTypeMapping.cs
  src/EFCore/Storage/ValueConversion/ValueConverter`.cs
  src/Shared/NonCapturingLazyInitializer.cs
Labels: auto-merge

#23904 Support for SQL Server sparse columns
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
  test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Labels: auto-merge

#23975 [small] Fix migration dependencies
  src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
  test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
Labels: auto-merge

#23873 Add support for three and four string argument versions of System.String.Concat
  src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
  src/EFCore.Relational/Query/Internal/StringMethodTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
  test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
  test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
Labels: auto-merge

#23986 Update branding to 6.0.0-preview2
  eng/Versions.props
Labels: area-infrastructure

#23987 Update branding to 6.0.0-preview1
  eng/Versions.props
Labels: area-infrastructure, tell-mode
