Repository dotnet/efcore, pull requests merged in 2021-06, with the labels that each got.

#25015 [release/5.0] Update branding to v5.0.8
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#24944 [5.0.x] SqlServer: Add Cast to (n)varchar(max) when injecting Concat for multi-line seed data
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerStringTypeMappingTest.cs
Labels: Servicing-approved

#25034 Don't remove default table mapping for TVF return entity types.
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/TableValuedDbFunctionConvention.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/Internal/TableValuedDbFunctionConventionTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: auto-merge

#25070 Target .NET 6.0
  docs/getting-and-building-the-code.md
  src/EFCore.Abstractions/EFCore.Abstractions.csproj
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  src/EFCore.Design/EFCore.Design.csproj
  src/EFCore.Design/build/net6.0/Microsoft.EntityFrameworkCore.Design.props
  src/EFCore.InMemory/EFCore.InMemory.csproj
  src/EFCore.Proxies/EFCore.Proxies.csproj
  src/EFCore.Relational/EFCore.Relational.csproj
  src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
  src/EFCore.SqlServer.NTS/build/net6.0/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite.targets
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
  src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
  src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
  src/EFCore.Sqlite.NTS/build/net6.0/Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite.targets
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/EFCore.Sqlite/lib/net6.0/_._
  src/EFCore.Tools/lib/net6.0/_._
  src/EFCore/EFCore.csproj
  src/EFCore/Query/QueryableMethods.cs
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/dotnet-ef/dotnet-ef.csproj
Labels: providers-beware

#25057 Revert to Microsoft.Data.SqlClient 2.x
  .github/dependabot.yml
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: auto-merge

#25085 Add support for `InfiniteTimeSpan` in `SetCommandTimeout`.
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  test/EFCore.SqlServer.Tests/CommandConfigurationTests.cs
Labels: waiting-for-response

#25102 Test fixup
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: auto-merge

#25094 Make IScaffoldingModelFactory public
  src/EFCore.Design/Scaffolding/IScaffoldingModelFactory.cs
  src/EFCore.Design/Scaffolding/Internal/IScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalDatabaseModelFactoryTest.cs
Labels: auto-merge

#25104 Rebrand for 6.0.0-preview7
  eng/Versions.props
Labels: area-infrastructure

#25105 Update to .NET SDK 6.0.100-preview.5
  eng/Version.Details.xml
  global.json
Labels: auto-merge

#25125 Correct nullability of DbSet.Find
  src/EFCore/DbSet.cs
Labels: auto-merge

#25155 [release/6.0-preview6] Unpin Microsoft.Extensions.Logging
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: auto-merge

#24819 Fix table casing to be the expected default (Pascal casing)
  test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorDisabledRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorEnabledRelationalTestBase.cs
Labels: waiting-for-response

#25173 Bump NetTopologySuite from 2.1.0 to 2.3.0
  src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
  src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
  test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyFixture.cs
Labels: auto-merge
