Repository dotnet/efcore, pull requests merged in 2021-05, with the labels that each got.

#24407 Start flowing Microsoft.NETCore.App
  Directory.Build.targets
  eng/Version.Details.xml
  eng/Versions.props
  eng/helix.proj
  global.json
Labels: auto-merge

#24836 [release/5.0] Update branding to v5.0.7
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#24785 [release/5.0] Move cosmos testing to internal
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#24784 [release/3.1] Move cosmos testing to internal
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#24906 Add commands to create compiled models
  src/EFCore.Design/Design/DbContextActivator.cs
  src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
  src/EFCore.Design/Design/Internal/DbContextOperations.cs
  src/EFCore.Design/Design/Internal/MigrationsOperations.cs
  src/EFCore.Design/Design/OperationExecutor.cs
  src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.Design/Scaffolding/CompiledModelCodeGenerationOptions.cs
  src/EFCore.Design/Scaffolding/ICompiledModelScaffolder.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CompiledModelScaffolder.cs
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  src/EFCore.Tools/EFCore.Tools.csproj
  src/EFCore.Tools/EntityFrameworkCore.psd1.in
  src/EFCore.Tools/tools/EntityFrameworkCore.psm1
  src/EFCore.Tools/tools/about_EntityFrameworkCore.help.txt
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Infrastructure/ModelRuntimeInitializer.cs
  src/EFCore/Infrastructure/ModelSource.cs
  src/EFCore/Internal/DbContextServices.cs
  src/EFCore/Internal/IDbContextServices.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/RuntimeModel.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/dotnet-ef/Properties/Resources.Designer.cs
  src/dotnet-ef/Properties/Resources.resx
  src/ef/Commands/DbContextCommand.cs
  src/ef/Commands/DbContextOptimizeCommand.Configure.cs
  src/ef/Commands/DbContextOptimizeCommand.cs
  src/ef/IOperationExecutor.cs
  src/ef/OperationExecutorBase.cs
  src/ef/Properties/Resources.Designer.cs
  src/ef/Properties/Resources.resx
  test/EFCore.Design.Tests/Design/DesignTimeServicesTest.cs
  test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
  test/EFCore.Design.Tests/TestUtilities/TestDbContextOperations.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsInfrastructureTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
  test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelSourceTest.cs
Labels: auto-merge

#24941 Update branding to 6.0.0-preview6
  eng/Versions.props
Labels: area-infrastructure

#24951 Code Cleanup
  src/EFCore/Query/ExpressionPrinter.cs
  src/ef/CommandLineUtils/CommandLineApplication.cs
  test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTests.cs
  test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTests.cs
  test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
Labels: auto-merge
