Repository dotnet/efcore, pull requests merged in 2021-07, with the labels that each got.

#25209 Rebrand for v5.0.9
  eng/Versions.props
Labels: area-infrastructure

#25175 [release/5.0] Preserve the null table mapping in migration snapshot when an entity type is used as a TVF return type.
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#25176 [release/5.0] Fix missing code generation output for custom data annotation attributes
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
Labels: Servicing-approved

#25269 Update branding to 6.0.0-rc1
  eng/Versions.props
Labels: area-infrastructure

#25283 Default relationships to ownership for Cosmos
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosInversePropertyAttributeConvention.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosRelationshipDiscoveryConvention.cs
  src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
  src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
  src/EFCore.Cosmos/Metadata/Internal/CosmosEntityTypeExtensions.cs
  src/EFCore.Relational/Metadata/IColumn.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
  src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/IConventionModel.cs
  src/EFCore/Metadata/IModel.cs
  src/EFCore/Metadata/IMutableModel.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
  src/EFCore/Metadata/Internal/Model.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
  test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
  test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: breaking-change

#25313 Store options in ServiceProviderCache
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
  src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
  src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
  src/EFCore.SqlServer.NTS/Infrastructure/Internal/SqlServerNetTopologySuiteOptionsExtension.cs
  src/EFCore.Sqlite.NTS/Infrastructure/Internal/SqliteNetTopologySuiteOptionsExtension.cs
  src/EFCore/DbContextOptions.cs
  src/EFCore/DbContextOptions`.cs
  src/EFCore/Diagnostics/WarningsConfiguration.cs
  src/EFCore/Infrastructure/CoreOptionsExtension.cs
  src/EFCore/Infrastructure/DbContextOptionsExtensionInfo.cs
  src/EFCore/Internal/ServiceProviderCache.cs
  test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
  test/EFCore.Relational.Tests/RelationalConnectionTest.cs
  test/EFCore.Specification.Tests/LoggingTestBase.cs
  test/EFCore.Tests/DbContextOptionsTest.cs
  test/EFCore.Tests/ServiceProviderCacheTest.cs
Labels: providers-beware

#25220 Add IServiceCollection.Use[DbProviderName]<DbContext> extension methods
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
  test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
  test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
Labels: providers-beware

#25344 Cosmos: Add basic support for collections and dictionaries of primitive types
  src/EFCore.Cosmos/ChangeTracking/Internal/ListComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableEqualityComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableSingleDimensionalArrayComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/NullableStringDictionaryComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
  src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosInversePropertyAttributeConvention.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosRelationshipDiscoveryConvention.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
  src/EFCore/Storage/CoreTypeMapping.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
Labels: auto-merge

#25294 Make CSharpRuntimeAnnotationCodeGenerator and friends internal
  src/EFCore.InMemory/Design/Internal/InMemoryCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.InMemory/Design/Internal/InMemoryDesignTimeServices.cs
  src/EFCore.Relational/Design/EntityFrameworkRelationalDesignServicesBuilder.cs
  src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies.cs
  src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs
  src/EFCore.Sqlite.Core/Design/Internal/SqliteCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.Sqlite.Core/Design/Internal/SqliteDesignTimeServices.cs
  src/EFCore/Design/EntityFrameworkDesignServicesBuilder.cs
  src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGeneratorDependencies.cs
  src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGeneratorParameters.cs
  src/EFCore/Design/Internal/ICSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore/Diagnostics/UpdateEntryEventData.cs
  test/EFCore.Cosmos.FunctionalTests/CosmosApiConsistencyTest.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
Labels: auto-merge

#25238 Drop computed columns before non-computed
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Labels: auto-merge
