Repository dotnet/efcore, pull requests merged in 2021-02, with the labels that each got.

#23984 [release/5.0] InMemory: Allow UnaryExpression.Operand to be converted to nullable for LeftJoin
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Labels: Servicing-approved

#23983 Correctly set pool size when using AddPooledDbContextFactory
  src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: Servicing-approved

#24117 Re-enable SqlServer on helix
  eng/helix.proj
Labels: auto-merge

#24132 Reference Web SDK in OData test project since we need MVC references
  test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
Labels: auto-merge

#24147 Added DbUpdateException constructors that accept list of EntityEntry for Entries property
  src/EFCore/DbUpdateException.cs
  test/EFCore.Tests/ExceptionTest.cs
Labels: waiting-for-response

#24224 [main] Clear disabled package sources
  NuGet.config
Labels: area-infrastructure

#24227 Update branding to 6.0.0-preview3
  eng/Versions.props
Labels: area-infrastructure

#24226 Tools: Annotate NRTs
  src/EFCore.Design/Design/IOperationResultHandler.cs
  src/EFCore.Design/Design/OperationReportHandler.cs
  src/EFCore.Design/Design/OperationResultHandler.cs
  src/dotnet-ef/Exe.cs
  src/dotnet-ef/Project.cs
  src/dotnet-ef/ProjectOptions.cs
  src/dotnet-ef/RootCommand.cs
  src/dotnet-ef/dotnet-ef.csproj
  src/ef/AnsiConsole.cs
  src/ef/AnsiTextWriter.cs
  src/ef/AppDomainOperationExecutor.cs
  src/ef/CommandLineUtils/CommandArgument.cs
  src/ef/CommandLineUtils/CommandLineApplication.cs
  src/ef/CommandLineUtils/CommandLineApplicationExtensions.cs
  src/ef/CommandLineUtils/CommandOption.cs
  src/ef/Commands/ContextCommandBase.cs
  src/ef/Commands/DatabaseDropCommand.Configure.cs
  src/ef/Commands/DatabaseDropCommand.cs
  src/ef/Commands/DatabaseUpdateCommand.Configure.cs
  src/ef/Commands/DatabaseUpdateCommand.cs
  src/ef/Commands/DbContextInfoCommand.Configure.cs
  src/ef/Commands/DbContextInfoCommand.cs
  src/ef/Commands/DbContextListCommand.Configure.cs
  src/ef/Commands/DbContextListCommand.cs
  src/ef/Commands/DbContextScaffoldCommand.Configure.cs
  src/ef/Commands/DbContextScaffoldCommand.cs
  src/ef/Commands/DbContextScriptCommand.Configure.cs
  src/ef/Commands/DbContextScriptCommand.cs
  src/ef/Commands/HelpCommandBase.cs
  src/ef/Commands/MigrationsAddCommand.Configure.cs
  src/ef/Commands/MigrationsAddCommand.cs
  src/ef/Commands/MigrationsListCommand.Configure.cs
  src/ef/Commands/MigrationsListCommand.cs
  src/ef/Commands/MigrationsRemoveCommand.Configure.cs
  src/ef/Commands/MigrationsRemoveCommand.cs
  src/ef/Commands/MigrationsScriptCommand.Configure.cs
  src/ef/Commands/MigrationsScriptCommand.cs
  src/ef/Commands/ProjectCommandBase.cs
  src/ef/Commands/RootCommand.cs
  src/ef/IOperationExecutor.cs
  src/ef/Json.cs
  src/ef/NotNullIfNotNullAttribute.cs
  src/ef/OperationExecutorBase.cs
  src/ef/ReflectionOperationExecutor.cs
  src/ef/Reporter.cs
  src/ef/ef.csproj
Labels: auto-merge

#23437 Keep parameter names for inlined queries
  src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: auto-merge

#24209 Allow providers to override ambient transaction access
  src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.Relational/Update/Internal/BatchExecutor.cs
  src/EFCore/Storage/ExecutionStrategy.cs
  src/EFCore/Storage/ITransactionEnlistmentManager.cs
Labels: auto-merge

#24262 Unbreak API used by Scaffolding
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
  src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
  src/EFCore/Extensions/EntityTypeExtensions.cs
  src/EFCore/Extensions/ModelExtensions.cs
  src/EFCore/Extensions/MutableEntityTypeExtensions.cs
  src/EFCore/Extensions/NavigationExtensions.cs
  src/EFCore/Extensions/PropertyBaseExtensions.cs
  src/EFCore/Extensions/PropertyExtensions.cs
  test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
  test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
Labels: auto-merge
