Repository dotnet/efcore, pull requests merged in 2021-03, with the labels that each got.

#24306 Scaffolding: Annotate NRTs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Design/AnnotationCodeGeneratorDependencies.cs
  src/EFCore.Relational/Design/AttributeCodeFragment.cs
  src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
  src/EFCore.Relational/Design/MethodCallCodeFragment.cs
  src/EFCore.Relational/Design/NestedClosureCodeFragment.cs
  src/EFCore.Relational/Scaffolding/DatabaseModelFactory.cs
  src/EFCore.Relational/Scaffolding/DatabaseModelFactoryOptions.cs
  src/EFCore.Relational/Scaffolding/IDatabaseModelFactory.cs
  src/EFCore.Relational/Scaffolding/IProviderCodeGeneratorPlugin.cs
  src/EFCore.Relational/Scaffolding/IProviderConfigurationCodeGenerator.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseColumn.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseForeignKey.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseIndex.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseModel.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabasePrimaryKey.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseSequence.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseTable.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseUniqueConstraint.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseView.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGenerator.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorDependencies.cs
  src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorPlugin.cs
  src/EFCore.SqlServer.NTS/Design/Internal/SqlServerNetTopologySuiteDesignTimeServices.cs
  src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteDbContextOptionsBuilderExtensions.cs
  src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.SqlServer.NTS/Infrastructure/Internal/SqlServerNetTopologySuiteOptionsExtension.cs
  src/EFCore.SqlServer.NTS/Scaffolding/Internal/SqlServerNetTopologySuiteCodeGeneratorPlugin.cs
  src/EFCore.SqlServer.NTS/Storage/ValueConversion/Internal/GeometryValueConverter.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore.Sqlite.Core/Design/Internal/SqliteDesignTimeServices.cs
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteCodeGenerator.cs
  src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
  src/EFCore.Sqlite.NTS/Design/Internal/SqliteNetTopologySuiteDesignTimeServices.cs
  src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteDbContextOptionsBuilderExtensions.cs
  src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.Sqlite.NTS/Infrastructure/Internal/SqliteNetTopologySuiteOptionsExtension.cs
  src/EFCore.Sqlite.NTS/Scaffolding/Internal/SqliteNetTopologySuiteCodeGeneratorPlugin.cs
  src/EFCore.Sqlite.NTS/Storage/ValueConversion/Internal/GeometryValueConverter.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
Labels: auto-merge

#24350 Remove bad DebugAssert causing a stack overflow
  src/EFCore.Relational/Update/ColumnModification.cs
Labels: auto-merge

#24357 [release/5.0] Update SDK and runtime versions
  global.json
Labels: area-infrastructure, tell-mode

#24240 [release/3.1] Clear disabled package sources
  NuGet.config
Labels: area-infrastructure, tell-mode

#24241 [release/5.0] Clear disabled package sources
  NuGet.config
Labels: area-infrastructure, tell-mode

#24115 [release/3.1] Query: Use stronger reflection in Queryable/Enumerable methods (#24090)
  src/EFCore/Query/QueryableMethods.cs
  src/Shared/EnumerableMethods.cs
Labels: Servicing-approved

#24362 Add missing design-time services
  src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs
  src/EFCore.SqlServer/Properties/AssemblyInfo.cs
  src/EFCore.Sqlite.Core/Design/Internal/SqliteDesignTimeServices.cs
  src/EFCore.Sqlite.Core/Properties/AssemblyInfo.cs
  test/EFCore.Relational.Specification.Tests/DesignTimeTestBase.cs
  test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
  test/EFCore.SqlServer.FunctionalTests/DesignTimeSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
  test/EFCore.Sqlite.FunctionalTests/DesignTimeSqliteTest.cs
Labels: auto-merge

#24116 [release/5.0] Query: Use stronger reflection in Queryable/Enumerable methods
  src/EFCore/Query/QueryableMethods.cs
  src/Shared/EnumerableMethods.cs
Labels: Servicing-approved

#24178 [5.0.x] Don't leave unknown FK values when principal is known but has not-set, non-generated, value
  src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
  test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Labels: Servicing-approved

#24244 [release/5.0] Don't compare values from different keys for deleted entities
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Labels: Servicing-approved

#24372 InMemory: Preserve type to bool when applying predicate on a grouping
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/NorthwindGroupByQueryInMemoryTest.cs
Labels: auto-merge

#24225 [release/5.0] Warn for walking back up the Include tree
  src/EFCore/Diagnostics/CoreEventId.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/LoggingDefinitions.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: Servicing-approved

#24405 Update .NET SDK to 6.0.100-preview.2.21155.3
  benchmark/EFCore.Benchmarks/EFCore.Benchmarks.csproj
  benchmark/EFCore.SqlServer.Benchmarks/EFCore.SqlServer.Benchmarks.csproj
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  eng/helix.proj
  global.json
  test/EFCore.Analyzers.Tests/EFCore.Analyzers.Tests.csproj
  test/EFCore.AspNet.InMemory.FunctionalTests/EFCore.AspNet.InMemory.FunctionalTests.csproj
  test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
  test/EFCore.AspNet.SqlServer.FunctionalTests/EFCore.AspNet.SqlServer.FunctionalTests.csproj
  test/EFCore.AspNet.Sqlite.FunctionalTests/EFCore.AspNet.Sqlite.FunctionalTests.csproj
  test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
  test/EFCore.Cosmos.Tests/EFCore.Cosmos.Tests.csproj
  test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj
  test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
  test/EFCore.Design.Tests/xunit.runner.json
  test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj
  test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj
  test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
  test/EFCore.Proxies.Tests/EFCore.Proxies.Tests.csproj
  test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
  test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
  test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
  test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
  test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj
  test/EFCore.Tests/EFCore.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
  test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
  test/ef.Tests/ef.Tests.csproj
  test/xunit.runner.json
Labels: auto-merge

#24437 Obsolete MemberIdentity.IsNone()
  src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
  src/EFCore/Metadata/MemberIdentity.cs
Labels: auto-merge

#24436 Query: Re-organize SelectExpression
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Labels: auto-merge

#24484 Update branding to 6.0.0-preview4
  eng/Versions.props
Labels: area-infrastructure

#24486 Update explicit throw for navigation ignored warning
  src/EFCore/Infrastructure/CoreOptionsExtension.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#24498 Default options on ToDebugString
  src/EFCore.Relational/Metadata/ICheckConstraint.cs
  src/EFCore.Relational/Metadata/IColumn.cs
  src/EFCore.Relational/Metadata/IColumnMapping.cs
  src/EFCore.Relational/Metadata/IForeignKeyConstraint.cs
  src/EFCore.Relational/Metadata/IFunctionColumn.cs
  src/EFCore.Relational/Metadata/IFunctionColumnMapping.cs
  src/EFCore.Relational/Metadata/IFunctionMapping.cs
  src/EFCore.Relational/Metadata/IReadOnlyDbFunction.cs
  src/EFCore.Relational/Metadata/IReadOnlyDbFunctionParameter.cs
  src/EFCore.Relational/Metadata/IReadOnlySequence.cs
  src/EFCore.Relational/Metadata/IRelationalModel.cs
  src/EFCore.Relational/Metadata/ISqlQuery.cs
  src/EFCore.Relational/Metadata/ISqlQueryColumn.cs
  src/EFCore.Relational/Metadata/ISqlQueryColumnMapping.cs
  src/EFCore.Relational/Metadata/ISqlQueryMapping.cs
  src/EFCore.Relational/Metadata/IStoreFunction.cs
  src/EFCore.Relational/Metadata/IStoreFunctionParameter.cs
  src/EFCore.Relational/Metadata/ITable.cs
  src/EFCore.Relational/Metadata/ITableIndex.cs
  src/EFCore.Relational/Metadata/ITableMapping.cs
  src/EFCore.Relational/Metadata/IUniqueConstraint.cs
  src/EFCore.Relational/Metadata/IView.cs
  src/EFCore.Relational/Metadata/IViewColumn.cs
  src/EFCore.Relational/Metadata/IViewColumnMapping.cs
  src/EFCore.Relational/Metadata/IViewMapping.cs
  src/EFCore/ChangeTracking/ChangeTrackerExtensions.cs
  src/EFCore/Metadata/IReadOnlyEntityType.cs
  src/EFCore/Metadata/IReadOnlyForeignKey.cs
  src/EFCore/Metadata/IReadOnlyIndex.cs
  src/EFCore/Metadata/IReadOnlyKey.cs
  src/EFCore/Metadata/IReadOnlyModel.cs
  src/EFCore/Metadata/IReadOnlyNavigation.cs
  src/EFCore/Metadata/IReadOnlyProperty.cs
  src/EFCore/Metadata/IReadOnlyServiceProperty.cs
  src/EFCore/Metadata/IReadOnlySkipNavigation.cs
  src/EFCore/Metadata/Internal/PropertyExtensions.cs
  src/EFCore/Update/UpdateEntryExtensions.cs
Labels: community-contribution

#24477 Query: Add regression tests for correlated collection and GroupBy/Distinct
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableReferenceExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Labels: auto-merge

#24503 Microsoft.Data.Sqlite: Add Span overloads to SqliteBlob
  src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
Labels: auto-merge
