Repository dotnet/efcore, pull requests merged in 2022-08, with the labels that each got.

#28572 Update branding to 3.1.29
  eng/Versions.props
Labels: area-infrastructure, tell-mode, auto-merge

#28575 Update branding to 6.0.9
  eng/Versions.props
Labels: area-infrastructure, tell-mode, auto-merge

#28382 Fix scaffolding of reference navigations with NRT (#27616)
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#28590 Tests: Skip SQLite tests when no column metadata APIs
  test/Microsoft.Data.Sqlite.Tests/TestUtilities/SqliteTestFramework.cs
Labels: auto-merge

#28597 Query: Split databases for filter/non-filter cases for bulk updates
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerFixture.cs
Labels: auto-merge

#28576 [release/6.0] Add more cast nodes in multi-line breaks during migrations
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#28599 Update helix.proj for local runs
  eng/helix.proj
Labels: auto-merge

#28582 Query: Introduce QuerySqlGenerator.GenerateRootCommand as interceptio…
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
Labels: auto-merge

#28583 BulkUpdates: Add custom CommandSource and exception messages
  src/EFCore.Relational/Diagnostics/CommandSource.cs
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/NonQueryExpression.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
Labels: auto-merge

#28601 Add sugar methods to ConventionSet
  src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
  src/EFCore.InMemory/Metadata/Conventions/InMemoryConventionSetBuilder.cs
  src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteConventionSetBuilder.cs
  src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
  src/EFCore/Metadata/Conventions/NavigationBackingFieldAttributeConvention.cs
  src/EFCore/Metadata/Conventions/RequiredNavigationAttributeConvention.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionSetBuilderTests.cs
Labels: providers-beware, auto-merge

#28608 Query: Use object.Equals rather than Expression.Equal when constructi…
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/ChangeTracking/ValueComparer.cs
  src/EFCore/ChangeTracking/ValueComparer`.cs
  src/EFCore/Extensions/Internal/ExpressionExtensions.cs
  src/EFCore/Infrastructure/ExpressionExtensions.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindAggregateOperatorsQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
Labels: auto-merge

#28635 Merging internal commits for release/6.0
  global.json
Labels: tell-mode

#28630 Move table configuration methods to (OwnedNavigation)TableBuilder
  src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
  src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
  src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Builders/OwnedNavigationTableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/OwnedNavigationTableBuilder``.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder`.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
  src/EFCore.Relational/Metadata/IConventionStoredProcedure.cs
  src/EFCore.Relational/Metadata/IMutableStoredProcedure.cs
  src/EFCore.Relational/Metadata/IReadOnlyStoredProcedure.cs
  src/EFCore.Relational/Metadata/IStoreStoredProcedure.cs
  src/EFCore.Relational/Metadata/IStoreStoredProcedureReturnValue.cs
  src/EFCore.Relational/Metadata/Internal/InternalStoredProcedureBuilder.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore.Relational/Metadata/Internal/StoreStoredProcedure.cs
  src/EFCore.Relational/Metadata/Internal/StoreStoredProcedureReturnValue.cs
  src/EFCore.Relational/Metadata/Internal/StoredProcedure.cs
  src/EFCore.Relational/Metadata/RuntimeStoredProcedure.cs
  src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerTableBuilderExtensions.cs
  src/EFCore/Metadata/Builders/ConventionSetBuilder.cs
  src/EFCore/ModelConfigurationBuilder.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
  test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
  test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
  test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
  test/EFCore.SqlServer.FunctionalTests/MemoryOptimizedTablesTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerMemoryOptimizedTablesConventionTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerTestModelBuilderExtensions.cs
Labels: auto-merge

#28636 Merging internal commits for release/3.1
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure, tell-mode

#28649 Bump .NET SDK from 7.0.100-preview.6.22352.1 to 7.0.100-preview.7.22377.5
  global.json
  test/EFCore.Trimming.Tests/EFCore.Trimming.Tests.csproj
Labels: area-infrastructure, auto-merge, type-dependency update :arrow_up_small:

#28658 Fix Cosmos test on CI
  test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
Labels: auto-merge

#28626 Implement ExecuteUpdate
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/Internal/SelectExpressionPruningExpressionVisitor.cs
  src/EFCore.Relational/Query/NonQueryExpression.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Relational/Query/SetPropertyStatements.cs
  src/EFCore.Relational/Query/SqlExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/CaseWhenClause.cs
  src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SetColumnValue.cs
  src/EFCore.Relational/Query/SqlExpressions/UpdateExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/ShapedQueryExpression.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/BulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/FiltersInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPCInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/BulkUpdatesAsserter.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/TableSplittingSqliteTest.cs
Labels: auto-merge

#28659 Clean up build configuration
  NuGet.config
  azure-pipelines.yml
Labels: auto-merge

#28677 Add FromSql/ExecuteSql/ExecuteSqlAsync
  src/EFCore.Relational/Diagnostics/CommandSource.cs
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
  test/EFCore.CrossStore.FunctionalTests/QueryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPCInheritanceQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Labels: auto-merge

#28678 Add Microsoft.EntityFrameworkCore.Templates
  All.sln
  EFCore.Tools.slnf
  src/EFCore.Templates/EFCore.Templates.csproj
  src/EFCore.Templates/templates/ef-templates/.template.config/template.json
Labels: auto-merge

#28657 Exception message review by Shay
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.Json.cs
Labels: auto-merge

#28679 Add immutable annotation support to TableExpressionBase
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/CrossApplyExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/CrossJoinExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/ExceptExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/InnerJoinExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/IntersectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/LeftJoinExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/OuterApplyExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/TableExpressionBase.cs
  src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/UnionExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
Labels: providers-beware, auto-merge

#28699 Don't implement ITableBasedExpression in FromSqlExpression
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Labels: auto-merge

#28713 Fix bugs in SQL Server bulk insert management
  All.sln.DotSettings
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Labels: auto-merge

#28728 API review changes
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Diagnostics/CommandSource.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/ChangeTracking/ValueComparer`.cs
  src/EFCore/Extensions/Internal/ExpressionExtensions.cs
  src/EFCore/Infrastructure/ExpressionExtensions.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
Labels: auto-merge

#28731 ExecuteUpdate: Allow using other tables in the query to generate resu…
  src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
Labels: auto-merge

#28734 Remove unused parameters
  src/EFCore.Relational/Metadata/Builders/IConventionStoredProcedureBuilder.cs
  src/EFCore.Relational/Metadata/Internal/InternalStoredProcedureBuilder.cs
Labels: auto-merge

#28735 Add python script to replace query baselines
  tools/ReplaceQueryBaseline.py
Labels: auto-merge

#28711 Allow users to always use transactions with SaveChanges
  src/EFCore.Relational/Update/Internal/BatchExecutor.cs
  src/EFCore/AutoTransactionBehavior.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/DbContext.cs
  src/EFCore/Infrastructure/DatabaseFacade.cs
  src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
  test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
  test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
Labels: auto-merge

#28732 Update branding to 8.0.0-alpha1
  eng/Versions.props
Labels: blocked

#28750 Validate that an entity type with sproc mapping is mapped to a table
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Labels: tell-mode

#28691 Update branding to 7.0.0-rc2
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#28741 ExecuteUpdate: Convert to join for query with unsupported operations
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitorDependencies.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Labels: auto-merge

#28330 Add support for CSharpHelper for Dictionary literals
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  src/EFCore/Design/ICSharpHelper.cs
  test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Labels: auto-merge

#28753 Uniquify FK and Key constraint names across tables
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
  src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteSharedTableConvention.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
Labels: providers-beware

#28749 Add a custom convention which adds a blank trigger to all tables
  src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/BlankTriggerAddingConvention.cs
  src/EFCore/Extensions/Internal/DbContextExtensions.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/BlankTriggerAddingConventionTest.cs
  test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
Labels: tell-mode

#28764 Merge branch 'release/7.0-rc1' into release/7.0
  src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/BlankTriggerAddingConvention.cs
  src/EFCore/Extensions/Internal/DbContextExtensions.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/BlankTriggerAddingConventionTest.cs
  test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
Labels: type-merge forward :fast_forward:

#28770 Fix typo in aka.ms links
  src/EFCore/ModelBuilder.cs
Labels: auto-merge

#28793 Metadata changes from the API review
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.Relational/Extensions/RelationalTriggerBuilderExtensions.cs
  src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Builders/OwnedNavigationSplitTableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/OwnedNavigationTableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/SplitTableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/StoredProcedureBuilder.cs
  src/EFCore.Relational/Metadata/Builders/StoredProcedureBuilder`.cs
  src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/TableTriggerBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/BlankTriggerAddingConvention.cs
  src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Relational.Tests/Metadata/Conventions/BlankTriggerAddingConventionTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/Metadata/TriggerTest.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
  test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
Labels: tell-mode

#28801 Add scaffolding DatabaseTrigger class
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseTable.cs
  src/EFCore.Relational/Scaffolding/Metadata/DatabaseTrigger.cs
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: auto-merge

#28820 addressing final API review feedback for json columns
  src/EFCore.Relational/Query/JsonQueryExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
Labels: tell-mode

#28830 Remove `EFCore.Relational.Tests` dependency.
  test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
  test/EFCore.Specification.Tests/TestUtilities/MockAssembly.cs
  test/EFCore.Specification.Tests/TestUtilities/MockMethodInfo.cs
Labels: tell-mode

#28833 Query: API review changes
  src/EFCore.Cosmos/Metadata/Conventions/CosmosRuntimeModelConvention.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/Internal/SelectExpressionPruningExpressionVisitor.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SetPropertyCalls.cs
  src/EFCore.Relational/Query/SqlExpressions/ColumnValueSetter.cs
  src/EFCore.Relational/Query/SqlExpressions/UpdateExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerRuntimeModelConvention.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/BulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/BulkUpdatesAsserter.cs
Labels: tell-mode

#28832 Query: Fix for query fails with JSON columns and Include collection
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasic.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasicForCollection.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasicForReference.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Labels: tell-mode

#28797 Query: Update formatting of Update command
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/SqlExpressions/UpdateExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/TableSplittingSqliteTest.cs
Labels: auto-merge

#28850 Fix base parameter index calculation for sprocs
  src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
  test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Labels: auto-merge

#28834 ExecuteUpdate: Correctly identify when we need to cause a subquery join
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Labels: auto-merge

#28859 Query: Cleanup exception message about bulk updates
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
Labels: auto-merge

#28870 Query: Don't simplify Case block when ElseResult exists
  src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
Labels: auto-merge

#28884 Bump SQLitePCLRaw from 2.1.0 to 2.1.1-pre20220822172036
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: area-infrastructure, type-dependency update :arrow_up_small:

#28684 Stop scaffolding DbSet initializers
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/BuildSource.cs
Labels: auto-merge
