Repository dotnet/efcore, pull requests merged in 2022-11, with the labels that each got.

#29466 Update branding to 3.1.32
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29467 Update branding to 6.0.12
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29438 [release/7.0] Add CodeQL3000 run to efcore-ci-official
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29439 [release/6.0] Add CodeQL3000 run to efcore-ci-official
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29470 Update issue templates
  .github/ISSUE_TEMPLATE/ask_a_question.md
  .github/ISSUE_TEMPLATE/bug_report_efcore.md
  .github/ISSUE_TEMPLATE/bug_report_sqlite.md
Labels: auto-merge

#29216 [release/6.0] Query: Use type mapping from IDbFunction while translating (#27995)
  src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
  test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: Servicing-approved

#29435 [release/6.0] Update to SQLitePCLRaw 2.1.2
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: Servicing-approved

#29434 [release/3.1] Update to SQLitePCLRaw 2.1.2
  eng/Versions.props
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
Labels: Servicing-approved

#29440 [release/2.1] Add CodeQL3000 run to efcore-ci-official
  .config/tsaoptions.json
  azure-pipelines.yml
  build/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#29349 ToString() on string columns added
  src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: community-contribution

#29402 Fix to #29365 - Query/Test: convert FromSql tests to use query infra
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
Labels: auto-merge

#29522 Add test for ExecuteUpdate with two inner joins
  src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#29574 [SMALL] Fix to #29572 - Json: predicate on json bool property generates incorrect sql
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Labels: auto-merge

#29571 Make DbUpdateException.Entries contain all entries when we can't populate it
  src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
  test/EFCore.Relational.Specification.Tests/Update/NonSharedModelUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/NonSharedModelUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/NonSharedModelUpdatesSqliteTest.cs
Labels: auto-merge

#29616 Update daily build docs for 8.0
  docs/DailyBuilds.md
Labels: auto-merge

#29650 Use correct parameter in query based on type mapping
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#29590 [release/7.0] Fix SQL Server result mapping for bulk insert (#29565)
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  test/EFCore.Relational.Specification.Tests/Update/NonSharedModelUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
  test/EFCore.SqlServer.FunctionalTests/Update/Issue29502.sql
  test/EFCore.SqlServer.FunctionalTests/Update/NonSharedModelUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/NonSharedModelUpdatesSqliteTest.cs
Labels: Servicing-approved

#29575 [release/6.0] Use simpler Docker tags
  azure-pipelines.yml
  eng/helix.proj
Labels: area-infrastructure, tell-mode

#29576 [release/7.0] Use simpler Docker tags
  azure-pipelines.yml
  eng/helix.proj
Labels: area-infrastructure, tell-mode
