Repository dotnet/efcore, pull requests merged in 2022-02, with the labels that each got.

#27235 [release/3.1] Stop building w/ VS2017 in CI
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#27236 [release/5.0] Stop building w/ VS2017 in CI
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#27238 [release/6.0] Update build and test machines
  azure-pipelines-richnav.yml
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#26794 [release/2.1] Move off expiring machine pools
  Directory.Build.targets
  build/dependencies.props
  build/repo.props
  build/templates/default-build.yml
  korebuild-lock.txt
Labels: area-infrastructure, tell-mode, auto-merge

#27216 [release/6.0] Revert change to delete dependent when optional FK with cascade delete is set to null
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Labels: Servicing-approved

#27190 [release/6.0] Store ApplicationServiceProvider in a WeakReference
  src/EFCore/Internal/ServiceProviderCache.cs
Labels: Servicing-approved

#27231 [release/6.0] RevEng: Don't use nameof syntax (#26622)
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#27284 [release/6.0] Query: Convert single result subquery comparison to null to Any operation
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved

#27302 [release/6.0] Fix to #27072 - Suboptimal SQL generation for query with optional navigation, its collection navigation and lateral join
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
Labels: Servicing-approved

#27292 [release/6.0] Query: Match correct predicate structure to convert apply to join
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Labels: Servicing-approved

#27363 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: auto-merge

#27350 Fix for the optimizer when an entity has a collection property that references itself.
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Labels: community-contribution

#27397 Fix for the optimizer when an entity has a collection property that references itself.
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Labels: Servicing-approved

#27461 Update branding to preview3
  eng/Versions.props
Labels: area-infrastructure
