Repository dotnet/efcore, pull requests merged in 2022-06, with the labels that each got.

#28142 Query: Remove TpcTablesExpression once pruning is done
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/Internal/TpcTablesExpression.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/ExistsExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/ScalarSubqueryExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#28176 Update branding to 6.0.7
  eng/Versions.props
Labels: area-infrastructure, tell-mode, auto-merge

#28198 Query: Improve logic to find column names in TPC
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: auto-merge

#28143 [release/6.0] Query: Don't add grouping key to projection when Distinct is applied
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: Servicing-approved

#28102 Query: Provide a way to translate aggregate methods on top level
  src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitorDependencies.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#28227 Merging internal commits for release/6.0
  global.json
Labels: area-infrastructure, tell-mode

#28230 Update Resources.tt for VS2022
  src/EFCore.Abstractions/EFCore.Abstractions.csproj
  src/EFCore.Abstractions/Properties/AbstractionsStrings.Designer.cs
  src/EFCore.Abstractions/Properties/AbstractionsStrings.Designer.tt
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.tt
  src/EFCore.Design/EFCore.Design.csproj
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.Designer.tt
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.InMemory/EFCore.InMemory.csproj
  src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
  src/EFCore.InMemory/Properties/InMemoryStrings.Designer.tt
  src/EFCore.Proxies/EFCore.Proxies.csproj
  src/EFCore.Proxies/Properties/ProxiesStrings.Designer.tt
  src/EFCore.Relational/EFCore.Relational.csproj
  src/EFCore.Relational/Properties/RelationalStrings.Designer.tt
  src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
  src/EFCore.SqlServer.NTS/Properties/SqlServerNTSStrings.Designer.cs
  src/EFCore.SqlServer.NTS/Properties/SqlServerNTSStrings.Designer.tt
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.tt
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.tt
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
  src/EFCore.Sqlite.NTS/Properties/SqliteNTSStrings.Designer.cs
  src/EFCore.Sqlite.NTS/Properties/SqliteNTSStrings.Designer.tt
  src/EFCore/EFCore.csproj
  src/EFCore/Properties/CoreStrings.Designer.tt
  src/EFCore/Query/Internal/CompiledAsyncEnumerableQuery.cs
  src/EFCore/Query/Internal/CompiledAsyncEnumerableQuery.tt
  src/EFCore/Query/Internal/CompiledAsyncTaskQuery.cs
  src/EFCore/Query/Internal/CompiledAsyncTaskQuery.tt
  src/EFCore/Query/Internal/CompiledQuery.cs
  src/EFCore/Query/Internal/CompiledQuery.tt
  src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
  src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.tt
  src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
  src/dotnet-ef/Properties/Resources.Designer.cs
  src/dotnet-ef/Properties/Resources.Designer.tt
  src/dotnet-ef/Properties/Resources.resx
  src/ef/Properties/Resources.Designer.cs
  src/ef/Properties/Resources.Designer.tt
  src/ef/Properties/Resources.resx
  tools/Resources.tt
  tools/SqliteResources.tt
Labels: auto-merge

#28261 Fixup to Cosmos regex translation
  src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
Labels: auto-merge

#28115 Translate spatial aggregates
  src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
  src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMethodTranslator.cs
  src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
  src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
  src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
  src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/Shared/Check.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/SpatialModel/PointEntity.cs
  test/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Labels: auto-merge

#28289 Update branding to 7.0.0-preview7
  eng/Versions.props
Labels: area-infrastructure

#28212 Add support for CSharpHelper for List literals
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Labels: auto-merge

#28305 Interceptor for DbUpdateConcurrencyException
  src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
  src/EFCore.InMemory/Storage/Internal/IInMemoryTable.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
  src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
  src/EFCore.Relational/Diagnostics/RelationalConcurrencyExceptionEventData.cs
  src/EFCore.Relational/Storage/RelationalDataReader.cs
  src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
  src/EFCore.Relational/Update/ModificationCommandBatchFactoryDependencies.cs
  src/EFCore/ChangeTracking/CollectionEntry.cs
  src/EFCore/ChangeTracking/EntityEntry.cs
  src/EFCore/ChangeTracking/Internal/ArrayPropertyValues.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  src/EFCore/ChangeTracking/ReferenceEntry.cs
  src/EFCore/DbContext.cs
  src/EFCore/Diagnostics/ConcurrencyExceptionEventData.cs
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  src/EFCore/Diagnostics/ISaveChangesInterceptor.cs
  src/EFCore/Diagnostics/UpdateEntryEventData.cs
  src/EFCore/Internal/ManyToManyLoader.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Storage/DatabaseDependencies.cs
  src/EFCore/Update/IUpdateEntry.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
  test/EFCore.Tests/ExceptionTest.cs
  test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs
Labels: providers-beware
