Repository dotnet/efcore, pull requests merged in 2022-09, with the labels that each got.

#28945 Update public pool names
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
Labels: area-infrastructure

#28949 Update public pool names
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
Labels: area-infrastructure, tell-mode

#28958 Take the value converter into account when creating concurrency tokens for table sharing
  src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
Labels: auto-merge

#28959 Don't match explicit implementations for InversePropertyAttribute
  src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
Labels: auto-merge

#28965 Don't skip creating cascade delete on SQL Server when types are base-linking across tables
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqliteTest.cs
Labels: breaking-change

#28970 Remove EF.Default since we are punting for 7.0
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore/EF.cs
  src/EFCore/Infrastructure/MethodInfoExtensions.cs
  src/EFCore/Query/EvaluatableExpressionFilter.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Labels: propose-close

#28957 [release/2.1] Update public pool names
  build/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#28994 [release/7.0] In-build signing for release branches
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29064 Convert to provider values when comparing shared columns
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
  test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Address.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Country.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
  test/EFCore.Specification.Tests/UpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPCTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPTTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
Labels: auto-merge

#29073 Remove old principal key after a value converter is applied
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  src/EFCore.Relational/Metadata/Internal/CheckConstraint.cs
  src/EFCore.Relational/Metadata/Internal/EntityTypeMappingFragment.cs
  src/EFCore.Relational/Metadata/Internal/RelationalPropertyOverrides.cs
  src/EFCore.Relational/Metadata/Internal/StoredProcedureParameter.cs
  src/EFCore.Relational/Metadata/Internal/StoredProcedureResultColumn.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
  src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
  src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
  src/EFCore/Metadata/Internal/ForeignKey.cs
  src/EFCore/Metadata/Internal/Index.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  src/EFCore/Metadata/Internal/Key.cs
  src/EFCore/Metadata/Internal/Navigation.cs
  src/EFCore/Metadata/Internal/Property.cs
  src/EFCore/Metadata/Internal/ServiceProperty.cs
  src/EFCore/Metadata/Internal/SkipNavigation.cs
  src/EFCore/Metadata/Internal/Trigger.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: auto-merge

#29071 Merging internal commits for release/3.1
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure, tell-mode, auto-merge

#29086 Ensure warnings configured to throw really do throw with the SQL Server provider
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  test/EFCore.InMemory.FunctionalTests/LoggingInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
  test/EFCore.Relational.Specification.Tests/LoggingRelationalTestBase.cs
  test/EFCore.Specification.Tests/LoggingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/LoggingSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/LoggingSqliteTest.cs
Labels: providers-beware, breaking-change

#29102 Update versions for 7.0.0 RTM
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29118 Templates: Specify a groupIdentity for ef-templates
  src/EFCore.Templates/templates/ef-templates/.template.config/template.json
Labels: Servicing-approved

#29133 Don't fixup to deleted entities
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Specification.Tests/FieldsOnlyLoadTestBase.cs
  test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseOneToOne.cs
  test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseOneToOneAk.cs
  test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
  test/EFCore.Specification.Tests/LoadTestBase.cs
  test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Labels: Servicing-approved

#29126 [release/7.0] Scaffolding: Don't scaffold HasColumnOrder
  global.json
  src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
Labels: Servicing-approved

#29134 Async fix for "Generate values for PK properties that are also self-referencing FK properties"
  src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
  test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/CosmosConcurrencyTest.cs
  test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
  test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Internal/IdentifierShadowValuePresenceTest.cs
  test/EFCore.Cosmos.FunctionalTests/ReloadTest.cs
  test/EFCore.InMemory.FunctionalTests/CompositeKeyEndToEndTest.cs
  test/EFCore.InMemory.FunctionalTests/DatabaseInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/GuidValueGeneratorEndToEndTest.cs
  test/EFCore.InMemory.FunctionalTests/IntegerGeneratorEndToEndInMemoryTest.cs
  test/EFCore.InMemory.FunctionalTests/ShadowStateUpdateTest.cs
  test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
  test/EFCore.Relational.Tests/Update/BatchExecutorTest.cs
  test/EFCore.Specification.Tests/CompositeKeyEndToEndTestBase.cs
  test/EFCore.Specification.Tests/MusicStoreTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
  test/EFCore.Specification.Tests/WithConstructorsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/EntitySplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/SequentialGuidEndToEndTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
  test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
  test/EFCore.Tests/DbContextTest.cs
  test/EFCore.Tests/EventSourceTest.cs
  test/EFCore.Tests/Storage/ValueConverterTest.cs
Labels: Servicing-approved

#29138 Sproc test fixes around concurrency tokens
  test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Labels: tell-mode

#29145 [release/7.0-rc2] Update to SQLitePCLRaw 2.1.2
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: area-infrastructure, tell-mode, type-dependency update :arrow_up_small:

#29155 Reduce indentation in SqlTranslator
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
Labels: auto-merge

#29160 Update Readme
  README.md
Labels: auto-merge

#29139 Allow specify property value without lambda in ExecuteUpdate
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SetPropertyCalls.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/FiltersInheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Labels: Servicing-approved

#29181 [release/7.0] Reset LocalView when returning context to the pool
  src/EFCore/ChangeTracking/LocalView.cs
  src/EFCore/Internal/InternalDbSet.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: Servicing-approved

#29159 [release/7.0] Move to Ubuntu 22.04 - missed parts
  azure-pipelines.yml
  eng/helix.proj
Labels: area-infrastructure

#29207 Query: Generate condition for table splitting when no required properties
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
Labels: Servicing-consider

#29206 Generate condition for required property in optional dependents
  src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
Labels: Servicing-approved

#29231 Fix result mapping string size in SQL Server string aggregate translator
  src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs
Labels: Servicing-approved
