Repository dotnet/efcore, pull requests merged in 2022-05, with the labels that each got.

#27898 Remove ValueBuffer from update pipeline
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Storage/IRelationalValueBufferFactory.cs
  src/EFCore.Relational/Storage/IRelationalValueBufferFactoryFactory.cs
  src/EFCore.Relational/Storage/Internal/TypedRelationalValueBufferFactory.cs
  src/EFCore.Relational/Storage/RelationalTypeMapping.cs
  src/EFCore.Relational/Storage/RelationalValueBufferFactoryDependencies.cs
  src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
  src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
  src/EFCore.Relational/Update/IReadOnlyModificationCommand.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  src/EFCore.Relational/Update/ModificationCommandBatchFactoryDependencies.cs
  src/EFCore.Relational/Update/ModificationCommandParameters.cs
  src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
  src/EFCore/Diagnostics/ILoggingOptions.cs
  src/EFCore/Diagnostics/Internal/LoggingOptions.cs
  src/EFCore/Query/EvaluatableExpressionFilter.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
  test/EFCore.Relational.Tests/Update/ModificationCommandComparerTest.cs
  test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Labels: auto-merge

#27937 [Typo] Cleanup trailing end tag in documentation
  src/EFCore/Diagnostics/IInterceptorAggregator.cs
Labels: auto-merge

#27941 Update branding to 6.0.6
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#27940 Update branding to 3.1.26
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#27931 Query: Translate aggregate over grouping element in separate pass
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/DistinctExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlEnumerableExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore/Query/GroupByShaperExpression.cs
  src/EFCore/Query/ReplacingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/NorthwindSelectQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
Labels: providers-beware

#27910 [6.0.x] Add [DynamicDependency] on DateOnly/TimeOnly for trimming
  src/EFCore.Relational/Query/IMethodCallTranslator.cs
Labels: Servicing-approved

#27857 [6.0.x] Return null constraint names for keys and FKs on entity types not mapped to a table.
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
  test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Labels: Servicing-approved

#27852 [6.0.x] Reset read count on RelationalDataReader
  src/EFCore.Relational/Storage/RelationalDataReader.cs
  test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
Labels: Servicing-approved

#27994 Bump .NET SDK to 7.0.100-preview.4
  global.json
Labels: area-infrastructure, auto-merge, type-dependency update :arrow_up_small:

#28010 Update SQL baselines
  test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
Labels: auto-merge

#28019 Query: Optimize usage of GetViewOrTableMappings
  src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalTableSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
Labels: auto-merge

#27807 [release/6.0] Tools: Target .NET 6 to improve compatibility with osx-arm64
  src/dotnet-ef/dotnet-ef.csproj
  src/ef/ef.csproj
Labels: Servicing-approved

#28023 Query: API review changes
  src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
  src/EFCore.Relational/Query/EnumerableExpression.cs
  src/EFCore.Relational/Query/RelationalGroupByShaperExpression.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore/Query/GroupByShaperExpression.cs
Labels: auto-merge

#27916 [release/6.0] Force NullabilityInfoContextSupport=true in user projects
  src/EFCore/EFCore.csproj
  src/EFCore/buildTransitive/net6.0/Microsoft.EntityFrameworkCore.props
Labels: Servicing-approved

#28045 Query: Fix some nullability errors
  src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
Labels: auto-merge

#28046 Query: Minor refactoring in shaper
  src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
  src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
Labels: auto-merge

#27630 Attribute for configuring DeleteBehavior
  src/EFCore.Abstractions/DeleteBehavior.cs
  src/EFCore.Abstractions/DeleteBehaviorAttribute.cs
  src/EFCore/Metadata/Conventions/DeleteBehaviorAttributeConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Properties/TypeForwards.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/DeleteBehaviorAttributeConventionTest.cs
  test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
Labels: community-contribution

#28052 SqlServer: Block arithmetic on date/time expressions when type mappin…
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPCGearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
Labels: auto-merge

#28048 Query: Change RelationalCommandCache to allow non-SelectExpression as…
  src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
  src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalParameterBasedSqlProcessor.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
Labels: providers-beware

#28068 Query: Assign correct type/typemapping to result of Round on SqlServer
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
Labels: auto-merge

#28086 Update exception message for optional dependent without identifying p…
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
Labels: auto-merge

#28064 Add more cast nodes in multi-line breaks during migrations
  src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: auto-merge

#28072 Query: Don't add grouping key to projection when Distinct is applied
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: auto-merge

#28087 Update branding to 7.0.0-preview6
  eng/Versions.props
Labels: area-infrastructure

#28063 Query: Use accurate generic types in group join flattening
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Labels: auto-merge

#28099 Query: Remove the requirement that instance or first argument would b…
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/Query/ICompiledQueryCacheKeyGenerator.cs
Labels: auto-merge

#28084 add support for System.Text.Json not including LazyLoader
  src/EFCore.Proxies/Proxies/Internal/IProxyLazyLoader.cs
Labels: community-contribution

#28070 Query: Use GetDiscriminatorValue for TPT and TPC
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/EntityProjectionExpression.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore/Infrastructure/ConventionAnnotatable.cs
  src/EFCore/Infrastructure/ModelValidator.cs
  src/EFCore/Metadata/IConventionAnnotatable.cs
  src/EFCore/Metadata/IConventionEntityType.cs
  src/EFCore/Metadata/IMutableEntityType.cs
  src/EFCore/Metadata/IReadOnlyEntityType.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
  test/EFCore.Tests/Metadata/Conventions/DiscriminatorConventionTest.cs
  test/EFCore.Tests/Metadata/EntityTypeExtensionsTest.cs
  test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
Labels: auto-merge

#28090 Update some NuGet packages
  .github/dependabot.yml
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  rulesets/FxCop.ruleset
  rulesets/FxCop.test.ruleset
  src/Directory.Build.props
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: area-infrastructure, auto-merge, type-dependency update :arrow_up_small:
