Repository dotnet/efcore, pull requests merged in 2022-07, with the labels that each got.

#28348 [release/6.0] Query: Don't add DbParameter if already added
  src/EFCore.Relational/Storage/Internal/RawRelationalParameter.cs
  test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Labels: Servicing-approved

#28394 Implement spatial EnvelopeCombine aggregate translation
  src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
  src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
  src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Labels: auto-merge

#28110 Custom aggregate translations
  src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs
  src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerAggregateFunctionExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerAggregateMethodCallTranslatorProvider.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlExpressionFactory.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerStatisticsAggregateMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteAggregateMethodCallTranslatorProvider.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteStringAggregateMethodTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
Labels: auto-merge

#28410 Make Select_nested_collection_with_groupby have deterministic ordering
  test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
Labels: auto-merge

#28420 Update branding to 7.0.0-rc1
  eng/Versions.props
Labels: area-infrastructure

#28425 Query: Entity splitting support for regular entities
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/EntitySplittingContext.cs
  test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/SplitEntityData.cs
  test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/SplitEntityOne.cs
  test/EFCore.SqlServer.FunctionalTests/EntitySplittingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteFixture.cs
  test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteTest.cs
Labels: auto-merge

#28460 Allow null connection string to be passed to UseProvider methods
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
  test/EFCore.Relational.Specification.Tests/TwoDatabasesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/TwoDatabasesSqlServerTest.cs
  test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
  test/EFCore.Sqlite.FunctionalTests/TwoDatabasesSqliteTest.cs
  test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
Labels: providers-beware

#28473 Update broken links
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Metadata/ISqlQuery.cs
  src/EFCore.Relational/Metadata/ISqlQueryColumn.cs
  src/EFCore.Relational/Metadata/ISqlQueryColumnMapping.cs
  src/EFCore.Relational/Metadata/ISqlQueryMapping.cs
Labels: auto-merge

#28491 Query: Allow materializing owned entities with no required properties
  src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
Labels: auto-merge

#28472 Query: Add support for non entity query roots
  src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/FromSqlQueryRootExpression.cs
  src/EFCore.InMemory/Metadata/Conventions/DefiningQueryRewritingConvention.cs
  src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
  src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
  src/EFCore.Relational/Query/Internal/TableValuedFunctionQueryRootExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbSetExtensions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs
  src/EFCore.SqlServer/Query/Internal/TemporalAllQueryRootExpression.cs
  src/EFCore.SqlServer/Query/Internal/TemporalAsOfQueryRootExpression.cs
  src/EFCore.SqlServer/Query/Internal/TemporalBetweenQueryRootExpression.cs
  src/EFCore.SqlServer/Query/Internal/TemporalContainedInQueryRootExpression.cs
  src/EFCore.SqlServer/Query/Internal/TemporalFromToQueryRootExpression.cs
  src/EFCore.SqlServer/Query/Internal/TemporalQueryRootExpression.cs
  src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
  src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
  src/EFCore/Query/EntityQueryRootExpression.cs
  src/EFCore/Query/INavigationExpansionExtensibilityHelper.cs
  src/EFCore/Query/Internal/EntityQueryable`.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  src/EFCore/Query/NavigationExpansionExtensibilityHelper.cs
  src/EFCore/Query/QueryRootExpression.cs
  src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSplitQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSplitSharedTypeQueryRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/CompositeKeysSplitQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalPointInTimeQueryRewriter.cs
Labels: breaking-change

#28510 Workaround for Sqlite/InMemory test failures on OSX (again)
  azure-pipelines.yml
  eng/helix.proj
Labels: auto-merge

#28477 Sugar for sequence-based key value generation on SQL Server
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilderDependencies.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Update/IUpdateSqlGenerator.cs
  src/EFCore.Relational/Update/UpdateSqlGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
  src/EFCore.SqlServer/Metadata/SqlServerValueGenerationStrategy.cs
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosFixture.cs
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Specification.Tests/Query/FiltersInheritanceQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/InheritanceModel/Animal.cs
  test/EFCore.Specification.Tests/TestModels/InheritanceModel/Bird.cs
  test/EFCore.Specification.Tests/TestModels/InheritanceModel/Drink.cs
  test/EFCore.Specification.Tests/TestModels/InheritanceModel/InheritanceContext.cs
  test/EFCore.Specification.Tests/TestModels/InheritanceModel/InheritanceData.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerSequenceTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalFiltersInheritanceQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationConflictTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
  test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerValueGenerationStrategyConventionTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataBuilderExtensionsTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
  test/EFCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPCFiltersInheritanceQuerySqliteFixture.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPCInheritanceQuerySqliteFixture.cs
Labels: providers-beware

#28529 Change value generation defaults for numeric keys when using TPC
  src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerFixture.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Labels: providers-beware

#28552 Use Arcade's token replacement task
  eng/Version.Details.xml
  eng/Versions.props
  src/EFCore.Tools/EFCore.Tools.csproj
Labels: auto-merge
