Repository dotnet/efcore, pull requests merged in 2022-03, with the labels that each got.

#27536 Update branding to 6.0.4
  eng/Versions.props
Labels: tell-mode

#27379 [release/6.0] Fix to #27375 - EF Core 6.0 temporal tables - migration rollback doesn't work
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Labels: Servicing-approved

#27428 [release/6.0] SQLite: Don't modify collection while enumerating inside ReclaimLeakedConnections
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionPool.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteConnectionFactoryTest.cs
Labels: Servicing-approved

#27429 [release/6.0] Fix to #27356 - Collection_navigation_equal_to_null_for_subquery fails after merging from release/6.0
  src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: Servicing-approved

#27579 Generate temp values for key properties contained in optional FKs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/Metadata/Internal/PropertyExtensions.cs
  test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
Labels: Servicing-approved

#27565 Scaffolding: Enable text templates
  .github/dependabot.yml
  src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
  src/EFCore.Design/Design/Internal/DatabaseOperations.cs
  src/EFCore.Design/EFCore.Design.csproj
  src/EFCore.Design/Properties/DesignStrings.Designer.cs
  src/EFCore.Design/Properties/DesignStrings.resx
  src/EFCore.Design/Scaffolding/IModelCodeGeneratorSelector.cs
  src/EFCore.Design/Scaffolding/Internal/ModelCodeGeneratorSelector.cs
  src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
  src/EFCore.Design/Scaffolding/Internal/TextTemplatingModelGenerator.cs
  src/EFCore.Design/Scaffolding/ModelCodeGenerationOptions.cs
  src/EFCore.Design/Scaffolding/ModelCodeGenerator.cs
  src/EFCore.Design/Scaffolding/TemplatedModelGenerator.cs
  src/EFCore.Design/TextTemplating/ITextTemplating.cs
  src/EFCore.Design/TextTemplating/ITextTemplatingCallback.cs
  src/EFCore.Design/TextTemplating/Internal/TextTemplatingCallback.cs
  src/EFCore.Design/TextTemplating/Internal/TextTemplatingService.cs
  test/EFCore.Design.Tests/Design/DesignTimeServicesTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorSelectorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/TextTemplatingModelGeneratorTest.cs
  test/EFCore.Design.Tests/TestUtilities/TempDirectory.cs
  test/EFCore.Design.Tests/TextTemplating/Internal/TextTemplatingServiceTest.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/BuildReference.cs
Labels: auto-merge

#27610 Fix SQL Server memory-optimized + temporal tables
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Labels: auto-merge

#27557 Stop deleting orphans for optional relationships configured for cascade deletes
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Labels: breaking-change

#27584 Refactor ReaderModificationCommandBatch
  src/EFCore.Relational/Storage/IRelationalCommandBuilder.cs
  src/EFCore.Relational/Storage/RelationalCommandBuilder.cs
  src/EFCore.Relational/Update/ColumnModification.cs
  src/EFCore.Relational/Update/IColumnModification.cs
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/ModificationCommandBatch.cs
  src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
  src/EFCore.Relational/Update/SingularModificationCommandBatch.cs
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  test/EFCore.Relational.Tests/TestUtilities/TestModificationCommandBatch.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
  test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Labels: auto-merge

#27683 Update branding to preview4
  eng/Versions.props
Labels: area-infrastructure

#27689 Ignore a failing Cosmos test to unblock builds
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
Labels: auto-merge

#27690 Ignore a failing Cosmos test to unblock builds
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
Labels: auto-merge

#27696 Reimplement MaxBatchSize as a pre-check
  src/EFCore.Relational/Update/ModificationCommandBatch.cs
  src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
  src/EFCore.Relational/Update/SingularModificationCommandBatch.cs
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatchFactory.cs
  test/EFCore.Relational.Tests/TestUtilities/TestModificationCommandBatch.cs
  test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Labels: auto-merge
