Repository dotnet/efcore, pull requests merged in 2022-10, with the labels that each got.

#29243 [release/7.0] Query: Don't fail translation of aggregate when owned navigations
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
Labels: Servicing-approved

#29254 Update branding to 3.1.31
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29215 [release/6.0] Microsoft.Data.Sqlite: Avoid re-sending PRAGMA key on pooled connections
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
Labels: Servicing-approved

#29158 [release/6.0] Move to Ubuntu 22.04
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29157 [release/3.1] Move to Ubuntu 22.04
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29005 [release/6.0] Clear reference to DbDataReader from RelationalDataReader
  src/EFCore.Relational/Storage/RelationalDataReader.cs
  test/EFCore.Relational.Tests/Storage/RelationalDataReaderTest.cs
Labels: Servicing-approved

#29227 [release/7.0] Fix for some minor bugs around JSON mappings
  src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonOwnedAllTypes.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonOwnedBranch.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
  test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Labels: Servicing-approved

#29264 [release/2.1] Switch to consolidated Windows build images and Ubuntu 20.04
  build/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#29268 [release/3.1] Switch to consolidated Windows build images
  azure-pipelines.yml
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/post-build/channels/generic-internal-channel.yml
  eng/common/templates/post-build/channels/generic-public-channel.yml
  eng/common/templates/post-build/darc-gather-drop.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/templates/post-build/promote-build.yml
  eng/common/templates/post-build/setup-maestro-vars.yml
Labels: area-infrastructure, tell-mode

#29262 [MQ] Add test changes to AddMonths test for Sqlite
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#29270 [release/7.0] Switch to consolidated Windows build images
  azure-pipelines-richnav.yml
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29271 [main] Switch to consolidated Windows build images and non-Svc pools
  azure-pipelines-richnav.yml
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29269 [release/6.0] Switch to consolidated Windows build images
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#29274 [8.0] Fix to #29260 - Sqlite: AddTicks translation gives incorrect results
  src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#29277 Validate that the main fragment of optional dependents that use table sharing have at least one required non-shared property
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: Servicing-approved

#29285 Validate that if any fragments use table sharing then the main fragments are mapped to the same table
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryTestBase.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteTest.cs
Labels: Servicing-approved

#29288 [release/7.0] Fix to #29279 - EF7 - GroupBy on Json column property + First/FirstOrDefault generates incorrect SQL
  src/EFCore.Relational/Query/JsonQueryExpression.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Labels: Servicing-approved

#29331 Clean up stored procedure tests as NonSharedModelTestBase
  test/Directory.Build.props
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/Entity.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/EntityWithAdditionalProperty.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/EntityWithTwoAdditionalProperties.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/StoredProcedureUpdateContext.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TpcChild.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TpcParent.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TphChild1.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TphChild2.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TphParent.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TptChild.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TptMixedChild.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TptMixedParent.cs
  test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TptParent.cs
  test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Labels: tell-mode, auto-merge

#29328 [release/7.0] Stabilize versions
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29366 [release/7.0] Fix to #29355 - FromSqlRaw throws Exception when querying all objects that contain a certain string property in a json array column
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Labels: Servicing-consider

#29388 [release/7.0] Fix batching boundary with cycle breaking
  src/Shared/Multigraph.cs
  test/EFCore.Relational.Specification.Tests/Update/NonSharedModelUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/NonSharedModelUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/NonSharedModelUpdatesSqliteTest.cs
Labels: Servicing-approved

#29401 Remove SQL Server-specific test config from relational
  test/EFCore.InMemory.FunctionalTests/DataBindingInMemoryTest.cs
  test/EFCore.Specification.Tests/DataBindingTestBase.cs
  test/EFCore.Specification.Tests/F1FixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/DataBindingSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
  test/EFCore.Sqlite.FunctionalTests/DataBindingSqliteTest.cs
Labels: auto-merge

#29407 Fix to #29289 - don't print JSON_QUERY calls when we extract the entire aggregate
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
Labels: auto-merge

#29425 Add CodeQL3000 run to efcore-ci-official
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: area-infrastructure

#29458 !fixup! Correct CodeQL3000 setup
  azure-pipelines.yml
Labels: area-infrastructure
