Repository dotnet/efcore, pull requests merged in 2023-04, with the labels that each got.

#30591 [release/7.0] Fix to #30115 - IndexOutOfRangeException in CreateNavigationExpansionExpression
  src/EFCore/Metadata/IReadOnlyTypeBase.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
Labels: Servicing-approved

#30579 [release/7.x] Fixes around IncludeExpression for ExecuteUpdate/Delete (#30571)
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqliteTest.cs
Labels: Servicing-approved

#30486 [release/7.0] Fix to #30358 - Duplicate table alias in generated select query (An item with the same key has already been added)
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
Labels: Servicing-approved

#30616 [SMALL/TEST ONLY] Small fix to JSON update tests
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Labels: auto-merge

#30615 [release/7.0] Fix to #30330 - Json: updating property with conversion from string to other type fails on sql server
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
Labels: Servicing-approved

#30640 Avoid considering unchanged properties as modified
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
Labels: Servicing-approved

#30763 Remove leading $ from JSON expressions
  src/EFCore.Relational/Query/JsonQueryExpression.cs
  src/EFCore.Relational/Query/PathSegment.cs
  src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
Labels: auto-merge

#30767 Refactor internal usage analyzer
  src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
Labels: auto-merge

#30769 Use JsonScalarExpression for primitive collection indexing
  src/EFCore.Relational/Query/JsonQueryExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGeneratorFactory.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/NonSharedPrimitiveCollectionsQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: auto-merge

#30791 [release/8.0-preview4] Reintroduce the SDK workaround for OSX on Helix
  eng/helix.proj
Labels: tell-mode
