Repository dotnet/efcore, pull requests merged in 2023-02, with the labels that each got.

#30164 Remove unchecks in SQL Server type mappings
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
Labels: auto-merge

#30225 Update branding to 7.0.4
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#30098 [release/7.0] Move taking of lock earlier to avoid race in PruneCallback
  src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Labels: Servicing-approved

#30144 [release/7.0] Fix to #29667 - Count after Take throws "No column name was specified for column 1 of 't'."
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
Labels: Servicing-approved

#30241 [release/7.0] Use default schema for TPC tables (#30214)
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#30275 [release/7.0] Store null table name in the model snapshot for TPC abstract types
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#30252 Simplify SqlExpressionSimplifyingExpressionVisitor
  src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
Labels: auto-merge

#30288 Merging internal commits for release/7.0
  global.json
Labels: area-infrastructure, tell-mode

#30296 Use Arcade's pool-providers.yml
  azure-pipelines-richnav.yml
  azure-pipelines.yml
Labels: area-infrastructure

#30342 Rebrand for 8.0.0-preview3
  eng/Versions.props
Labels: area-infrastructure, auto-merge

#30340 Evaluate SqlServerConvertTranslator.SupportedMethods once
  src/EFCore.SqlServer/Query/Internal/SqlServerConvertTranslator.cs
Labels: auto-merge

#30359 Update SDK to 8.0.100-preview.3.23127.4
  global.json
Labels: area-infrastructure
