Repository dotnet/efcore, pull requests merged in 2023-08, with the labels that each got.

#31264 [release/7.0] Fix to #29572 - Json: predicate on json bool property generates incorrect sql
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Labels: Servicing-approved

#31286 [release/7.0] Bump Microsoft.Data.SqlClient to 5.1.1
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: Servicing-approved

#31495 API review updates
  src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
  src/EFCore.Cosmos/ValueGeneration/IdValueGeneratorFactory.cs
  src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGeneratorFactory.cs
  src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs
  src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
  src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
  src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  src/EFCore/Extensions/Internal/ExpressionExtensions.cs
  src/EFCore/Metadata/IClrPropertyGetter.cs
  src/EFCore/Metadata/Internal/ClrPropertyGetter.cs
  src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
  src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
  src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs
  src/EFCore/Storage/Json/JsonValueReaderWriter.cs
  src/EFCore/Storage/TypeMappingSource.cs
  src/EFCore/Storage/TypeMappingSourceBase.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Storage/RelationalGeometryTypeMappingTest.cs
  test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
  test/EFCore.Specification.Tests/TestUtilities/WktComparer.cs
  test/EFCore.Tests/ApiConsistencyTest.cs
  test/EFCore.Tests/Metadata/Internal/ClrPropertyGetterFactoryTest.cs
Labels: Servicing-approved

#31496 Tiny API review renames
  src/EFCore.Relational/Query/RelationalQueryRootProcessor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
Labels: Servicing-approved

#31494 Memoize flattened property lookup
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  src/EFCore/Metadata/ITypeBase.cs
  src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
  src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/IRuntimeEntityType.cs
  src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
  src/EFCore/Metadata/Internal/PropertyBase.cs
  src/EFCore/Metadata/Internal/TypeBase.cs
  src/EFCore/Metadata/RuntimeComplexType.cs
  src/EFCore/Metadata/RuntimeEntityType.cs
  src/EFCore/Metadata/RuntimeTypeBase.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
Labels: Servicing-approved

#31454 31355: SQLite: Add EF.Functions.Unhex
  src/EFCore.Sqlite.Core/Extensions/SqliteDbFunctionsExtensions.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteHexMethodTranslator.cs
  test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
Labels: community-contribution

#31548 Bump SQLitePCLRaw from 2.1.6-pre20230809203314 to 2.1.6
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
  test/EFCore.NativeAotTests/EFCore.NativeAotTests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/EFCore.TrimmingTests/EFCore.TrimmingTests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: area-infrastructure, type-dependency update :arrow_up_small:
