Repository dotnet/efcore, pull requests merged in 2023-01, with the labels that each got.

#29973 Update branding to 7.0.3
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#29965 Use raw string literals in scaffolding tests
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/TextTemplatingModelGeneratorTest.cs
Labels: auto-merge

#29717 [release/7.0] Fix SQL Server bulk insert edge case (#29669)
  src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
  test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Labels: Servicing-approved

#29722 [release/7.0] Fix bug where a non-sproc command comes before a sproc command
  src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
  test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Labels: Servicing-approved

#29723 [release/7.0] Support entities with owned types in ExecuteUpdate setter property lambda
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
  test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTInheritanceBulkUpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
Labels: Servicing-approved

#29724 [release/7.0] Use correct parameter in query based on type mapping
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: Servicing-approved

#29731 [release/7.0] Scaffolding: Fix missing HasForeignKey when principal key is an alternate key
  src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: Servicing-approved

#29778 [release/7.0] Allow shared columns with nullable value converters
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Update/ModificationCommand.cs
  test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Address.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
  test/EFCore.Specification.Tests/UpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
Labels: Servicing-approved

#29784 [release/7.0] Fix making column required on SQL Server with idempotent migrations
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Labels: Servicing-approved

#29797 [release/7.0] Reset query tracking behavior correctly if set on DbContextOptions
  src/EFCore/DbContext.cs
  src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
  test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Labels: Servicing-approved

#29807 [release/7.0] Avoid redundant looping in property metadata
  src/EFCore/Metadata/Internal/Property.cs
Labels: Servicing-approved

#29820 [release/7.0] Include table name for overrides in snapshot.
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#29822 [release/7.0] Allow underscores in identifiers again
  src/EFCore.Design/Design/Internal/CSharpHelper.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Labels: Servicing-approved

#29850 [release/7.0] Avoid infinite loop during foreign key discovery
  src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
  test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
Labels: Servicing-approved

#29920 [release/7.0] Update discriminator columns when PK-to-PK dependent type is changed
  src/EFCore.Relational/Update/ModificationCommand.cs
  test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Gift.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Lift.cs
  test/EFCore.Specification.Tests/UpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPCTest.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPTTest.cs
Labels: Servicing-approved

#29921 [release/7.0] Avoid circular dependency for unique indexes with null values
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  src/EFCore.Relational/Update/Internal/CompositeRowIndexValueFactory.cs
  src/EFCore.Relational/Update/Internal/CompositeRowKeyValueFactory.cs
  src/EFCore.Relational/Update/Internal/CompositeRowValueFactory.cs
  src/EFCore.Relational/Update/Internal/IRowIndexValueFactory.cs
  src/EFCore.Relational/Update/Internal/IRowIndexValueFactory`.cs
  src/EFCore.Relational/Update/Internal/SimpleRowIndexValueFactory.cs
  src/EFCore/Update/EquatableKeyValue.cs
  test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
Labels: Servicing-approved

#29867 [release/7.0] Revert shared columns validation breaking change
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Labels: Servicing-approved

#29991 Correct [Obsolete] message for AutoTransactionBehavior
  src/EFCore/Infrastructure/DatabaseFacade.cs
Labels: auto-merge

#29983 Some tweaks to the daily build docs
  docs/DailyBuilds.md
Labels: auto-merge

#29982 Fix test string assertion
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: auto-merge

#29779 [release/7.0] Scaffolding: Handle FK on keyless entity type
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#29793 [release/7.0] Scaffolding: Fix code for EF6 many-to-many pattern
  src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: Servicing-approved

#29960 Allow transfer of ownership of DbConnection from application to DbContext
  src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
  src/EFCore.Relational/Storage/IRelationalConnection.cs
  src/EFCore.Relational/Storage/RelationalConnection.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
  test/EFCore.Relational.Tests/RelationalConnectionTest.cs
  test/EFCore.Relational.Tests/RelationalEventIdTest.cs
  test/EFCore.Relational.Tests/RelationalOptionsExtensionTest.cs
  test/EFCore.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs
  test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
  test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
Labels: providers-beware

#30021 Correct ExpressionPrinter in [DebuggerDisplay]
  src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs
Labels: auto-merge

#30024 Fix split query over GroupBy over parameter
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindEFPropertyIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindStringIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
Labels: auto-merge

#30030 [release/7.0] Fix split query over GroupBy over parameter (#30024)
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
Labels: Servicing-approved

#30036 [release/7.0] Update to SQLitePCLRaw 2.1.4
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
  src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
  test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Labels: Servicing-approved

#30047 [release/7.0] Take schema into account when comparing FK constraints.
  src/EFCore.Relational/Metadata/Internal/ForeignKeyConstraintComparer.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Labels: Servicing-consider

#29917 Allow opting out of RETURNING/OUTPUT clauses in SaveChanges
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
  src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Builders/OwnedNavigationSplitTableBuilder.cs
  src/EFCore.Relational/Metadata/Builders/SplitTableBuilder.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerEntityTypeMappingFragmentExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerTableBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerTableExtensions.cs
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOutputClauseConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteEntityTypeExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteEntityTypeMappingFragmentExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteTableBuilderExtensions.cs
  src/EFCore.Sqlite.Core/Extensions/SqliteTableExtensions.cs
  src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteModelValidator.cs
  src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationNames.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
  src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
  src/EFCore.Sqlite.Core/Update/Internal/SqliteLegacyUpdateSqlGenerator.cs
  src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/ITriggerAddedConvention.cs
  src/EFCore/Metadata/Conventions/ITriggerRemovedConvention.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.DelayedConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationIdentityWithoutOutputSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationSequenceWithoutOutputSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationWithoutOutputSqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationWithoutOutputSqlServerTestBase.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerOutputClauseConventionTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/StoreValueGenerationLegacySqliteTest.cs
  test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
  test/EFCore.Sqlite.Tests/Metadata/Builders/SqliteBuilderExtensionsTest.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
Labels: auto-merge

#30177 [release/8.0-preview1] Rebrand for release
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#30178 Rebrand for 8.0.0-preview2
  eng/Versions.props
Labels: area-infrastructure
