Repository dotnet/efcore, pull requests merged in 2023-05, with the labels that each got.

#30794 [release/7.0] Fix to #30575 - Multiple LeftJoins (GroupJoins) lead to GroupJoin Exception when the same where is used twice
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
Labels: Servicing-approved

#30784 [release/7.0] fixing a typo in quirk string for issue 30330
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
Labels: tell-mode

#30821 Disable VB tests
  test/EFCore.VisualBasic.FunctionalTests/EFCore.VisualBasic.FunctionalTests.vbproj
Labels: auto-merge

#30825 Re-introduce quirk with typo
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
Labels: tell-mode

#30828 [release/7.0] Bump SqlClient to 5.0.2 due to bad memory bug in 5.0.1
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#30939 Allow value comparers for supertypes of the mapping's type
  src/EFCore/Storage/CoreTypeMapping.cs
Labels: auto-merge
