Repository dotnet/efcore, pull requests merged in 2023-06, with the labels that each got.

#30992 SDK update
  global.json
  test/EFCore.Design.Tests/DesignExceptionTest.cs
  test/EFCore.Tests/ExceptionTest.cs
Labels: auto-merge

#30911 [release/7.0] Stop skipping shadow skip navigation slots when creating the shadow values array
  src/EFCore/ChangeTracking/Internal/ShadowValuesFactoryFactory.cs
  src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
  src/EFCore/ChangeTracking/Internal/TemporaryValuesFactoryFactory.cs
  src/EFCore/Infrastructure/ExpressionExtensions.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
Labels: Servicing-approved

#31148 No longer scaffold nullable booleans when column has a default value
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: providers-beware
