Repository dotnet/efcore, pull requests merged in 2023-07, with the labels that each got.

#31036 [release/7.x] Disable trigger enumeration on Azure Synapse Analytics, where triggers are not supported
  src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
Labels: Servicing-approved, community-contribution

#31013 [release/6.0] Microsoft.Data.Sqlite: Fix handling of queries with RETURNING clause
  src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
  src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Labels: Servicing-approved

#31198 [manual] Merge branch 'release/6.0' => 'release/7.0'
  src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
  src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Labels: area-infrastructure, auto-merge, type-merge forward :fast_forward:

#31202 [manual] Merge branch 'release/7.0' => 'main'
  src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
  src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Labels: area-infrastructure, auto-merge, type-merge forward :fast_forward:

#31284 Update SDK to 8.0.100-rc.1.23370.3
  global.json
Labels: area-infrastructure, auto-merge

#31321 Fix NativeAOT warnings in EFCore.Abstractions
  benchmark/EFCore.Benchmarks/EFCore.Benchmarks.csproj
  benchmark/EFCore.SqlServer.Benchmarks/EFCore.SqlServer.Benchmarks.csproj
  benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
  src/EFCore.Abstractions/ChangeTracking/Internal/ObservableBackedBindingList.cs
  src/EFCore.Abstractions/ChangeTracking/Internal/SortableBindingList.cs
  src/EFCore.Abstractions/ChangeTracking/ObservableCollectionListSource.cs
  src/EFCore.Abstractions/EFCore.Abstractions.csproj
  src/EFCore.Abstractions/ObservableCollectionExtensions.cs
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  src/EFCore.Design/EFCore.Design.csproj
  src/EFCore.InMemory/EFCore.InMemory.csproj
  src/EFCore.Proxies/EFCore.Proxies.csproj
  src/EFCore.Relational/EFCore.Relational.csproj
  src/EFCore.SqlServer.HierarchyId/EFCore.SqlServer.HierarchyId.csproj
  src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
  src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
  src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
  src/EFCore.Sqlite/EFCore.Sqlite.csproj
  src/EFCore/EFCore.csproj
  src/dotnet-ef/dotnet-ef.csproj
  test/EFCore.Analyzers.Tests/EFCore.Analyzers.Tests.csproj
  test/EFCore.AspNet.InMemory.FunctionalTests/EFCore.AspNet.InMemory.FunctionalTests.csproj
  test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
  test/EFCore.AspNet.SqlServer.FunctionalTests/EFCore.AspNet.SqlServer.FunctionalTests.csproj
  test/EFCore.AspNet.Sqlite.FunctionalTests/EFCore.AspNet.Sqlite.FunctionalTests.csproj
  test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
  test/EFCore.Cosmos.Tests/EFCore.Cosmos.Tests.csproj
  test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj
  test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
  test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj
  test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj
  test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
  test/EFCore.Proxies.Tests/EFCore.Proxies.Tests.csproj
  test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
  test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
  test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
  test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
  test/EFCore.SqlServer.HierarchyId.Tests/EFCore.SqlServer.HierarchyId.Tests.csproj
  test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj
  test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
  test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj
  test/EFCore.Tests/EFCore.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
  test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
  test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
  test/ef.Tests/ef.Tests.csproj
Labels: auto-merge

#31363 Implemented missing methods in the SaveChangesInterceptorAggregator
  src/EFCore/Diagnostics/Internal/SaveChangesInterceptorAggregator.cs
Labels: community-contribution
