Repository dotnet/efcore, pull requests merged in 2023-11, with the labels that each got.

#32203 Revert to latest public preview of the .NET SDK
  Directory.Build.targets
  eng/Version.Details.xml
  eng/Versions.props
  eng/helix.proj
  global.json
Labels: auto-merge

#32265 [release/8.0] Contains nullability processing
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32266 [release/8.0] Visit arguments in QueryableMethodNormalizingExpressionVisitor after converting List.Contains (#32219)
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32253 [release/8.0] Fix to #32235 - Buffering error in JSON deserialization with junk data
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs
  src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs
  src/EFCore/Storage/Json/JsonReaderData.cs
  src/EFCore/Storage/Json/Utf8JsonReaderManager.cs
  test/EFCore.InMemory.FunctionalTests/BadDataJsonDeserializationInMemoryTest.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
  test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs
  test/EFCore.Specification.Tests/JsonTypesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BadDataJsonDeserializationSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/BadDataJsonDeserializationSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/JsonQueryAdHocSqliteTest.cs
Labels: Servicing-approved

#32285 [release/8.0] Stop throwing for complex type properties when sensitive data logging is on
  src/EFCore/Diagnostics/CoreLoggerExtensions.cs
  test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Labels: Servicing-approved

#32221 Make ModelBuilderTest asserts more robust and extensible
  eng/Versions.props
  src/EFCore/Metadata/Internal/Model.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.InMemory.Tests/ModelBuilding/InMemoryModelBuilderGenericTest.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
  test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
  test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
  test/EFCore.Specification.Tests/TestUtilities/ForeignKeyStrictComparer.cs
  test/EFCore.Specification.Tests/TestUtilities/MetadataExtensions.cs
  test/EFCore.Specification.Tests/TestUtilities/NavigationComparer.cs
  test/EFCore.Specification.Tests/TestUtilities/PropertyComparer.cs
  test/EFCore.Specification.Tests/TestUtilities/TestAnnotationComparer.cs
  test/EFCore.Specification.Tests/TestUtilities/TestIndexComparer.cs
  test/EFCore.Specification.Tests/TestUtilities/TestKeyComparer.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderNonGenericTest.cs
  test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
  test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
  test/EFCore.Tests/ModelBuilding/ComplexTypeTestBase.cs
  test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
  test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/ModelBuilding/ShadowEntityTypeTest.cs
Labels: providers-beware

#32298 Update to .NET 8 GA
  global.json
Labels: auto-merge

#32330 Add primitive collection regression test
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: auto-merge

#32317 [release/8.0] Fix to #32217 - Nav expansion visitor does not visit the Contains item argument (and possibly other non-lambda arguments)
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: Servicing-approved

#32355 [release/8.0] Do extra processing for init-only fields (#32342)
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
Labels: Servicing-consider

#32368 [release/8.0] Don't throw when attempting to load from a newly Added entity with unknown FK values
  src/EFCore/Internal/EntityFinder.cs
  test/EFCore.Specification.Tests/LazyLoadTestBase.cs
Labels: Servicing-approved

#32334 [release/7.0] Fix to #31448 Use token for NonQueryResultAsync (#31449)
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
Labels: Servicing-approved
