Repository dotnet/efcore, pull requests merged in 2023-03, with the labels that each got.

#30380 [SMALL] Fix to #30330 - Json: updating property with conversion from string to other type fails on sql server
  src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
Labels: auto-merge

#30412 Optimize SqliteDataReader.GetFieldValue
  All.sln.DotSettings
  src/Microsoft.Data.Sqlite.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Labels: auto-merge

#30394 [release/7.0] Handle entity paths with no tables in model differ
  src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Labels: Servicing-approved

#30343 [release/7.0] Add back setter for scaffolded collection navigations
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
  src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.tt
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Labels: Servicing-approved

#30333 [release/7.0] Fix to #30028 - Added nullable property to Json mapped model resulting in errors instead of mapping non existing json property to null
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
Labels: Servicing-approved

#30427 Better exception when same parameter instance is reused in multiple lambdas
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/ExpressionEqualityComparer.cs
Labels: auto-merge

#30454 Regression test for #30181 - Missing parentheses when using Expression.Or over bool (instead of OrElse)
  test/EFCore.Relational.Specification.Tests/Query/OperatorsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OperatorsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/OperatorsQuerySqliteTest.cs
Labels: auto-merge

#30480 Fix Typo
  src/EFCore/Metadata/RuntimeEntityType.cs
Labels: auto-merge

#30451 [release/7.0] Fix to #30273 - EF7 generating incorrect SQL for the Concat/Union All, The same code was working fine for EF6.4.4
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
Labels: Servicing-approved

#30593 Trim the mapping store type base name
  src/EFCore.Relational/Storage/RelationalTypeMapping.cs
  test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs
Labels: auto-merge

#29346 Proposed fix for Optional RestartSequenceOperation.StartValue #26560
  src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
  src/EFCore.Relational/Migrations/MigrationBuilder.cs
  src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
  src/EFCore.Relational/Migrations/Operations/RestartSequenceOperation.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Labels: providers-beware
