Repository dotnet/efcore, pull requests merged in 2023-09, with the labels that each got.

#31638 Rename SQL Azure to Azure SQL
  src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteDbContextOptionsBuilderExtensions.cs
  src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Diagnostics/ConflictingValueGenerationStrategiesEventData.cs
  src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
  src/EFCore.SqlServer/Extensions/SqlServerComplexTypePrimitiveCollectionBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerComplexTypePropertyBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerDatabaseFacadeExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerKeyBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerMigrationBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPrimitiveCollectionBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerDbFunctionConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerMemoryOptimizedTablesConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOutputClauseConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerRuntimeModelConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerTemporalConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
  src/EFCore.SqlServer/Metadata/SqlServerValueGenerationStrategy.cs
  src/EFCore.SqlServer/Migrations/Operations/SqlServerCreateDatabaseOperation.cs
  src/EFCore.SqlServer/Migrations/Operations/SqlServerDropDatabaseOperation.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
Labels: auto-merge

#30470 Add readme file for nuget package EFCore.Tools
  src/EFCore.Tools/README.md
Labels: propose-close

#30471 Add readme for EFcore.Desgin NuGet package
  src/EFCore.Design/README.md
Labels: propose-close

#30466 Add readme for sql server
  src/EFCore.SqlServer/README.md
Labels: propose-close

#31663 [TEST ONLY] Add tests for #30885 - DateOnly/TimeOnly with JSON exceptions in preview 4
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonOwnedAllTypes.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
  test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Labels: auto-merge

#30831 Add support for DATA_COMPRESSION and SORT_IN_TEMPDB SQL Server index options
  src/EFCore.SqlServer/DataCompressionType.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
  src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerRuntimeModelConvention.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
  src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
  src/EFCore.SqlServer/Properties/SqlServerStrings.resx
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
  test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
  test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
  test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Labels: waiting-for-response

#31828 Queries for struct complex types
  src/EFCore.Proxies/Proxies/Internal/ProxyBindingInterceptor.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore/Metadata/DefaultValueBinding.cs
  src/EFCore/Metadata/Internal/ConstructorBindingFactory.cs
  src/EFCore/Query/Internal/EntityMaterializerSource.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/ComplexTypeQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/ComplexTypeQueryFixtureBase.cs
  test/EFCore.Specification.Tests/Query/ComplexTypeQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/QueryTestBase.cs
  test/EFCore.Specification.Tests/TestModels/ComplexTypeModel/ComplexTypeData.cs
  test/EFCore.Specification.Tests/TestModels/ComplexTypeModel/Model.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
Labels: Servicing-approved

#31853 [release/8.0] Set default discriminator value even when there are no derived types.
  src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/DiscriminatorConvention.cs
  src/EFCore/Metadata/Conventions/IDiscriminatorPropertySetConvention.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.DelayedConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
  src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  test/EFCore.Tests/Metadata/Conventions/DiscriminatorConventionTest.cs
  test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
  test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
Labels: Servicing-approved

#31863 [release/8.0] Fail fast when using EF8 primitive collections with the Cosmos provider
  src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
  test/EFCore.Cosmos.FunctionalTests/JsonTypesCosmosTest.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ComplexTypeTestBase.cs
Labels: Servicing-consider

#31868 [release/8.0] Move sentinel to end of AddProperty
  src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
  src/EFCore/Metadata/RuntimeTypeBase.cs
  test/EFCore.NativeAotTests/CompiledModels/UserEntityType.cs
Labels: Servicing-consider

#31872 [release/8.0] Don't remove entry from dependent map if it's not found in identity map.
  src/EFCore/ChangeTracking/Internal/IdentityMap.cs
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Labels: Servicing-approved

#31856 [release/8.0] Fix to #30589 - Query/Json: improve JSON entity/collection comparisons to null (fails currently for optional dependent with all nullable properties)
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/OptionalDependentQueryFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/OptionalDependentQueryTestBase.cs
  test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentData.cs
  test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentJsonAllOptional.cs
  test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentJsonSomeRequired.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/OptionalDependentQuerySqliteTest.cs
Labels: Servicing-consider
