Repository dotnet/efcore, pull requests merged in 2024-06, with the labels that each got.

#33768 Set publishAssetsImmediately on post-build
  azure-pipelines.yml
Labels: tell-mode

#33891 Add support for `object` in `SqlServerConvertTranslator`
  src/EFCore.SqlServer/Query/Internal/Translators/SqlServerConvertTranslator.cs
  test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
Labels: community-contribution

#33939 [release/8.0] Add missing check for predicate in primitive collection simplifications
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#33966 [release/8.0] Use TokenCredential for Cosmos tests
  All.sln
  azure-pipelines.yml
  eng/Versions.props
  test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/ConnectionSpecificationTest.cs
  test/EFCore.Cosmos.FunctionalTests/CosmosConcurrencyTest.cs
  test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
  test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
  test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
  test/EFCore.Cosmos.FunctionalTests/ReloadTest.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosCondition.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosConditionAttribute.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestHelpers.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs
Labels: tell-mode

#34080 Use XOR to translate some NOT expressions
  src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: breaking-change
