Repository dotnet/efcore, pull requests merged in 2024-01, with the labels that each got.

#32706 Fix to #32570 - Test/Cleanup: some adhoc tests that are provider only… because hardcoded column types etc can be moved from provider to relational/core
  test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
  test/EFCore.Specification.Tests/Query/AdHocMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/AdHocMiscellaneousQuerySqliteTest.cs
Labels: auto-merge

#32612 [release/8.0] Check value converter configuration source when setting element type.
  src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
  test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
  test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: Servicing-approved

#32582 [release/8.0] Ensure that, by convention, dependent properties have the same element type as principal properties
  All.sln.DotSettings
  src/EFCore/Metadata/Conventions/ConventionSet.cs
  src/EFCore/Metadata/Conventions/ElementMappingConvention.cs
  src/EFCore/Metadata/Conventions/ElementTypeChangedConvention.cs
  src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
  test/EFCore.Cosmos.FunctionalTests/KeysWithConvertersCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/KeysWithConvertersInMemoryTest.cs
  test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs
Labels: Servicing-approved

#32543 [release/8.0] Fix Contains within SQL Server aggregate functions
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryCompilationContext.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitorFactory.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitorFactory.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqliteTest.cs
Labels: Servicing-approved

#32523 [release/8.0] Revert behavior to throw when attempting to modify an unconstrained alternate key property
  src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
  test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOne.cs
Labels: Servicing-approved

#32520 [release/8.0] Infer type mapping suitable for concatenating two results (#32510)
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/CompositeKeysQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/CompositeKeysSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NullSemanticsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/OptionalDependentQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPCGearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
  test/EFCore.VisualBasic.FunctionalTests/NorthwindQueryVisualBasicTest.vb
Labels: Servicing-approved

#32489 [release/8.0] Cosmos: Generate ordinal values for key properties that used not to be persisted.
  src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
  src/EFCore.Cosmos/Metadata/Conventions/CosmosValueGenerationConvention.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
Labels: Servicing-approved

#32463 [release/8.0] Make ILazyLoader not IDisposable (#32345)
  src/EFCore.Abstractions/Infrastructure/ILazyLoader.cs
  src/EFCore/ChangeTracking/Internal/StateManager.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Infrastructure/Internal/ILazyLoaderFactory.cs
  src/EFCore/Infrastructure/Internal/LazyLoaderFactory.cs
  test/EFCore.Tests/Infrastructure/EntityFrameworkServicesBuilderTest.cs
Labels: Servicing-approved

#32454 [release/8.0] Allow empty inline collections (#32414)
  src/EFCore.Relational/Query/QuerySqlGenerator.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Query/PrimitiveCollectionsQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32440 [release/8.0] Add method postfix when rewriting parameters for StartsWith/EndsWith/Contains
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/FunkyDataQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQueryFiltersQuerySqliteTest.cs
Labels: Servicing-approved

#32434 [release/8.0] Allow opting out of new subquery translation for Contains
  src/EFCore/EF.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32467 [release/8.0] Visit inside InlineQueryRootExpression in nav expansion
  src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Labels: Servicing-approved

#32504 [release/8.0] Fix expression cloning when table changes in SelectExpression.VisitChildren
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: Servicing-approved

#32598 [release/8.0] Improve the relationship cycle breaking logic to detect cycles even when not starting on one.
  src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
  src/EFCore/Metadata/Internal/Property.cs
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/Shared/HashHelpers.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
  test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Labels: Servicing-approved

#32731 [release/8.0] Don't try to cast negative enum values to ulong
  src/EFCore/Storage/Json/JsonWarningEnumReaderWriter.cs
  test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEnum.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Labels: Servicing-approved

#32729 [release/8.0] Don't detect join table with other incoming references as a simple join table
  src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Labels: Servicing-approved

#32753 [release/8.0] Change the return type of OwnedNavigationBuilder.PrimitiveCollection
  src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
  test/EFCore.Tests/ModelBuilding/ComplexTypeTestBase.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
  test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
  test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Labels: Servicing-approved

#32789 Fix test baseline due to bad merge
  test/EFCore.SqlServer.FunctionalTests/BulkUpdates/ComplexTypeBulkUpdatesSqlServerTest.cs
Labels: auto-merge

#32764 [release/8.x] Produce uncorrelated IN for Contains with nullable item (#32575)
  src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlNullabilityProcessor.cs
  test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindEFPropertyIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindStringIncludeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32807 [release/8.0] Don't discover DbFunctions when building ad-hoc model
  src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
  src/EFCore.Relational/Metadata/Internal/RelationalAdHocMapper.cs
  src/EFCore/Metadata/Internal/AdHocMapper.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Labels: Servicing-approved

#32840 [release/6.0] Update SqlClient dependency
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#32841 [release/7.0] Update SqlClient dependency
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#32838 [release/8.0] Bump SqlClient version
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#32845 [TINY/TESTONLY] Resolution to #32515 - Query: primitive collection parameters values should reflect the type they are representing
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs
Labels: auto-merge

#31190 stackalloc for BytesToDecimal
  src/EFCore/Storage/ValueConversion/NumberToBytesConverter.cs
Labels: community-contribution

#32770 Microsoft.Data.Sqlite.Core issue with multiple Blob colums
  src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
  test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Labels: waiting-for-response, community-contribution

#32951 Fix copy paste typo
  src/dotnet-ef/Project.cs
Labels: community-contribution
