Repository dotnet/efcore, pull requests merged in 2024-08, with the labels that each got.

#34326 Add missing ConditionalTheory Attribute to Delete_FromSql_converted_to_subquery
  test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesRelationalTestBase.cs
Labels: community-contribution

#34232 [release/8.0] Update Helix pools
  azure-pipelines-public.yml
  azure-pipelines.yml
  eng/helix.proj
Labels: tell-mode

#34234 [release/6.0] Update Helix pools
  azure-pipelines-public.yml
  azure-pipelines.yml
Labels: tell-mode

#34342 [release/8.0] Use placeholder value to fix CredScan
  azure-pipelines-public.yml
  azure-pipelines.yml
  eng/helix.proj
Labels: tell-mode

#34388 [release/8.0] Find the discriminator property even if it is not string
  src/EFCore/Metadata/Internal/InternalTypeBaseBuilder.cs
  test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Labels: Servicing-approved

#34484 Enable PoliCheck
  azure-pipelines.yml
Labels: tell-mode

#34486 Update Microsoft.Build.Locator
  src/EFCore.Design/EFCore.Design.csproj
Labels: tell-mode

#34478 (RC2) Persist `Id` values into owned collection JSON documents
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
  src/EFCore.Relational/Metadata/Conventions/RelationalKeyDiscoveryConvention.cs
  src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  test/EFCore.Cosmos.FunctionalTests/Query/JsonQueryCosmosFixture.cs
  test/EFCore.Cosmos.FunctionalTests/Query/JsonQueryCosmosTest.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.ModelSnapshot.cs
  test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
  test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.Json.cs
  test/EFCore.Specification.Tests/Query/JsonQueryFixtureBase.cs
  test/EFCore.Specification.Tests/TestModels/JsonQuery/JsonOwnedBranch.cs
  test/EFCore.Specification.Tests/TestModels/JsonQuery/JsonOwnedRoot.cs
  test/EFCore.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/OwnedType0EntityType.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/OwnedType0EntityType.cs
  test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Labels: Servicing-approved, tell-mode

#34495 (RC2) Cosmos: strip implicit casts to allow vector search over arrays
  src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
  test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
Labels: Servicing-approved, tell-mode

#34514 Rename some locals
  src/EFCore.Relational/Metadata/Internal/StoredProcedureComparer.cs
Labels: Servicing-approved, tell-mode

#34529 (RC2) (Test only) Fix async void tests
  test/EFCore.Specification.Tests/MusicStoreTestBase.cs
  test/EFCore.Specification.Tests/SpatialTestBase.cs
Labels: tell-mode

#34523 [release/9.0] Add explicit casts for generated null in method calls.
  src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalBaseEntityType.cs
  test/EFCore.Cosmos.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalDerivedEntityType.cs
  test/EFCore.Design.Tests/Query/LinqToCSharpSyntaxTranslatorTest.cs
  test/EFCore.InMemory.FunctionalTests/Scaffolding/Baselines/Custom_value_converter/MyEntityEntityType.cs
  test/EFCore.InMemory.FunctionalTests/Scaffolding/CompiledModelInMemoryTest.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalBaseEntityType.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalDerivedEntityType.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/PrincipalBaseEntityType.cs
  test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/PrincipalDerivedEntityType.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalBaseEntityType.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel/PrincipalDerivedEntityType.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/PrincipalBaseEntityType.cs
  test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/PrincipalDerivedEntityType.cs
Labels: tell-mode

#34560 [release/9.0] Properly implement support for Cosmos hierarchical partition keys
  src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryDiscriminatorInIdTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryInheritanceTestBase.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryNoDiscriminatorInIdTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryRootDiscriminatorInIdTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTestBase.cs
Labels: tell-mode

#34540 (RC2) Downgrade to LTS SqlClient
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#34547 [release/9.0] Always include generated files in the compilation
  src/EFCore.Tasks/buildTransitive/Microsoft.EntityFrameworkCore.Tasks.targets
Labels: tell-mode
