Repository dotnet/efcore, pull requests merged in 2024-09, with the labels that each got.

#34489 [release/9.0] Acquire the migrations database lock in a transaction.
  src/EFCore.Relational/Diagnostics/RelationalEventId.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
  src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
  src/EFCore.Relational/Migrations/HistoryRepository.cs
  src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
  src/EFCore.Relational/Migrations/IHistoryRepository.cs
  src/EFCore.Relational/Migrations/IMigrationCommandExecutor.cs
  src/EFCore.Relational/Migrations/IMigrationsDatabaseLock.cs
  src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  src/EFCore.Relational/Migrations/LockReleaseBehavior.cs
  src/EFCore.Relational/Migrations/MigrationExecutionState.cs
  src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
  src/EFCore.Relational/Properties/RelationalStrings.resx
  src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
  src/EFCore.SqlServer/Migrations/Internal/SqlServerHistoryRepository.cs
  src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
  src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs
  src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationDatabaseLock.cs
  test/EFCore.Design.Tests/Design/DesignTimeServicesTest.cs
  test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
  test/EFCore.Relational.Tests/Extensions/RelationalDatabaseFacadeExtensionsTest.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs
Labels: providers-beware, tell-mode

#34561 [release/8.0] Update FK ElementType when the FK properties change.
  src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
  src/EFCore/Metadata/Conventions/ElementTypeChangedConvention.cs
  src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
  test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
  test/EFCore.Tests/ModelBuilding/TestModel.cs
Labels: Servicing-approved

#34587 [release/9.0] Generate correct calls for complex and primitive properties in the model snapshot
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.ModelSnapshot.cs
Labels: tell-mode

#34614 [release/9.0] Don't remove non-existent foreign keys.
  src/EFCore/Metadata/Internal/EntityType.cs
  src/EFCore/Metadata/Internal/InternalModelBuilder.cs
  test/EFCore.Cosmos.FunctionalTests/ModelBuilding/CosmosModelBuilderGenericTest.cs
Labels: Servicing-approved, tell-mode

#34623 [release/9.0] Set shared database throughput when using RBAC in tests
  test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
Labels: area-test, tell-mode

#34626 [release/9.0] Take into account store-generated values when ordering update commands
  src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
  test/EFCore.Relational.Specification.Tests/Update/UpdatesRelationalTestBase.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/Product.cs
  test/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
  test/EFCore.Specification.Tests/Update/UpdatesTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Update/UpdatesSqlServerTPCTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/UpdatesSqlServerTPTTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/UpdatesSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Update/UpdatesSqlServerTestBase.cs
Labels: Servicing-approved

#34636 [release/9.0] Nominally upgrade Microsoft.Build.Framework to 17.8.3
  src/EFCore.Design/EFCore.Design.csproj
Labels: Servicing-approved

#34639 [release/9.0] Bump Microsoft.Azure.Cosmos from 3.42.0 to 3.43.0
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
Labels: Servicing-approved, tell-mode

#34648 [release/9.0] Update Microsoft.CodeAnalysis.Testing packages to 1.1.2
  eng/Versions.props
  test/EFCore.Analyzers.Tests/TestUtilities/CSharpAnalyzerVerifier.cs
  test/EFCore.Analyzers.Tests/TestUtilities/CSharpCodeFixVerifier.cs
Labels: Servicing-approved

#34640 [release/9.0] Remove referencing indexes when reconfiguring a property as a navigation
  src/EFCore/Metadata/Internal/InternalTypeBaseBuilder.cs
  test/EFCore.Cosmos.FunctionalTests/ModelBuilding/CosmosModelBuilderGenericTest.cs
  test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.OwnedTypes.cs
  test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.TestModel.cs
Labels: Servicing-approved, tell-mode

#34624 [release/9.0] Change some JSON Metadata API to respect null values set explicitly.
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
  src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
  src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
  test/EFCore.SqlServer.FunctionalTests/ModelBuilding/SqlServerModelBuilderTestBase.cs
Labels: Servicing-approved, tell-mode

#34663 [release/9.0] Fix type mapping management for JsonScalarExpression
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressionFactory.cs
  test/EFCore.Cosmos.FunctionalTests/Query/PrimitiveCollectionsQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerJsonTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: tell-mode

#34669 [release/9.0] Update SDK to 9.0.100-rc.1.24452.12
  global.json
Labels: Servicing-approved, tell-mode

#34535 Move runtime override to tests
  Directory.Build.targets
  test/Directory.Build.props
Labels: blocked

#34711 Remove package source mapping and suppress warning
  Directory.Packages.props
  NuGet.config
  src/EFCore.Analyzers/EFCore.Analyzers.csproj
  src/EFCore.Design/EFCore.Design.csproj
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
  src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
  src/EFCore.Tasks/EFCore.Tasks.csproj
Labels: Servicing-approved, tell-mode

#34712 [release/9.0] Use the correct comparer when sorting relational functions.
  src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
  test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Labels: Servicing-approved

#34717 [release/9.0] Rename IncludeRootDiscriminatorInJsonId to HasRootDiscriminatorInJsonId
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeBuilderExtensions.cs
  src/EFCore.Cosmos/Extensions/CosmosModelBuilderExtensions.cs
  test/EFCore.Cosmos.FunctionalTests/FindCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/KeysWithConvertersCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
  test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryRootDiscriminatorInIdTest.cs
Labels: Servicing-approved

#34744 [release/9.0] Disabling a flaky test
  test/EFCore.Specification.Tests/Query/AdHocMiscellaneousQueryTestBase.cs
Labels: area-test, tell-mode

#34743 [release/9.0] Fix to #34728 - Split query with AsNoTrackingWithIdentityResolution() throws ArgumentOutOfRangeException
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  test/EFCore.Relational.Specification.Tests/Query/AdHocQuerySplittingQueryTestBase.cs
Labels: Servicing-approved

#34759 [release/9.0] Tools: Fallback to service provider when no context types found
  src/EFCore.Design/Design/Internal/DbContextOperations.cs
  test/EFCore.AspNet.Specification.Tests/AspNetIdentityCustomTypesDefaultTestBase.cs
  test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
Labels: Servicing-approved

#34777 [release/9.0] Use the specified migrations assembly in validation
  src/EFCore.Design/Design/Internal/MigrationsOperations.cs
  src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs
  test/EFCore.Design.Tests/Design/Internal/MigrationsOperationsTest.cs
Labels: Servicing-approved
