Repository dotnet/efcore, pull requests merged in 2024-02, with the labels that each got.

#32982 [release/8.0] NuGet package readme files
  Directory.Build.targets
  src/EFCore.Abstractions/PACKAGE.md
  src/EFCore.Analyzers/AnalyzerReleases.Shipped.md
  src/EFCore.Analyzers/EFCore.Analyzers.nuspec
  src/EFCore.Analyzers/PACKAGE.md
  src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
  src/EFCore.Cosmos/PACKAGE.md
  src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
  src/EFCore.Design/PACKAGE.md
  src/EFCore.Design/README.md
  src/EFCore.InMemory/PACKAGE.md
  src/EFCore.Proxies/PACKAGE.md
  src/EFCore.Relational/PACKAGE.md
  src/EFCore.SqlServer.Abstractions/PACKAGE.md
  src/EFCore.SqlServer.HierarchyId/PACKAGE.md
  src/EFCore.SqlServer.NTS/PACKAGE.md
  src/EFCore.SqlServer/PACKAGE.md
  src/EFCore.SqlServer/README.md
  src/EFCore.Sqlite.Core/PACKAGE.md
  src/EFCore.Sqlite.NTS/PACKAGE.md
  src/EFCore.Sqlite/PACKAGE.md
  src/EFCore.Templates/PACKAGE.md
  src/EFCore.Tools/EFCore.Tools.nuspec
  src/EFCore.Tools/PACKAGE.md
  src/EFCore.Tools/README.md
  src/EFCore/PACKAGE.md
  src/Microsoft.Data.Sqlite.Core/Package.md
  src/Microsoft.Data.Sqlite/PACKAGE.md
  src/dotnet-ef/PACKAGE.md
  src/dotnet-ef/dotnet-ef.nuspec
  test/EFCore.AspNet.Specification.Tests/PACKAGE.md
  test/EFCore.Relational.Specification.Tests/PACKAGE.md
  test/EFCore.Specification.Tests/PACKAGE.md
Labels: Servicing-approved

#32941 [release/8.0] Also catch type initialization errors when attempting to load types that might not exist
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Labels: Servicing-approved

#32928 [release/8.0] Throw for empty strings in primitive collection columns
  src/EFCore/Properties/CoreStrings.Designer.cs
  src/EFCore/Properties/CoreStrings.resx
  src/EFCore/Storage/Json/JsonValueReaderWriter.cs
  test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Labels: Servicing-approved

#32851 [release/8.0] Stop stripping new lines from migration script literals (#32788)
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsInfrastructureTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsInfrastructureSqliteTest.cs
Labels: Servicing-approved

#32925 [release/8.0] Don't assume that FK of skip navigation is non-null
  src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
  test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerOnDeleteConventionTest.cs
Labels: Servicing-approved

#32869 [release/8.0] Use the unpatched shared framework as the minimum requirement for tools.
  Directory.Build.targets
Labels: Servicing-approved

#32894 [release/8.0] Handle complex types in GetDatabaseValues
  src/EFCore/ChangeTracking/Internal/ArrayPropertyValues.cs
  src/EFCore/ChangeTracking/Internal/EntryPropertyValues.cs
  src/EFCore/Internal/EntityFinder.cs
  src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
  src/EFCore/Query/Internal/EntityMaterializerSource.cs
  test/EFCore.InMemory.FunctionalTests/PropertyValuesInMemoryTest.cs
  test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
Labels: Servicing-approved

#32963 [release/8.0] Stop specifying incorrect column name in snapshot for owned type of generic entity type
  src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#32919 [release/8.0] Stop using case-insensitive comparisons for indexed properties (#32899)
  src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
  src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
  src/EFCore/Storage/TypeMappingInfo.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
  test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTestBase.cs
Labels: Servicing-approved

#33042 [release/7.0] Update SqlClient dependency
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#33043 [release/8.0] Update SqlClient dependency
  src/EFCore.SqlServer/EFCore.SqlServer.csproj
Labels: tell-mode

#33050 [TEST ONLY] moving tests for #32972 to relational so we also test SqLite
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
Labels: auto-merge

#33076 [TEST ONLY] Move AdHoc tests relying on MARS to SqlServer suite
  test/EFCore.Specification.Tests/Query/AdHocMiscellaneousQueryTestBase.cs
  test/EFCore.Specification.Tests/Query/AdHocNavigationsQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocNavigationsQuerySqlServerTest.cs
Labels: auto-merge
