Repository dotnet/efcore, pull requests merged in 2024-05, with the labels that each got.

#33622 [release/8.0] Don't generate a discriminator in the snapshot if there's no discriminator property.
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
  test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Labels: Servicing-approved

#33548 [release/8.0] Fix parameter names for nested types in complex type equality (#33527)
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
  test/EFCore.Specification.Tests/Query/AdHocComplexTypeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocComplexTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/AdHocComplexTypeQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
Labels: Servicing-approved

#33665 [release/2.1] Fix artifact publishing
  azure-pipelines.yml
Labels: tell-mode

#33692 [release/8.0] Fix to #33547 - Breaking Change in 8.0.4: System.InvalidOperationException: The data is NULL at ordinal 0. This method can't be called on NULL values. Check using IsDBNull before calling.
  src/EFCore.Relational/Query/RelationalStructuralTypeShaperExpression.cs
  test/EFCore.Specification.Tests/Query/ComplexTypeQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
Labels: Servicing-approved

#33743 [release/6.0] Update CODEOWNERS
  .github/CODEOWNERS
Labels: tell-mode

#33744 [release/8.0] Update CODEOWNERS
  .github/CODEOWNERS
Labels: tell-mode

#33804 Pass sequence annotations (#33780)
  src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
  test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Labels: community-contribution
