Repository dotnet/efcore, pull requests merged in 2024-04, with the labels that each got.

#33346 [release/8.0] [CG] Update Microsoft.CodeAnalysis.Testing
  eng/Versions.props
Labels: tell-mode

#33349 [release/7.0] [CG] Update Azure.Identity
  test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
Labels: tell-mode

#33355 [release/6.0] Update EOL OS versions
  azure-pipelines-public.yml
  azure-pipelines.yml
  eng/helix.proj
Labels: tell-mode

#33356 [release/6.0] [CG] Update Microsoft.Azure.Cosmos
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
Labels: tell-mode

#33305 [release/8.0] Onboard the official build to 1ES pipeline templates
  .config/guardian/.gdnbaselines
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: tell-mode

#33304 [release/7.0] Onboard the official build to 1ES pipeline templates
  .config/guardian/.gdnbaselines
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: tell-mode

#33303 [release/6.0] Onboard the official build to 1ES pipeline templates
  .config/guardian/.gdnbaselines
  .config/tsaoptions.json
  azure-pipelines.yml
Labels: tell-mode

#33471 chore: remove repetitive words
  src/EFCore/ChangeTracking/Internal/InternalEntityEntry.RelationshipsSnapshot.cs
  src/EFCore/DbContextOptionsBuilder.cs
  src/EFCore/DbContextOptionsBuilder`.cs
Labels: community-contribution

#33480 Add the VMR configuration file
  eng/DotNetBuild.props
Labels: area-infrastructure

#33552 [release/2.1] Separate public pipeline
  azure-pipelines-public.yml
  build/dependencies.props
Labels: tell-mode

#33567 [release/2.1] Onboard the official build to 1ES pipeline templates
  azure-pipelines-public.yml
  azure-pipelines.yml
  build/dependencies.props
  build/templates/default-build.yml
Labels: tell-mode

#33561 InMemoryTable: Make IsConcurrencyConflict() method more readable
  src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
Labels: community-contribution
