Repository dotnet/efcore, pull requests merged in 2025-08, with the labels that each got.

#36490 [release/9.0] Dispose related readers in GroupBySplitQueryingEnumerable (#36484)
  src/EFCore.Relational/Query/Internal/GroupBySplitQueryingEnumerable.cs
  src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
Labels: Servicing-approved

#36595 [RC2, TESTS] Complex type test fixes
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.StructuralEquality.cs
  test/EFCore.Cosmos.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsCollectionCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsCosmosFixture.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/OwnedNavigations/OwnedNavigationsRelationalFixtureBase.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/OwnedTableSplitting/OwnedTableSplittingRelationalFixtureBase.cs
  test/EFCore.Specification.Tests/Query/Relationships/OwnedNavigations/OwnedNavigationsFixtureBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/OwnedJson/OwnedJsonCollectionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsCollectionSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsCollectionSqliteTest.cs
Labels: tell-mode

#36598 [release/10.0][TESTS-ONLY] Improve parameter splitting
  src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
  test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Labels: tell-mode

#36610 [release/10.0-rc1] Fix whitespace in Microsoft.EntityFrameworkCore.Tasks.props
  src/EFCore.Tasks/buildTransitive/Microsoft.EntityFrameworkCore.Tasks.props
Labels: Servicing-approved

#36615 [RC2] - Suppress BinSkim BA2008 warning for SqlServerSpatial170.dll
  .config/guardian/gdnbaselines
  eng/common/sdl/configure-sdl-tool.ps1
Labels: ask-mode

#36620 [rc2] Fix complex collection type in model snapshot
  src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
  test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.ModelSnapshot.cs
Labels: ask-mode

#36635 [rc2] Fix some minor documentation errors.
  src/EFCore.Abstractions/Infrastructure/ILazyLoader.cs
  src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
  src/EFCore.Relational/Query/PathSegment.cs
  src/EFCore/Diagnostics/IInterceptors.cs
  src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
  src/EFCore/Query/ShapedQueryCompilingExpressionVisitorDependencies.cs
  src/Shared/ExpressionVisitorExtensions.cs
Labels: tell-mode

#36631 [rc2] Fix tests for Azure SQL and SQL Server 2025
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryJsonTypeSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrecompiledSqlPregenerationQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerJsonTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/ComplexJson/ComplexJsonCollectionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/ComplexJson/ComplexJsonSqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Translations/BasicTypesQuerySqlServerFixture.cs
  test/EFCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureDatabaseCreationTest.cs
  test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDbContextOptionsBuilderExtensions.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
  test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
  test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateJsonTypeSqlServerTest.cs
Labels: tell-mode

#36639 [RC2] Fix structural Contains with JSON collections
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.StructuralEquality.cs
  test/EFCore.Cosmos.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsStructuralEqualityCosmosTest.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/ComplexTableSplitting/ComplexTableSplittingStructuralEqualityRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/OwnedJson/OwnedJsonStructuralEqualityRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/OwnedNavigations/OwnedNavigationsStructuralEqualityRelationalTestBase.cs
  test/EFCore.Relational.Specification.Tests/Query/Relationships/OwnedTableSplitting/OwnedTableSplittingStructuralEqualityRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/Relationships/RelationshipsData.cs
  test/EFCore.Specification.Tests/Query/Relationships/RelationshipsStructuralEqualityTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/ComplexJson/ComplexJsonStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/ComplexTableSplitting/ComplexTableSplittingStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/Navigations/NavigationsStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/OwnedJson/OwnedJsonStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Relationships/OwnedTableSplitting/OwnedTableSplittingStructuralEqualitySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Relationships/OwnedJson/OwnedJsonStructuralEqualitySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Relationships/OwnedNavigations/OwnedNavigationsStructuralEqualitySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Relationships/OwnedTableSplitting/OwnedTableSplittingStructuralEqualitySqliteTest.cs
Labels: ask-mode

#36662 [rc2] Revert migrator behavior to use a transaction for each migration (when possible)
  src/EFCore.Relational/Migrations/Internal/Migrator.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsInfrastructureSqliteTest.cs
Labels: ask-mode

#36642 [rc2] Fix transformation from JsonQueryExpression to OPENJSON
  src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Associations/ComplexJson/ComplexJsonCollectionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Associations/ComplexJson/ComplexJsonProjectionSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Associations/ComplexJson/ComplexJsonSetOperationsSqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Associations/ComplexJson/ComplexJsonStructuralEqualitySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryJsonTypeSqlServerTest.cs
Labels: ask-mode

#36683 [RC2] Rename "relationship" to "structural property"
  src/EFCore.Relational/Query/CollectionResultExpression.cs
  src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
  src/EFCore.Relational/Query/JsonQueryExpression.cs
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.StructuralEquality.cs
  src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
  src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
  src/EFCore/Query/LiftableConstantExpressionHelpers.cs
Labels: tell-mode
