Repository dotnet/efcore, pull requests merged in 2025-04, with the labels that each got.

#35933 [release/9.0] Disable Cosmos tests on CI
  azure-pipelines.yml
  test/EFCore.Cosmos.FunctionalTests/Query/AdHocJsonQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/AdHocMiscellaneousQueryCosmosTest.cs
Labels: ask-mode

#35909 [release/9.0-staging] Cosmos Full Text Search support (query part)
  src/EFCore.Analyzers/EFDiagnostics.cs
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
  src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
  src/EFCore.Cosmos/Properties/CosmosStrings.resx
  src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
  src/EFCore.Cosmos/Query/Internal/CosmosQuerySqlGenerator.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.InExpressionValuesExpandingExpressionVisitor.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.PagingQueryingEnumerable.cs
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
  src/EFCore.Cosmos/Query/Internal/Expressions/FragmentExpression.cs
  src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
  src/EFCore.Cosmos/Query/Internal/Expressions/SqlFunctionExpression.cs
  src/EFCore.Cosmos/Query/Internal/Translators/CosmosFullTextSearchTranslator.cs
  src/EFCore.Cosmos/Query/Internal/Translators/CosmosVectorSearchTranslator.cs
Labels: Servicing-approved

#35606 SQLite: implement MAX/MIN/ORDER BY for `decimal`
  src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/Translators/SqliteQueryableAggregateMethodTranslator.cs
  src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
  test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Ef6GroupBySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQuerySqliteFixture.cs
Labels: community-contribution

#35954 [release/9.0] Bump version of Cosmos SDK from 3.45 to 3.48 to improve hybrid search experience out of the box
  Directory.Packages.props
  src/EFCore.Cosmos/EFCore.Cosmos.csproj
Labels: Servicing-approved

#34171 Translate COALESCE as ISNULL
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Labels: community-contribution

#35992 [release/10.0-preview4] Disable cosmos tests on CI
  azure-pipelines.yml
Labels: ask-mode
