Repository dotnet/efcore, pull requests merged in 2025-09, with the labels that each got.

#36685 [rc2] Properly handle automatic rollbacks in SQLite in Commit.
  src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
Labels: ask-mode

#36707 [rc2] Update MSBuild and Roslyn dependencies to sim-ship versions
  Directory.Packages.props
  eng/Version.Details.props
  eng/Version.Details.xml
  eng/Versions.props
  test/EFCore.Relational.Specification.Tests/Query/PrecompiledQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Directory.Packages.props
  test/EFCore.SqlServer.FunctionalTests/Query/PrecompiledQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/PrecompiledSqlPregenerationQuerySqlServerTest.cs
Labels: tell-mode

#36716 [rc2] [TEST-ONLY] Add SQL Server spatial type tests
  test/EFCore.Cosmos.FunctionalTests/Types/CosmosMiscellaneousTypeTest.cs
  test/EFCore.Cosmos.FunctionalTests/Types/CosmosNumericTypeTest.cs
  test/EFCore.Cosmos.FunctionalTests/Types/CosmosTemporalTypeTest.cs
  test/EFCore.Relational.Specification.Tests/RelationalTypeTestBase.cs
  test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
  test/EFCore.Specification.Tests/TypeTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Types/SqlServerGeographyTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Types/SqlServerGeometryTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Types/SqlServerMiscellaneousTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Types/SqlServerNumericTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Types/SqlServerTemporalTypeTest.cs
  test/EFCore.Sqlite.FunctionalTests/Types/SqliteMiscellaneousTypeTest.cs
  test/EFCore.Sqlite.FunctionalTests/Types/SqliteNumericTypeTest.cs
  test/EFCore.Sqlite.FunctionalTests/Types/SqliteTemporalTypeTest.cs
Labels: tell-mode

#36736 Small refactoring in analyzer.
  src/EFCore.Analyzers/NullableAttributes.cs
  src/EFCore.Analyzers/StringsUsageInRawQueriesDiagnosticAnalyzer.cs
  test/EFCore.Analyzers.Tests/StringInterpolationInRawQueriesAnalyzerTests.cs
Labels: tell-mode

#36739 [rc2] Enable the JSON data type for Azure SQL Database
  src/EFCore.SqlServer/Infrastructure/Internal/SqlServerSingletonOptions.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
  test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
Labels: ask-mode

#36238 [rc2] Fix DefaultIfEmpty and nullability within SelectMany selector
  src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
  src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
  test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
  test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServer160Test.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Labels: ask-mode

#36776 [release/8.0] Disable Guardian Dotnet Analyzers
  azure-pipelines.yml
Labels: tell-mode

#36779 [8.0] Resolve query logger from QueryContext in shaper generation (#36758)
  src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
Labels: Servicing-approved

#36762 [rc2] Add the threat model.
  docs/security.md
  docs/threat_model.md
Labels: tell-mode

#36803 [rc2] Adapt SQL Server legacy enum test to new JSON type
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerJsonTypeTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTest.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTestBase.cs
Labels: tell-mode

#36855 [release/8.0] Remove OSX.13.Amd64 target from HelixTargetQueues
  azure-pipelines.yml
Labels: tell-mode
