Repository dotnet/efcore, pull requests merged in 2025-03, with the labels that each got.

#35617 Improve LoadExtension to work correctly with dotnet run and lib* named libs
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Labels: community-contribution

#35718 [release/8.0-staging] Improve LoadExtension to work correctly with dotnet run and lib* named libs
  .github/workflows/TestCosmos.yaml
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Labels: Servicing-approved

#35717 [release/9.0-staging] Improve LoadExtension to work correctly with dotnet run and lib* named libs
  src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Labels: Servicing-approved

#35719 [release/9.0-staging] Transform Span-based overloads to Enumerable in funcletizer
  src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
Labels: Servicing-approved

#35776 [release/9.0-staging] Fix to #35162 - Regression from EF Core 8 to 9: MigrationBuilder.DropTable Causes Issues with Subsequent Table Recreation
  src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
  test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
Labels: Servicing-approved

#35782 [release/9.0-staging] Fix to #21006 - Support a default value for non-nullable properties
  src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
  test/EFCore.Cosmos.FunctionalTests/Query/AdHocCosmosTestHelpers.cs
  test/EFCore.Cosmos.FunctionalTests/Query/AdHocJsonQueryCosmosTest.cs
  test/EFCore.Cosmos.FunctionalTests/Query/AdHocMiscellaneousQueryCosmosTest.cs
  test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
  test/EFCore.Relational.Specification.Tests/Query/AdHocJsonQueryRelationalTestBase.cs
  test/EFCore.Specification.Tests/Query/AdHocJsonQueryTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTestBase.cs
  test/EFCore.Sqlite.FunctionalTests/Query/AdHocJsonQuerySqliteTest.cs
Labels: Servicing-approved

#35805 [release/10.0-preview3] Disable Cosmos tests
  azure-pipelines.yml
Labels: tell-mode

#35822 [release/10.0-preview3] Prevent Cosmos tests from running
  azure-pipelines.yml
Labels: tell-mode

#34999 Support translating some string functions when they have a char parameters
  src/EFCore.Cosmos/Query/Internal/Translators/CosmosStringMethodTranslator.cs
  src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
  src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
  src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
  src/EFCore.Sqlite.Core/Query/Internal/Translators/SqliteStringMethodTranslator.cs
  test/EFCore.Cosmos.FunctionalTests/Query/Translations/StringTranslationsCosmosTest.cs
  test/EFCore.Specification.Tests/Query/Translations/StringTranslationsTestBase.cs
  test/EFCore.SqlServer.FunctionalTests/Query/Translations/StringTranslationsSqlServerTest.cs
  test/EFCore.Sqlite.FunctionalTests/Query/Translations/StringTranslationsSqliteTest.cs
Labels: community-contribution

#35835 Fixed Lazy loader performance issues
  src/EFCore/Infrastructure/Internal/LazyLoader.cs
  test/EFCore.Specification.Tests/LoadTestBase.cs
Labels: community-contribution
